x-common-env: &common-env
  - CGO_ENABLED=1
  - GOFLAGS=-buildvcs=false
  - PYBUILD_NO_DOCKER=1
  - VENV=/tmp/venv
  - YES=1
  - PATH=/opt/goenv/bin:/opt/goenv/shims:/opt/pyenv/bin:/opt/pyenv/shims:/opt/nodeenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

services:
  build:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspace
    environment: *common-env
    volumes:
      - .:/workspace
    entrypoint: ["/bin/bash", "-c"]
    command: ["make dysvm dashboard build"]

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspace
    environment: *common-env
    volumes:
      - .:/workspace
    entrypoint: ["/bin/bash", "-c"]
    command: ["make test"]

  shell:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspace
    environment: *common-env
    volumes:
      - .:/workspace
    entrypoint: ["/bin/bash", "-c"]
    command: ["bash"]
