x-common: &common
  build:
    context: .
    dockerfile: Dockerfile.dev
  network_mode: host
  working_dir: /workspace/dysonprotocol2
  environment:
    - YES=1
    - GOBIN=/usr/local/bin
  volumes:
    - .:/workspace/dysonprotocol2
    - ./.docker-home:/home/user
  entrypoint: ["/bin/bash", "-c"]

services:
  build:
    <<: *common
    command: ["make dysvm build"]

  test:
    <<: *common
    command: ["make dev-install test PYTEST_ARGS='--tb=long'"]

  shell:
    <<: *common
    command: ["bash"]
