[pytest]
testpaths = tests
addopts = -v --tb=short --strict-markers --strict-config --headed --browser chromium --screenshot only-on-failure --tracing retain-on-failure -m "not docs" --ignore=tests/state_channels
python_files = test_*.py
python_classes = Test*
python_functions = test_*


# Log levels
log_cli = True
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

# Markers
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
    frontend: marks tests as frontend tests
    visual: marks tests as visual regression tests
    basics: tests for basic functionality
    script: tests for script management
    storage: tests for storage operations
    crontasks: tests for crontask scheduling
    wsgi: tests for WSGI endpoints
    docs: tests for documentation notebooks
    nameservice: tests for nameservice module operations
