// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file dysonprotocol/crontask/v1/tx.proto (package dysonprotocol.crontask.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Any, Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Coin } from "../../../cosmos/base/v1beta1/coin_pb.js";
import { Params } from "./crontask_pb.js";

/**
 * MsgCreateTask defines the message for creating a new task
 *
 * @generated from message dysonprotocol.crontask.v1.MsgCreateTask
 */
export class MsgCreateTask extends Message<MsgCreateTask> {
  /**
   * Address of the creator of the task
   *
   * @generated from field: string creator = 1;
   */
  creator = "";

  /**
   * Unix timestamp when the task is scheduled to execute
   * Can be either a Unix timestamp or a time offset prefixed with "+" (e.g.
   * "+1h30m") Offset is relative to the current block time
   *
   * @generated from field: string scheduled_timestamp = 2;
   */
  scheduledTimestamp = "";

  /**
   * Unix timestamp after which the task will expire if not executed
   * Can be either a Unix timestamp or a time offset prefixed with "+" (e.g.
   * "+2h") When using an offset, it's relative to the scheduled_timestamp
   *
   * @generated from field: string expiry_timestamp = 3;
   */
  expiryTimestamp = "";

  /**
   * Maximum gas limit for the task execution
   *
   * @generated from field: uint64 task_gas_limit = 4;
   */
  taskGasLimit = protoInt64.zero;

  /**
   * Gas fee for the task execution
   *
   * @generated from field: cosmos.base.v1beta1.Coin task_gas_fee = 5;
   */
  taskGasFee?: Coin;

  /**
   * Messages to execute as part of the task
   *
   * @generated from field: repeated google.protobuf.Any msgs = 7;
   */
  msgs: Any[] = [];

  constructor(data?: PartialMessage<MsgCreateTask>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.MsgCreateTask";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "scheduled_timestamp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "expiry_timestamp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "task_gas_limit", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "task_gas_fee", kind: "message", T: Coin },
    { no: 7, name: "msgs", kind: "message", T: Any, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgCreateTask {
    return new MsgCreateTask().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgCreateTask {
    return new MsgCreateTask().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgCreateTask {
    return new MsgCreateTask().fromJsonString(jsonString, options);
  }

  static equals(a: MsgCreateTask | PlainMessage<MsgCreateTask> | undefined, b: MsgCreateTask | PlainMessage<MsgCreateTask> | undefined): boolean {
    return proto3.util.equals(MsgCreateTask, a, b);
  }
}

/**
 * MsgCreateTaskResponse defines the response for creating a new task
 *
 * @generated from message dysonprotocol.crontask.v1.MsgCreateTaskResponse
 */
export class MsgCreateTaskResponse extends Message<MsgCreateTaskResponse> {
  /**
   * The ID of the created task
   *
   * @generated from field: uint64 task_id = 1;
   */
  taskId = protoInt64.zero;

  constructor(data?: PartialMessage<MsgCreateTaskResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.MsgCreateTaskResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "task_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgCreateTaskResponse {
    return new MsgCreateTaskResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgCreateTaskResponse {
    return new MsgCreateTaskResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgCreateTaskResponse {
    return new MsgCreateTaskResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgCreateTaskResponse | PlainMessage<MsgCreateTaskResponse> | undefined, b: MsgCreateTaskResponse | PlainMessage<MsgCreateTaskResponse> | undefined): boolean {
    return proto3.util.equals(MsgCreateTaskResponse, a, b);
  }
}

/**
 * MsgDeleteTask defines the message for deleting a task
 *
 * @generated from message dysonprotocol.crontask.v1.MsgDeleteTask
 */
export class MsgDeleteTask extends Message<MsgDeleteTask> {
  /**
   * Address of the creator of the task
   *
   * @generated from field: string creator = 1;
   */
  creator = "";

  /**
   * ID of the task to delete
   *
   * @generated from field: uint64 task_id = 2;
   */
  taskId = protoInt64.zero;

  constructor(data?: PartialMessage<MsgDeleteTask>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.MsgDeleteTask";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "task_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgDeleteTask {
    return new MsgDeleteTask().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgDeleteTask {
    return new MsgDeleteTask().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgDeleteTask {
    return new MsgDeleteTask().fromJsonString(jsonString, options);
  }

  static equals(a: MsgDeleteTask | PlainMessage<MsgDeleteTask> | undefined, b: MsgDeleteTask | PlainMessage<MsgDeleteTask> | undefined): boolean {
    return proto3.util.equals(MsgDeleteTask, a, b);
  }
}

/**
 * MsgDeleteTaskResponse defines the response for deleting a task
 *
 * @generated from message dysonprotocol.crontask.v1.MsgDeleteTaskResponse
 */
export class MsgDeleteTaskResponse extends Message<MsgDeleteTaskResponse> {
  constructor(data?: PartialMessage<MsgDeleteTaskResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.MsgDeleteTaskResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgDeleteTaskResponse {
    return new MsgDeleteTaskResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgDeleteTaskResponse {
    return new MsgDeleteTaskResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgDeleteTaskResponse {
    return new MsgDeleteTaskResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgDeleteTaskResponse | PlainMessage<MsgDeleteTaskResponse> | undefined, b: MsgDeleteTaskResponse | PlainMessage<MsgDeleteTaskResponse> | undefined): boolean {
    return proto3.util.equals(MsgDeleteTaskResponse, a, b);
  }
}

/**
 * ---------------------------------------------------------------------------
 * MsgUpdateParams
 * ---------------------------------------------------------------------------
 * UpdateParams defines a governance operation for updating the x/crontask
 * module parameters. The authority defaults to the x/gov module account.
 *
 * @generated from message dysonprotocol.crontask.v1.MsgUpdateParams
 */
export class MsgUpdateParams extends Message<MsgUpdateParams> {
  /**
   * authority is the address that controls the module (defaults to x/gov unless
   * overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority = "";

  /**
   * params defines the x/crontask parameters to update.
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: dysonprotocol.crontask.v1.Params params = 2;
   */
  params?: Params;

  constructor(data?: PartialMessage<MsgUpdateParams>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.MsgUpdateParams";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "params", kind: "message", T: Params },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined, b: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParams, a, b);
  }
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * @generated from message dysonprotocol.crontask.v1.MsgUpdateParamsResponse
 */
export class MsgUpdateParamsResponse extends Message<MsgUpdateParamsResponse> {
  constructor(data?: PartialMessage<MsgUpdateParamsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.MsgUpdateParamsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined, b: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParamsResponse, a, b);
  }
}

/**
 * CreateSubscription
 *
 * @generated from message dysonprotocol.crontask.v1.MsgCreateSubscription
 */
export class MsgCreateSubscription extends Message<MsgCreateSubscription> {
  /**
   * @generated from field: string creator = 1;
   */
  creator = "";

  /**
   * @generated from field: string filter = 2;
   */
  filter = "";

  /**
   * @generated from field: string script_address = 3;
   */
  scriptAddress = "";

  /**
   * @generated from field: string function = 4;
   */
  function = "";

  /**
   * @generated from field: string args = 5;
   */
  args = "";

  /**
   * @generated from field: string kwargs = 6;
   */
  kwargs = "";

  /**
   * @generated from field: uint64 task_gas_limit = 7;
   */
  taskGasLimit = protoInt64.zero;

  /**
   * @generated from field: cosmos.base.v1beta1.Coin task_gas_fee = 8;
   */
  taskGasFee?: Coin;

  constructor(data?: PartialMessage<MsgCreateSubscription>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.MsgCreateSubscription";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "filter", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "script_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "function", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "args", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "kwargs", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "task_gas_limit", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 8, name: "task_gas_fee", kind: "message", T: Coin },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgCreateSubscription {
    return new MsgCreateSubscription().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgCreateSubscription {
    return new MsgCreateSubscription().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgCreateSubscription {
    return new MsgCreateSubscription().fromJsonString(jsonString, options);
  }

  static equals(a: MsgCreateSubscription | PlainMessage<MsgCreateSubscription> | undefined, b: MsgCreateSubscription | PlainMessage<MsgCreateSubscription> | undefined): boolean {
    return proto3.util.equals(MsgCreateSubscription, a, b);
  }
}

/**
 * @generated from message dysonprotocol.crontask.v1.MsgCreateSubscriptionResponse
 */
export class MsgCreateSubscriptionResponse extends Message<MsgCreateSubscriptionResponse> {
  /**
   * @generated from field: uint64 subscription_id = 1;
   */
  subscriptionId = protoInt64.zero;

  constructor(data?: PartialMessage<MsgCreateSubscriptionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.MsgCreateSubscriptionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subscription_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgCreateSubscriptionResponse {
    return new MsgCreateSubscriptionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgCreateSubscriptionResponse {
    return new MsgCreateSubscriptionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgCreateSubscriptionResponse {
    return new MsgCreateSubscriptionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgCreateSubscriptionResponse | PlainMessage<MsgCreateSubscriptionResponse> | undefined, b: MsgCreateSubscriptionResponse | PlainMessage<MsgCreateSubscriptionResponse> | undefined): boolean {
    return proto3.util.equals(MsgCreateSubscriptionResponse, a, b);
  }
}

/**
 * DeleteSubscription
 *
 * @generated from message dysonprotocol.crontask.v1.MsgDeleteSubscription
 */
export class MsgDeleteSubscription extends Message<MsgDeleteSubscription> {
  /**
   * @generated from field: string creator = 1;
   */
  creator = "";

  /**
   * @generated from field: uint64 subscription_id = 2;
   */
  subscriptionId = protoInt64.zero;

  constructor(data?: PartialMessage<MsgDeleteSubscription>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.MsgDeleteSubscription";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "subscription_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgDeleteSubscription {
    return new MsgDeleteSubscription().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgDeleteSubscription {
    return new MsgDeleteSubscription().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgDeleteSubscription {
    return new MsgDeleteSubscription().fromJsonString(jsonString, options);
  }

  static equals(a: MsgDeleteSubscription | PlainMessage<MsgDeleteSubscription> | undefined, b: MsgDeleteSubscription | PlainMessage<MsgDeleteSubscription> | undefined): boolean {
    return proto3.util.equals(MsgDeleteSubscription, a, b);
  }
}

/**
 * @generated from message dysonprotocol.crontask.v1.MsgDeleteSubscriptionResponse
 */
export class MsgDeleteSubscriptionResponse extends Message<MsgDeleteSubscriptionResponse> {
  constructor(data?: PartialMessage<MsgDeleteSubscriptionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.MsgDeleteSubscriptionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgDeleteSubscriptionResponse {
    return new MsgDeleteSubscriptionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgDeleteSubscriptionResponse {
    return new MsgDeleteSubscriptionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgDeleteSubscriptionResponse {
    return new MsgDeleteSubscriptionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgDeleteSubscriptionResponse | PlainMessage<MsgDeleteSubscriptionResponse> | undefined, b: MsgDeleteSubscriptionResponse | PlainMessage<MsgDeleteSubscriptionResponse> | undefined): boolean {
    return proto3.util.equals(MsgDeleteSubscriptionResponse, a, b);
  }
}

/**
 * RenewSubscription
 *
 * @generated from message dysonprotocol.crontask.v1.MsgRenewSubscription
 */
export class MsgRenewSubscription extends Message<MsgRenewSubscription> {
  /**
   * @generated from field: string creator = 1;
   */
  creator = "";

  /**
   * @generated from field: uint64 subscription_id = 2;
   */
  subscriptionId = protoInt64.zero;

  constructor(data?: PartialMessage<MsgRenewSubscription>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.MsgRenewSubscription";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "subscription_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRenewSubscription {
    return new MsgRenewSubscription().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRenewSubscription {
    return new MsgRenewSubscription().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRenewSubscription {
    return new MsgRenewSubscription().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRenewSubscription | PlainMessage<MsgRenewSubscription> | undefined, b: MsgRenewSubscription | PlainMessage<MsgRenewSubscription> | undefined): boolean {
    return proto3.util.equals(MsgRenewSubscription, a, b);
  }
}

/**
 * @generated from message dysonprotocol.crontask.v1.MsgRenewSubscriptionResponse
 */
export class MsgRenewSubscriptionResponse extends Message<MsgRenewSubscriptionResponse> {
  constructor(data?: PartialMessage<MsgRenewSubscriptionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.MsgRenewSubscriptionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRenewSubscriptionResponse {
    return new MsgRenewSubscriptionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRenewSubscriptionResponse {
    return new MsgRenewSubscriptionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRenewSubscriptionResponse {
    return new MsgRenewSubscriptionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRenewSubscriptionResponse | PlainMessage<MsgRenewSubscriptionResponse> | undefined, b: MsgRenewSubscriptionResponse | PlainMessage<MsgRenewSubscriptionResponse> | undefined): boolean {
    return proto3.util.equals(MsgRenewSubscriptionResponse, a, b);
  }
}

