// Since: cosmos-sdk 0.46

// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file dysonprotocol/script/v1/tx.proto (package dysonprotocol.script.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Any, Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";

/**
 * MsgUpdateScript is the Msg/UpdateScript request type.
 *
 * @generated from message dysonprotocol.script.v1.MsgUpdateScript
 */
export class MsgUpdateScript extends Message<MsgUpdateScript> {
  /**
   * address is the account address of the script.
   *
   * @generated from field: string address = 1;
   */
  address = "";

  /**
   * script is the updated script.
   *
   * @generated from field: string code = 2;
   */
  code = "";

  constructor(data?: PartialMessage<MsgUpdateScript>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgUpdateScript";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateScript {
    return new MsgUpdateScript().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateScript {
    return new MsgUpdateScript().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateScript {
    return new MsgUpdateScript().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateScript | PlainMessage<MsgUpdateScript> | undefined, b: MsgUpdateScript | PlainMessage<MsgUpdateScript> | undefined): boolean {
    return proto3.util.equals(MsgUpdateScript, a, b);
  }
}

/**
 * MsgUpdateScriptResponse is the Msg/UpdateScript response type.
 *
 * @generated from message dysonprotocol.script.v1.MsgUpdateScriptResponse
 */
export class MsgUpdateScriptResponse extends Message<MsgUpdateScriptResponse> {
  /**
   * version is the updated script version.
   *
   * @generated from field: uint64 version = 1;
   */
  version = protoInt64.zero;

  constructor(data?: PartialMessage<MsgUpdateScriptResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgUpdateScriptResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "version", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateScriptResponse {
    return new MsgUpdateScriptResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateScriptResponse {
    return new MsgUpdateScriptResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateScriptResponse {
    return new MsgUpdateScriptResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateScriptResponse | PlainMessage<MsgUpdateScriptResponse> | undefined, b: MsgUpdateScriptResponse | PlainMessage<MsgUpdateScriptResponse> | undefined): boolean {
    return proto3.util.equals(MsgUpdateScriptResponse, a, b);
  }
}

/**
 * MsgExec executes a script by calling a function with arguments.
 *
 * @generated from message dysonprotocol.script.v1.MsgExec
 */
export class MsgExec extends Message<MsgExec> {
  /**
   * executor is the account address used to execute the script.
   *
   * @generated from field: string executor_address = 1;
   */
  executorAddress = "";

  /**
   * address is the script bech32 address to execute.
   *
   * @generated from field: string script_address = 2;
   */
  scriptAddress = "";

  /**
   * script_name is the optional nameservice name of the script to execute
   * (e.g., "example.dys")
   *
   * @generated from field: string script_name = 3;
   */
  scriptName = "";

  /**
   * Only if the executor is the owner of the script  will the optional
   * extra_code be temporary appended to the script for this message before
   * calling the function.
   *
   * @generated from field: string extra_code = 4;
   */
  extraCode = "";

  /**
   * The function name to run
   *
   * @generated from field: string function_name = 5;
   */
  functionName = "";

  /**
   * The positional arguments to pass to the function (*args) encoded as a
   * json list
   *
   * @generated from field: string args = 6;
   */
  args = "";

  /**
   * The keyword argument to pass to the function (**kwargs) encoded as a
   * json dict
   *
   * @generated from field: string kwargs = 7;
   */
  kwargs = "";

  /**
   * The list of messages to run before the script and the result will be
   * available in `dys.get_attached_messages()`. If any of the attached messages
   * fails, the script execution will be aborted. The script can assume that the
   * attached messages have been executed successfully by virtue of the fact
   * that the script execution will never occur if any of the attached messages
   * had failed. The attached messages are executed in the order they are
   * provided.
   *
   * @generated from field: repeated google.protobuf.Any attached_messages = 8;
   */
  attachedMessages: Any[] = [];

  constructor(data?: PartialMessage<MsgExec>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgExec";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "executor_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "script_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "script_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "extra_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "function_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "args", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "kwargs", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "attached_messages", kind: "message", T: Any, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgExec {
    return new MsgExec().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgExec {
    return new MsgExec().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgExec {
    return new MsgExec().fromJsonString(jsonString, options);
  }

  static equals(a: MsgExec | PlainMessage<MsgExec> | undefined, b: MsgExec | PlainMessage<MsgExec> | undefined): boolean {
    return proto3.util.equals(MsgExec, a, b);
  }
}

/**
 * MsgExecResponse is the Msg/Exec request type.
 *
 * @generated from message dysonprotocol.script.v1.MsgExecResponse
 */
export class MsgExecResponse extends Message<MsgExecResponse> {
  /**
   * result is the final result of the proposal execution.
   *
   * @generated from field: string result = 1;
   */
  result = "";

  /**
   * Results of the attached messages.
   *
   * @generated from field: repeated google.protobuf.Any attached_message_results = 2;
   */
  attachedMessageResults: Any[] = [];

  constructor(data?: PartialMessage<MsgExecResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgExecResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "result", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "attached_message_results", kind: "message", T: Any, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgExecResponse {
    return new MsgExecResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgExecResponse {
    return new MsgExecResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgExecResponse {
    return new MsgExecResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgExecResponse | PlainMessage<MsgExecResponse> | undefined, b: MsgExecResponse | PlainMessage<MsgExecResponse> | undefined): boolean {
    return proto3.util.equals(MsgExecResponse, a, b);
  }
}

/**
 * MsgCreateNewScript is the Msg/CreateNewScript request type.
 *
 * @generated from message dysonprotocol.script.v1.MsgCreateNewScript
 */
export class MsgCreateNewScript extends Message<MsgCreateNewScript> {
  /**
   * creator is the account address creating the script.
   *
   * @generated from field: string creator_address = 1;
   */
  creatorAddress = "";

  /**
   * code is the script content.
   *
   * @generated from field: string code = 2;
   */
  code = "";

  constructor(data?: PartialMessage<MsgCreateNewScript>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgCreateNewScript";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "creator_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgCreateNewScript {
    return new MsgCreateNewScript().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgCreateNewScript {
    return new MsgCreateNewScript().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgCreateNewScript {
    return new MsgCreateNewScript().fromJsonString(jsonString, options);
  }

  static equals(a: MsgCreateNewScript | PlainMessage<MsgCreateNewScript> | undefined, b: MsgCreateNewScript | PlainMessage<MsgCreateNewScript> | undefined): boolean {
    return proto3.util.equals(MsgCreateNewScript, a, b);
  }
}

/**
 * MsgCreateNewScriptResponse is the Msg/CreateNewScript response type.
 *
 * @generated from message dysonprotocol.script.v1.MsgCreateNewScriptResponse
 */
export class MsgCreateNewScriptResponse extends Message<MsgCreateNewScriptResponse> {
  /**
   * script_address is the address of the newly created script.
   *
   * @generated from field: string script_address = 1;
   */
  scriptAddress = "";

  /**
   * version is the initial script version.
   *
   * @generated from field: uint64 version = 2;
   */
  version = protoInt64.zero;

  constructor(data?: PartialMessage<MsgCreateNewScriptResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgCreateNewScriptResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "script_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgCreateNewScriptResponse {
    return new MsgCreateNewScriptResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgCreateNewScriptResponse {
    return new MsgCreateNewScriptResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgCreateNewScriptResponse {
    return new MsgCreateNewScriptResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgCreateNewScriptResponse | PlainMessage<MsgCreateNewScriptResponse> | undefined, b: MsgCreateNewScriptResponse | PlainMessage<MsgCreateNewScriptResponse> | undefined): boolean {
    return proto3.util.equals(MsgCreateNewScriptResponse, a, b);
  }
}

/**
 * MsgUpdateParams is the Msg/UpdateParams request type.
 *
 * @generated from message dysonprotocol.script.v1.MsgUpdateParams
 */
export class MsgUpdateParams extends Message<MsgUpdateParams> {
  /**
   * authority is the address that controls the module (defaults to x/gov unless
   * overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority = "";

  /**
   * params defines the x/script parameters to update.
   *
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: dysonprotocol.script.v1.Params params = 2;
   */
  params?: Params;

  constructor(data?: PartialMessage<MsgUpdateParams>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgUpdateParams";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "params", kind: "message", T: Params },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined, b: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParams, a, b);
  }
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * @generated from message dysonprotocol.script.v1.MsgUpdateParamsResponse
 */
export class MsgUpdateParamsResponse extends Message<MsgUpdateParamsResponse> {
  constructor(data?: PartialMessage<MsgUpdateParamsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgUpdateParamsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined, b: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParamsResponse, a, b);
  }
}

/**
 * MsgArbitraryData is used for signing arbitrary data for verification purposes
 *
 * @generated from message dysonprotocol.script.v1.MsgArbitraryData
 */
export class MsgArbitraryData extends Message<MsgArbitraryData> {
  /**
   * signer is the account address signing the data
   *
   * @generated from field: string signer = 1;
   */
  signer = "";

  /**
   * data is the arbitrary data being signed
   *
   * @generated from field: string data = 2;
   */
  data = "";

  /**
   * app_domain is an optional application domain for the data
   *
   * @generated from field: string app_domain = 3;
   */
  appDomain = "";

  constructor(data?: PartialMessage<MsgArbitraryData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgArbitraryData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "signer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "app_domain", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgArbitraryData {
    return new MsgArbitraryData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgArbitraryData {
    return new MsgArbitraryData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgArbitraryData {
    return new MsgArbitraryData().fromJsonString(jsonString, options);
  }

  static equals(a: MsgArbitraryData | PlainMessage<MsgArbitraryData> | undefined, b: MsgArbitraryData | PlainMessage<MsgArbitraryData> | undefined): boolean {
    return proto3.util.equals(MsgArbitraryData, a, b);
  }
}

/**
 * MsgArbitraryDataResponse is the response for MsgArbitraryData
 *
 * @generated from message dysonprotocol.script.v1.MsgArbitraryDataResponse
 */
export class MsgArbitraryDataResponse extends Message<MsgArbitraryDataResponse> {
  constructor(data?: PartialMessage<MsgArbitraryDataResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgArbitraryDataResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgArbitraryDataResponse {
    return new MsgArbitraryDataResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgArbitraryDataResponse {
    return new MsgArbitraryDataResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgArbitraryDataResponse {
    return new MsgArbitraryDataResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgArbitraryDataResponse | PlainMessage<MsgArbitraryDataResponse> | undefined, b: MsgArbitraryDataResponse | PlainMessage<MsgArbitraryDataResponse> | undefined): boolean {
    return proto3.util.equals(MsgArbitraryDataResponse, a, b);
  }
}

