// Since: cosmos-sdk 0.46

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dysonprotocol/script/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_ScriptInfo_FullMethodName     = "/dysonprotocol.script.v1.Query/ScriptInfo"
	Query_EncodeJson_FullMethodName     = "/dysonprotocol.script.v1.Query/EncodeJson"
	Query_DecodeBytes_FullMethodName    = "/dysonprotocol.script.v1.Query/DecodeBytes"
	Query_VerifyTx_FullMethodName       = "/dysonprotocol.script.v1.Query/VerifyTx"
	Query_Params_FullMethodName         = "/dysonprotocol.script.v1.Query/Params"
	Query_Web_FullMethodName            = "/dysonprotocol.script.v1.Query/Web"
	Query_Run_FullMethodName            = "/dysonprotocol.script.v1.Query/Run"
	Query_GetBlock_FullMethodName       = "/dysonprotocol.script.v1.Query/GetBlock"
	Query_FunctionSchema_FullMethodName = "/dysonprotocol.script.v1.Query/FunctionSchema"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query is the dysonprotocol.script.v1 Query service.
type QueryClient interface {
	// ScriptInfo queries script information by address or nameservice name.
	// Supports both direct bech32 addresses and nameservice resolution.
	ScriptInfo(ctx context.Context, in *QueryScriptInfoRequest, opts ...grpc.CallOption) (*QueryScriptInfoResponse, error)
	// EncodeJson encodes a JSON string to protobuf bytes for message
	// construction. Useful for converting human-readable JSON to binary protobuf
	// format.
	EncodeJson(ctx context.Context, in *QueryEncodeJsonRequest, opts ...grpc.CallOption) (*QueryEncodeJsonResponse, error)
	// DecodeBytes decodes protobuf bytes to JSON string for message inspection.
	// Useful for converting binary protobuf messages to human-readable JSON
	// format.
	DecodeBytes(ctx context.Context, in *QueryDecodeBytesRequest, opts ...grpc.CallOption) (*QueryDecodeBytesResponse, error)
	// VerifyTx verifies the signatures of an arbitrary transaction for
	// MsgArbitraryData. Implements ADR-036 arbitrary signature verification with
	// empty chain ID and sequence.
	//
	// Example transaction JSON for verification:
	// ```json
	//
	//	{
	//	  "body": {
	//	    "messages": [
	//	      {
	//	        "@type": "/dysonprotocol.script.v1.MsgArbitraryData",
	//	        "signer": "dys1example_address",
	//	        "data": "arbitrary data to sign",
	//	        "app_domain": "my_app/v1.0"
	//	      }
	//	    ],
	//	    "memo": "",
	//	    "timeout_height": "0"
	//	  },
	//	  "auth_info": {
	//	    "signer_infos": [
	//	      {
	//	        "public_key": {
	//	          "@type": "/cosmos.crypto.secp256k1.PubKey",
	//	          "key": "base64_encoded_public_key"
	//	        },
	//	        "mode_info": {
	//	          "single": {
	//	            "mode": "SIGN_MODE_DIRECT"
	//	          }
	//	        },
	//	        "sequence": "0"
	//	      }
	//	    ],
	//	    "fee": {
	//	      "amount": [],
	//	      "gas_limit": "0"
	//	    }
	//	  },
	//	  "signatures": [
	//	    "base64_encoded_signature"
	//	  ]
	//	}
	//
	// ```
	//
	// CLI Example:
	//
	// # Create a signed MsgArbitraryData transaction for verification
	// ```bash
	// dysond tx script sign-arbitrary-data "your data to sign" --app-domain
	// "my_app/v1.0" --from alice --chain-id "" --account-number 0 --sequence 0
	// --offline --output-document signed_tx.json
	// ```
	//
	// # Verify the signed transaction
	// ```bash
	// dysond query script verify-tx --tx-json "$(cat signed_tx.json)" -o json
	// ```
	VerifyTx(ctx context.Context, in *QueryVerifyTxRequest, opts ...grpc.CallOption) (*QueryVerifyTxResponse, error)
	// Params queries the parameters of the script module.
	// Returns current configuration parameters for script execution and limits.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Web queries the WSGI web application function of a script.
	// This is used in the REST API and not intended for direct use.
	// Executes script's WSGI application in read-only mode for web requests.
	Web(ctx context.Context, in *WebRequest, opts ...grpc.CallOption) (*WebResponse, error)
	// Run executes a script function in read-only mode without modifying state.
	// Uses cached context to ensure execution has no persistent effects.
	Run(ctx context.Context, in *RunScript, opts ...grpc.CallOption) (*ResponseRunScript, error)
	// GetBlock returns the current block information.
	// Provides block height, time, chain ID, hashes, and proposer for scripts.
	GetBlock(ctx context.Context, in *QueryGetBlockRequest, opts ...grpc.CallOption) (*QueryGetBlockResponse, error)
	// FunctionSchema returns JSON schemas for all public functions in a script.
	// Extracts function signatures, parameter types, and return types for tooling
	// and documentation.
	FunctionSchema(ctx context.Context, in *QueryFunctionSchemaRequest, opts ...grpc.CallOption) (*QueryFunctionSchemaResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ScriptInfo(ctx context.Context, in *QueryScriptInfoRequest, opts ...grpc.CallOption) (*QueryScriptInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryScriptInfoResponse)
	err := c.cc.Invoke(ctx, Query_ScriptInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EncodeJson(ctx context.Context, in *QueryEncodeJsonRequest, opts ...grpc.CallOption) (*QueryEncodeJsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryEncodeJsonResponse)
	err := c.cc.Invoke(ctx, Query_EncodeJson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DecodeBytes(ctx context.Context, in *QueryDecodeBytesRequest, opts ...grpc.CallOption) (*QueryDecodeBytesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDecodeBytesResponse)
	err := c.cc.Invoke(ctx, Query_DecodeBytes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VerifyTx(ctx context.Context, in *QueryVerifyTxRequest, opts ...grpc.CallOption) (*QueryVerifyTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryVerifyTxResponse)
	err := c.cc.Invoke(ctx, Query_VerifyTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Web(ctx context.Context, in *WebRequest, opts ...grpc.CallOption) (*WebResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebResponse)
	err := c.cc.Invoke(ctx, Query_Web_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Run(ctx context.Context, in *RunScript, opts ...grpc.CallOption) (*ResponseRunScript, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseRunScript)
	err := c.cc.Invoke(ctx, Query_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetBlock(ctx context.Context, in *QueryGetBlockRequest, opts ...grpc.CallOption) (*QueryGetBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetBlockResponse)
	err := c.cc.Invoke(ctx, Query_GetBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FunctionSchema(ctx context.Context, in *QueryFunctionSchemaRequest, opts ...grpc.CallOption) (*QueryFunctionSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFunctionSchemaResponse)
	err := c.cc.Invoke(ctx, Query_FunctionSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query is the dysonprotocol.script.v1 Query service.
type QueryServer interface {
	// ScriptInfo queries script information by address or nameservice name.
	// Supports both direct bech32 addresses and nameservice resolution.
	ScriptInfo(context.Context, *QueryScriptInfoRequest) (*QueryScriptInfoResponse, error)
	// EncodeJson encodes a JSON string to protobuf bytes for message
	// construction. Useful for converting human-readable JSON to binary protobuf
	// format.
	EncodeJson(context.Context, *QueryEncodeJsonRequest) (*QueryEncodeJsonResponse, error)
	// DecodeBytes decodes protobuf bytes to JSON string for message inspection.
	// Useful for converting binary protobuf messages to human-readable JSON
	// format.
	DecodeBytes(context.Context, *QueryDecodeBytesRequest) (*QueryDecodeBytesResponse, error)
	// VerifyTx verifies the signatures of an arbitrary transaction for
	// MsgArbitraryData. Implements ADR-036 arbitrary signature verification with
	// empty chain ID and sequence.
	//
	// Example transaction JSON for verification:
	// ```json
	//
	//	{
	//	  "body": {
	//	    "messages": [
	//	      {
	//	        "@type": "/dysonprotocol.script.v1.MsgArbitraryData",
	//	        "signer": "dys1example_address",
	//	        "data": "arbitrary data to sign",
	//	        "app_domain": "my_app/v1.0"
	//	      }
	//	    ],
	//	    "memo": "",
	//	    "timeout_height": "0"
	//	  },
	//	  "auth_info": {
	//	    "signer_infos": [
	//	      {
	//	        "public_key": {
	//	          "@type": "/cosmos.crypto.secp256k1.PubKey",
	//	          "key": "base64_encoded_public_key"
	//	        },
	//	        "mode_info": {
	//	          "single": {
	//	            "mode": "SIGN_MODE_DIRECT"
	//	          }
	//	        },
	//	        "sequence": "0"
	//	      }
	//	    ],
	//	    "fee": {
	//	      "amount": [],
	//	      "gas_limit": "0"
	//	    }
	//	  },
	//	  "signatures": [
	//	    "base64_encoded_signature"
	//	  ]
	//	}
	//
	// ```
	//
	// CLI Example:
	//
	// # Create a signed MsgArbitraryData transaction for verification
	// ```bash
	// dysond tx script sign-arbitrary-data "your data to sign" --app-domain
	// "my_app/v1.0" --from alice --chain-id "" --account-number 0 --sequence 0
	// --offline --output-document signed_tx.json
	// ```
	//
	// # Verify the signed transaction
	// ```bash
	// dysond query script verify-tx --tx-json "$(cat signed_tx.json)" -o json
	// ```
	VerifyTx(context.Context, *QueryVerifyTxRequest) (*QueryVerifyTxResponse, error)
	// Params queries the parameters of the script module.
	// Returns current configuration parameters for script execution and limits.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Web queries the WSGI web application function of a script.
	// This is used in the REST API and not intended for direct use.
	// Executes script's WSGI application in read-only mode for web requests.
	Web(context.Context, *WebRequest) (*WebResponse, error)
	// Run executes a script function in read-only mode without modifying state.
	// Uses cached context to ensure execution has no persistent effects.
	Run(context.Context, *RunScript) (*ResponseRunScript, error)
	// GetBlock returns the current block information.
	// Provides block height, time, chain ID, hashes, and proposer for scripts.
	GetBlock(context.Context, *QueryGetBlockRequest) (*QueryGetBlockResponse, error)
	// FunctionSchema returns JSON schemas for all public functions in a script.
	// Extracts function signatures, parameter types, and return types for tooling
	// and documentation.
	FunctionSchema(context.Context, *QueryFunctionSchemaRequest) (*QueryFunctionSchemaResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) ScriptInfo(context.Context, *QueryScriptInfoRequest) (*QueryScriptInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScriptInfo not implemented")
}
func (UnimplementedQueryServer) EncodeJson(context.Context, *QueryEncodeJsonRequest) (*QueryEncodeJsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncodeJson not implemented")
}
func (UnimplementedQueryServer) DecodeBytes(context.Context, *QueryDecodeBytesRequest) (*QueryDecodeBytesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodeBytes not implemented")
}
func (UnimplementedQueryServer) VerifyTx(context.Context, *QueryVerifyTxRequest) (*QueryVerifyTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyTx not implemented")
}
func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Web(context.Context, *WebRequest) (*WebResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Web not implemented")
}
func (UnimplementedQueryServer) Run(context.Context, *RunScript) (*ResponseRunScript, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedQueryServer) GetBlock(context.Context, *QueryGetBlockRequest) (*QueryGetBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedQueryServer) FunctionSchema(context.Context, *QueryFunctionSchemaRequest) (*QueryFunctionSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FunctionSchema not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call pancis, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_ScriptInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryScriptInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ScriptInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ScriptInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ScriptInfo(ctx, req.(*QueryScriptInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EncodeJson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEncodeJsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EncodeJson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_EncodeJson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EncodeJson(ctx, req.(*QueryEncodeJsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DecodeBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDecodeBytesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DecodeBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DecodeBytes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DecodeBytes(ctx, req.(*QueryDecodeBytesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VerifyTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerifyTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerifyTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_VerifyTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerifyTx(ctx, req.(*QueryVerifyTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Web_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Web(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Web_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Web(ctx, req.(*WebRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunScript)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Run(ctx, req.(*RunScript))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetBlock(ctx, req.(*QueryGetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FunctionSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFunctionSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FunctionSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_FunctionSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FunctionSchema(ctx, req.(*QueryFunctionSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dysonprotocol.script.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScriptInfo",
			Handler:    _Query_ScriptInfo_Handler,
		},
		{
			MethodName: "EncodeJson",
			Handler:    _Query_EncodeJson_Handler,
		},
		{
			MethodName: "DecodeBytes",
			Handler:    _Query_DecodeBytes_Handler,
		},
		{
			MethodName: "VerifyTx",
			Handler:    _Query_VerifyTx_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Web",
			Handler:    _Query_Web_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _Query_Run_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _Query_GetBlock_Handler,
		},
		{
			MethodName: "FunctionSchema",
			Handler:    _Query_FunctionSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dysonprotocol/script/v1/query.proto",
}
