// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dysonprotocol/storage/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_StorageSet_FullMethodName    = "/dysonprotocol.storage.v1.Msg/StorageSet"
	Msg_StorageDelete_FullMethodName = "/dysonprotocol.storage.v1.Msg/StorageDelete"
	Msg_UpdateParams_FullMethodName  = "/dysonprotocol.storage.v1.Msg/UpdateParams"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the storage Msg service.
type MsgClient interface {
	// StorageSet sets a storage entry for the specified owner and index.
	//
	// Sets a storage entry for the specified owner and index with stake
	// validation, size limits, and automatic metadata tracking including data
	// hashing and timestamp recording.
	//
	// Behavior:
	//   - Stores JSON data under a composite key of owner/index, creating or
	//     updating the entry
	//   - Validates data size against module's MaxStorageSize parameter
	//   - Enforces stake requirements when StorageStakeMultiple > 0: requires owner
	//     to have sufficient delegated stake
	//   - Calculates data hash using SHA256 and stores metadata including block
	//     height and timestamp
	//   - Updates owner's storage metrics (total bytes) for stake validation and
	//     monitoring
	//
	// Validation:
	//   - Owner must be a valid bech32 address
	//   - Index must be non-empty and contain only printable ASCII characters
	//   - Data size must not exceed MaxStorageSize parameter
	//   - When stake validation is enabled, owner's delegated stake must meet
	//     minimum requirement
	//
	// Emits:
	// - EventStorageUpdated(address, index) upon successful storage operation
	//
	// Returns:
	// - Empty response body on success
	StorageSet(ctx context.Context, in *MsgStorageSet, opts ...grpc.CallOption) (*MsgStorageSetResponse, error)
	// StorageDelete removes specified storage entries owned by the requesting
	// account.
	//
	// Behavior:
	//   - Deletes multiple storage entries by index for the specified owner
	//   - Verifies ownership of each entry before deletion to prevent unauthorized
	//     removal
	//   - Updates owner's storage metrics by subtracting deleted bytes from total
	//   - Returns list of successfully deleted indexes for transparency
	//
	// Validation:
	// - Owner must be a valid bech32 address
	// - At least one index must be specified for deletion
	// - Each specified index must exist and be owned by the requesting account
	//
	// Emits:
	//   - EventStorageDelete(owner, deleted_indexes) with list of successfully
	//     deleted indexes
	//
	// Returns:
	// - List of indexes that were successfully deleted
	StorageDelete(ctx context.Context, in *MsgStorageDelete, opts ...grpc.CallOption) (*MsgStorageDeleteResponse, error)
	// UpdateParams updates the x/storage module parameters via governance
	// proposal.
	//
	// Behavior:
	//   - Validates that the signer has authority to update module parameters
	//     (typically governance module)
	//   - Validates that all provided parameters are valid according to parameter
	//     constraints
	//   - Updates the module's parameter state with the new values
	//
	// Validation:
	//   - Authority must match the module's configured authority address
	//   - All parameter values must pass individual validation (MaxStorageSize,
	//     StorageStakeMultiple)
	//
	// Emits:
	// - No events emitted for parameter updates
	//
	// Returns:
	// - Empty response body on success
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) StorageSet(ctx context.Context, in *MsgStorageSet, opts ...grpc.CallOption) (*MsgStorageSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgStorageSetResponse)
	err := c.cc.Invoke(ctx, Msg_StorageSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) StorageDelete(ctx context.Context, in *MsgStorageDelete, opts ...grpc.CallOption) (*MsgStorageDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgStorageDeleteResponse)
	err := c.cc.Invoke(ctx, Msg_StorageDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the storage Msg service.
type MsgServer interface {
	// StorageSet sets a storage entry for the specified owner and index.
	//
	// Sets a storage entry for the specified owner and index with stake
	// validation, size limits, and automatic metadata tracking including data
	// hashing and timestamp recording.
	//
	// Behavior:
	//   - Stores JSON data under a composite key of owner/index, creating or
	//     updating the entry
	//   - Validates data size against module's MaxStorageSize parameter
	//   - Enforces stake requirements when StorageStakeMultiple > 0: requires owner
	//     to have sufficient delegated stake
	//   - Calculates data hash using SHA256 and stores metadata including block
	//     height and timestamp
	//   - Updates owner's storage metrics (total bytes) for stake validation and
	//     monitoring
	//
	// Validation:
	//   - Owner must be a valid bech32 address
	//   - Index must be non-empty and contain only printable ASCII characters
	//   - Data size must not exceed MaxStorageSize parameter
	//   - When stake validation is enabled, owner's delegated stake must meet
	//     minimum requirement
	//
	// Emits:
	// - EventStorageUpdated(address, index) upon successful storage operation
	//
	// Returns:
	// - Empty response body on success
	StorageSet(context.Context, *MsgStorageSet) (*MsgStorageSetResponse, error)
	// StorageDelete removes specified storage entries owned by the requesting
	// account.
	//
	// Behavior:
	//   - Deletes multiple storage entries by index for the specified owner
	//   - Verifies ownership of each entry before deletion to prevent unauthorized
	//     removal
	//   - Updates owner's storage metrics by subtracting deleted bytes from total
	//   - Returns list of successfully deleted indexes for transparency
	//
	// Validation:
	// - Owner must be a valid bech32 address
	// - At least one index must be specified for deletion
	// - Each specified index must exist and be owned by the requesting account
	//
	// Emits:
	//   - EventStorageDelete(owner, deleted_indexes) with list of successfully
	//     deleted indexes
	//
	// Returns:
	// - List of indexes that were successfully deleted
	StorageDelete(context.Context, *MsgStorageDelete) (*MsgStorageDeleteResponse, error)
	// UpdateParams updates the x/storage module parameters via governance
	// proposal.
	//
	// Behavior:
	//   - Validates that the signer has authority to update module parameters
	//     (typically governance module)
	//   - Validates that all provided parameters are valid according to parameter
	//     constraints
	//   - Updates the module's parameter state with the new values
	//
	// Validation:
	//   - Authority must match the module's configured authority address
	//   - All parameter values must pass individual validation (MaxStorageSize,
	//     StorageStakeMultiple)
	//
	// Emits:
	// - No events emitted for parameter updates
	//
	// Returns:
	// - Empty response body on success
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) StorageSet(context.Context, *MsgStorageSet) (*MsgStorageSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorageSet not implemented")
}
func (UnimplementedMsgServer) StorageDelete(context.Context, *MsgStorageDelete) (*MsgStorageDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorageDelete not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_StorageSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStorageSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).StorageSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_StorageSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).StorageSet(ctx, req.(*MsgStorageSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_StorageDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStorageDelete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).StorageDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_StorageDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).StorageDelete(ctx, req.(*MsgStorageDelete))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dysonprotocol.storage.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StorageSet",
			Handler:    _Msg_StorageSet_Handler,
		},
		{
			MethodName: "StorageDelete",
			Handler:    _Msg_StorageDelete_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dysonprotocol/storage/v1/tx.proto",
}
