// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dysonprotocol/crontask/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_TaskByID_FullMethodName               = "/dysonprotocol.crontask.v1.Query/TaskByID"
	Query_TasksByAddress_FullMethodName         = "/dysonprotocol.crontask.v1.Query/TasksByAddress"
	Query_TasksByStatusTimestamp_FullMethodName = "/dysonprotocol.crontask.v1.Query/TasksByStatusTimestamp"
	Query_TasksByStatusGasPrice_FullMethodName  = "/dysonprotocol.crontask.v1.Query/TasksByStatusGasPrice"
	Query_TasksAll_FullMethodName               = "/dysonprotocol.crontask.v1.Query/TasksAll"
	Query_Params_FullMethodName                 = "/dysonprotocol.crontask.v1.Query/Params"
	Query_Metrics_FullMethodName                = "/dysonprotocol.crontask.v1.Query/Metrics"
	Query_SubscriptionByID_FullMethodName       = "/dysonprotocol.crontask.v1.Query/SubscriptionByID"
	Query_SubscriptionsByCreator_FullMethodName = "/dysonprotocol.crontask.v1.Query/SubscriptionsByCreator"
	Query_SubscriptionsAll_FullMethodName       = "/dysonprotocol.crontask.v1.Query/SubscriptionsAll"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC query service for the crontask module
type QueryClient interface {
	// TaskByID returns a task by its ID.
	//
	// Returns the complete task record for the specified task ID, including all
	// scheduling information, messages, and execution status. Uses direct key
	// lookup for optimal performance.
	TaskByID(ctx context.Context, in *QueryTaskByIDRequest, opts ...grpc.CallOption) (*QueryTaskByIDResponse, error)
	// TasksByAddress returns all tasks created by a specific address.
	//
	// Returns paginated list of tasks created by the specified address, ordered
	// by task ID. Uses indexed queries for efficient lookup. Supports standard
	// pagination with customizable page size and navigation.
	TasksByAddress(ctx context.Context, in *QueryTasksByAddressRequest, opts ...grpc.CallOption) (*QueryTasksByAddressResponse, error)
	// TasksByStatusTimestamp returns tasks filtered by status and ordered by
	// timestamp.
	//
	// Returns paginated list of tasks with the specified status, ordered by
	// scheduled timestamp (earliest first). Uses indexed queries for efficient
	// status filtering. Supports pagination with reverse ordering capability.
	TasksByStatusTimestamp(ctx context.Context, in *QueryTasksByStatusTimestampRequest, opts ...grpc.CallOption) (*QueryTasksByStatusTimestampResponse, error)
	// TasksByStatusGasPrice returns tasks filtered by status and ordered by gas
	// price.
	//
	// Returns paginated list of tasks with the specified status, ordered by gas
	// price (lowest first). Uses indexed queries for efficient status filtering
	// and gas price ordering. Supports pagination with reverse ordering
	// capability.
	TasksByStatusGasPrice(ctx context.Context, in *QueryTasksByStatusGasPriceRequest, opts ...grpc.CallOption) (*QueryTasksByStatusGasPriceResponse, error)
	// TasksAll returns all tasks ordered by ID.
	//
	// Returns paginated list of all tasks in the system, ordered by task ID
	// ascending. Uses direct store iteration for comprehensive task listing.
	// Supports standard pagination for large result sets.
	TasksAll(ctx context.Context, in *QueryTasksAllRequest, opts ...grpc.CallOption) (*QueryTasksAllResponse, error)
	// Params returns the module parameters.
	//
	// Returns the current crontask module configuration including scheduling
	// limits, gas constraints, subscription rules, and stake requirements.
	// Parameters control task creation, execution limits, and subscription
	// behavior.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Metrics returns last-block crontask metrics.
	//
	// Returns operational metrics from the most recent block including task
	// execution counts, gas usage statistics, subscription activity, and system
	// performance indicators. Metrics are updated at the end of each block.
	Metrics(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error)
	// SubscriptionByID returns a subscription by id.
	//
	// Returns the complete subscription record for the specified subscription ID,
	// including filter criteria, script configuration, execution parameters, and
	// current status. Uses direct key lookup for optimal performance.
	SubscriptionByID(ctx context.Context, in *QuerySubscriptionByIDRequest, opts ...grpc.CallOption) (*QuerySubscriptionByIDResponse, error)
	// SubscriptionsByCreator returns subscriptions for a creator.
	//
	// Returns paginated list of subscriptions created by the specified address,
	// ordered by subscription ID. Uses collection filtering with indexed queries
	// for efficient creator-based lookups. Supports standard pagination.
	SubscriptionsByCreator(ctx context.Context, in *QuerySubscriptionsByCreatorRequest, opts ...grpc.CallOption) (*QuerySubscriptionsByCreatorResponse, error)
	// SubscriptionsAll returns all subscriptions.
	//
	// Returns paginated list of all subscriptions in the system, ordered by
	// subscription ID ascending. Uses collection pagination for comprehensive
	// subscription listing. Supports standard pagination for large result sets.
	SubscriptionsAll(ctx context.Context, in *QuerySubscriptionsAllRequest, opts ...grpc.CallOption) (*QuerySubscriptionsAllResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) TaskByID(ctx context.Context, in *QueryTaskByIDRequest, opts ...grpc.CallOption) (*QueryTaskByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTaskByIDResponse)
	err := c.cc.Invoke(ctx, Query_TaskByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TasksByAddress(ctx context.Context, in *QueryTasksByAddressRequest, opts ...grpc.CallOption) (*QueryTasksByAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTasksByAddressResponse)
	err := c.cc.Invoke(ctx, Query_TasksByAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TasksByStatusTimestamp(ctx context.Context, in *QueryTasksByStatusTimestampRequest, opts ...grpc.CallOption) (*QueryTasksByStatusTimestampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTasksByStatusTimestampResponse)
	err := c.cc.Invoke(ctx, Query_TasksByStatusTimestamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TasksByStatusGasPrice(ctx context.Context, in *QueryTasksByStatusGasPriceRequest, opts ...grpc.CallOption) (*QueryTasksByStatusGasPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTasksByStatusGasPriceResponse)
	err := c.cc.Invoke(ctx, Query_TasksByStatusGasPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TasksAll(ctx context.Context, in *QueryTasksAllRequest, opts ...grpc.CallOption) (*QueryTasksAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTasksAllResponse)
	err := c.cc.Invoke(ctx, Query_TasksAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Metrics(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMetricsResponse)
	err := c.cc.Invoke(ctx, Query_Metrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SubscriptionByID(ctx context.Context, in *QuerySubscriptionByIDRequest, opts ...grpc.CallOption) (*QuerySubscriptionByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySubscriptionByIDResponse)
	err := c.cc.Invoke(ctx, Query_SubscriptionByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SubscriptionsByCreator(ctx context.Context, in *QuerySubscriptionsByCreatorRequest, opts ...grpc.CallOption) (*QuerySubscriptionsByCreatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySubscriptionsByCreatorResponse)
	err := c.cc.Invoke(ctx, Query_SubscriptionsByCreator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SubscriptionsAll(ctx context.Context, in *QuerySubscriptionsAllRequest, opts ...grpc.CallOption) (*QuerySubscriptionsAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySubscriptionsAllResponse)
	err := c.cc.Invoke(ctx, Query_SubscriptionsAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC query service for the crontask module
type QueryServer interface {
	// TaskByID returns a task by its ID.
	//
	// Returns the complete task record for the specified task ID, including all
	// scheduling information, messages, and execution status. Uses direct key
	// lookup for optimal performance.
	TaskByID(context.Context, *QueryTaskByIDRequest) (*QueryTaskByIDResponse, error)
	// TasksByAddress returns all tasks created by a specific address.
	//
	// Returns paginated list of tasks created by the specified address, ordered
	// by task ID. Uses indexed queries for efficient lookup. Supports standard
	// pagination with customizable page size and navigation.
	TasksByAddress(context.Context, *QueryTasksByAddressRequest) (*QueryTasksByAddressResponse, error)
	// TasksByStatusTimestamp returns tasks filtered by status and ordered by
	// timestamp.
	//
	// Returns paginated list of tasks with the specified status, ordered by
	// scheduled timestamp (earliest first). Uses indexed queries for efficient
	// status filtering. Supports pagination with reverse ordering capability.
	TasksByStatusTimestamp(context.Context, *QueryTasksByStatusTimestampRequest) (*QueryTasksByStatusTimestampResponse, error)
	// TasksByStatusGasPrice returns tasks filtered by status and ordered by gas
	// price.
	//
	// Returns paginated list of tasks with the specified status, ordered by gas
	// price (lowest first). Uses indexed queries for efficient status filtering
	// and gas price ordering. Supports pagination with reverse ordering
	// capability.
	TasksByStatusGasPrice(context.Context, *QueryTasksByStatusGasPriceRequest) (*QueryTasksByStatusGasPriceResponse, error)
	// TasksAll returns all tasks ordered by ID.
	//
	// Returns paginated list of all tasks in the system, ordered by task ID
	// ascending. Uses direct store iteration for comprehensive task listing.
	// Supports standard pagination for large result sets.
	TasksAll(context.Context, *QueryTasksAllRequest) (*QueryTasksAllResponse, error)
	// Params returns the module parameters.
	//
	// Returns the current crontask module configuration including scheduling
	// limits, gas constraints, subscription rules, and stake requirements.
	// Parameters control task creation, execution limits, and subscription
	// behavior.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Metrics returns last-block crontask metrics.
	//
	// Returns operational metrics from the most recent block including task
	// execution counts, gas usage statistics, subscription activity, and system
	// performance indicators. Metrics are updated at the end of each block.
	Metrics(context.Context, *QueryMetricsRequest) (*QueryMetricsResponse, error)
	// SubscriptionByID returns a subscription by id.
	//
	// Returns the complete subscription record for the specified subscription ID,
	// including filter criteria, script configuration, execution parameters, and
	// current status. Uses direct key lookup for optimal performance.
	SubscriptionByID(context.Context, *QuerySubscriptionByIDRequest) (*QuerySubscriptionByIDResponse, error)
	// SubscriptionsByCreator returns subscriptions for a creator.
	//
	// Returns paginated list of subscriptions created by the specified address,
	// ordered by subscription ID. Uses collection filtering with indexed queries
	// for efficient creator-based lookups. Supports standard pagination.
	SubscriptionsByCreator(context.Context, *QuerySubscriptionsByCreatorRequest) (*QuerySubscriptionsByCreatorResponse, error)
	// SubscriptionsAll returns all subscriptions.
	//
	// Returns paginated list of all subscriptions in the system, ordered by
	// subscription ID ascending. Uses collection pagination for comprehensive
	// subscription listing. Supports standard pagination for large result sets.
	SubscriptionsAll(context.Context, *QuerySubscriptionsAllRequest) (*QuerySubscriptionsAllResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) TaskByID(context.Context, *QueryTaskByIDRequest) (*QueryTaskByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskByID not implemented")
}
func (UnimplementedQueryServer) TasksByAddress(context.Context, *QueryTasksByAddressRequest) (*QueryTasksByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TasksByAddress not implemented")
}
func (UnimplementedQueryServer) TasksByStatusTimestamp(context.Context, *QueryTasksByStatusTimestampRequest) (*QueryTasksByStatusTimestampResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TasksByStatusTimestamp not implemented")
}
func (UnimplementedQueryServer) TasksByStatusGasPrice(context.Context, *QueryTasksByStatusGasPriceRequest) (*QueryTasksByStatusGasPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TasksByStatusGasPrice not implemented")
}
func (UnimplementedQueryServer) TasksAll(context.Context, *QueryTasksAllRequest) (*QueryTasksAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TasksAll not implemented")
}
func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Metrics(context.Context, *QueryMetricsRequest) (*QueryMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Metrics not implemented")
}
func (UnimplementedQueryServer) SubscriptionByID(context.Context, *QuerySubscriptionByIDRequest) (*QuerySubscriptionByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscriptionByID not implemented")
}
func (UnimplementedQueryServer) SubscriptionsByCreator(context.Context, *QuerySubscriptionsByCreatorRequest) (*QuerySubscriptionsByCreatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscriptionsByCreator not implemented")
}
func (UnimplementedQueryServer) SubscriptionsAll(context.Context, *QuerySubscriptionsAllRequest) (*QuerySubscriptionsAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscriptionsAll not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call pancis, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_TaskByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTaskByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TaskByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_TaskByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TaskByID(ctx, req.(*QueryTaskByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TasksByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTasksByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TasksByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_TasksByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TasksByAddress(ctx, req.(*QueryTasksByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TasksByStatusTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTasksByStatusTimestampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TasksByStatusTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_TasksByStatusTimestamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TasksByStatusTimestamp(ctx, req.(*QueryTasksByStatusTimestampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TasksByStatusGasPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTasksByStatusGasPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TasksByStatusGasPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_TasksByStatusGasPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TasksByStatusGasPrice(ctx, req.(*QueryTasksByStatusGasPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TasksAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTasksAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TasksAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_TasksAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TasksAll(ctx, req.(*QueryTasksAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Metrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Metrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Metrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Metrics(ctx, req.(*QueryMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SubscriptionByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySubscriptionByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SubscriptionByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SubscriptionByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SubscriptionByID(ctx, req.(*QuerySubscriptionByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SubscriptionsByCreator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySubscriptionsByCreatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SubscriptionsByCreator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SubscriptionsByCreator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SubscriptionsByCreator(ctx, req.(*QuerySubscriptionsByCreatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SubscriptionsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySubscriptionsAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SubscriptionsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SubscriptionsAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SubscriptionsAll(ctx, req.(*QuerySubscriptionsAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dysonprotocol.crontask.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TaskByID",
			Handler:    _Query_TaskByID_Handler,
		},
		{
			MethodName: "TasksByAddress",
			Handler:    _Query_TasksByAddress_Handler,
		},
		{
			MethodName: "TasksByStatusTimestamp",
			Handler:    _Query_TasksByStatusTimestamp_Handler,
		},
		{
			MethodName: "TasksByStatusGasPrice",
			Handler:    _Query_TasksByStatusGasPrice_Handler,
		},
		{
			MethodName: "TasksAll",
			Handler:    _Query_TasksAll_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Metrics",
			Handler:    _Query_Metrics_Handler,
		},
		{
			MethodName: "SubscriptionByID",
			Handler:    _Query_SubscriptionByID_Handler,
		},
		{
			MethodName: "SubscriptionsByCreator",
			Handler:    _Query_SubscriptionsByCreator_Handler,
		},
		{
			MethodName: "SubscriptionsAll",
			Handler:    _Query_SubscriptionsAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dysonprotocol/crontask/v1/query.proto",
}
