// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dysonprotocol/crontask/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_CreateTask_FullMethodName         = "/dysonprotocol.crontask.v1.Msg/CreateTask"
	Msg_DeleteTask_FullMethodName         = "/dysonprotocol.crontask.v1.Msg/DeleteTask"
	Msg_UpdateParams_FullMethodName       = "/dysonprotocol.crontask.v1.Msg/UpdateParams"
	Msg_CreateSubscription_FullMethodName = "/dysonprotocol.crontask.v1.Msg/CreateSubscription"
	Msg_DeleteSubscription_FullMethodName = "/dysonprotocol.crontask.v1.Msg/DeleteSubscription"
	Msg_RenewSubscription_FullMethodName  = "/dysonprotocol.crontask.v1.Msg/RenewSubscription"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the crontask Msg service
type MsgClient interface {
	// CreateTask creates a new scheduled task with specified execution time and
	// messages.
	//
	// Behavior:
	// - Creates a task scheduled for execution at a future timestamp.
	// - Parses flexible timestamp formats (Unix timestamps or duration offsets
	// like
	// "+1h30m").
	// - Validates scheduling constraints and gas limits against module
	// parameters.
	// - Calculates gas price from fee and limit, stores task with unpacked
	// messages.
	// - Tasks remain in SCHEDULED status until execution time.
	//
	// Validation:
	// - Creator address must be valid.
	// - Scheduled timestamp must be in the future and within MaxScheduledTime
	// limit.
	// - Expiry timestamp must be after scheduled time (defaults to scheduled +
	// ExpiryLimit if not provided).
	// - Gas limit must be positive and not exceed BlockGasLimit.
	// - Gas fee must be positive and denominated in "udys".
	// - At least one message must be provided in the task.
	//
	// Emits:
	// - EventTaskCreated(task_id, creator) on successful task creation.
	//
	// Returns:
	// - MsgCreateTaskResponse with allocated task ID.
	CreateTask(ctx context.Context, in *MsgCreateTask, opts ...grpc.CallOption) (*MsgCreateTaskResponse, error)
	// DeleteTask permanently removes a scheduled task.
	//
	// Behavior:
	// - Permanently removes a task from storage before execution.
	// - Only the creator of the task can delete it.
	// - No refunds are provided for task fees or gas.
	//
	// Validation:
	// - Task must exist with the provided ID.
	// - Creator must match the task's creator field.
	//
	// Emits:
	// - EventTaskDeleted(task_id, creator) on successful deletion.
	//
	// Returns:
	// - Empty MsgDeleteTaskResponse.
	DeleteTask(ctx context.Context, in *MsgDeleteTask, opts ...grpc.CallOption) (*MsgDeleteTaskResponse, error)
	// UpdateParams updates the parameters of the x/crontask module via
	// governance proposal.
	//
	// Behavior:
	// - Updates all module parameters in a single governance operation.
	// - Authority is typically the x/gov module account.
	// - Parameters control task scheduling limits, gas constraints, and
	// subscription rules.
	//
	// Validation:
	// - Authority must be valid (typically x/gov module account).
	// - All parameter values must pass individual validation (Validate method).
	//
	// Emits:
	// - No events are emitted for parameter updates.
	//
	// Returns:
	// - Empty MsgUpdateParamsResponse.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// CreateSubscription creates a new event-triggered subscription with upfront
	// fee payment.
	//
	// Behavior:
	// - Creates a subscription that triggers script execution when events match
	// the filter.
	// - Enforces minimum stake requirements across all creator's subscriptions.
	// - Deducts anti-spam fee to fee_collector module account.
	// - Allocates unique subscription ID and sets expiry to current time +
	// max_subscription_duration.
	// - Minifies JSON args/kwargs for storage efficiency.
	// - Initializes subscription with "enabled" status and zero trigger count.
	//
	// Validation:
	// - Creator address must be valid.
	// - Script address must be valid and non-empty.
	// - Function name must be non-empty.
	// - Task gas limit must be positive.
	// - Task gas fee must be positive.
	// - Filter, script_address, function, args, kwargs must not exceed length
	// limits.
	// - Creator must have sufficient bonded stake if MinStakePerSubscription is
	// configured.
	// - Args/kwargs must be valid JSON (array for args, object for kwargs).
	//
	// Emits:
	// - EventSubscriptionCreated(subscription_id, creator) on successful
	// creation.
	//
	// Returns:
	// - MsgCreateSubscriptionResponse with allocated subscription ID.
	CreateSubscription(ctx context.Context, in *MsgCreateSubscription, opts ...grpc.CallOption) (*MsgCreateSubscriptionResponse, error)
	// DeleteSubscription permanently removes an existing subscription.
	//
	// Behavior:
	// - Permanently removes a subscription from storage.
	// - Only the creator of the subscription can delete it.
	// - No refunds are provided for remaining subscription time or fees.
	//
	// Validation:
	// - Creator address must be valid.
	// - Subscription must exist.
	// - Creator must match the subscription's creator field.
	//
	// Emits:
	// - EventSubscriptionDeleted(subscription_id, creator) on successful
	// deletion.
	//
	// Returns:
	// - Empty MsgDeleteSubscriptionResponse.
	DeleteSubscription(ctx context.Context, in *MsgDeleteSubscription, opts ...grpc.CallOption) (*MsgDeleteSubscriptionResponse, error)
	// RenewSubscription extends subscription expiry and recharges the fee.
	//
	// Behavior:
	// - Extends subscription expiry to current time + max_subscription_duration.
	// - Recharges the task gas fee from creator to fee_collector.
	// - Re-enables "disabled" subscriptions (time-expired or insufficient funds).
	// - Does NOT re-enable "error" subscriptions (unrecoverable issues).
	// - Enforces minimum stake requirements before renewal.
	//
	// Validation:
	// - Creator address must be valid.
	// - Subscription must exist.
	// - Creator must match the subscription's creator field.
	// - Creator must have sufficient bonded stake if MinStakePerSubscription is
	// configured.
	//
	// Emits:
	// - No events are emitted for renewal (subscription remains active).
	//
	// Returns:
	// - Empty MsgRenewSubscriptionResponse.
	RenewSubscription(ctx context.Context, in *MsgRenewSubscription, opts ...grpc.CallOption) (*MsgRenewSubscriptionResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateTask(ctx context.Context, in *MsgCreateTask, opts ...grpc.CallOption) (*MsgCreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCreateTaskResponse)
	err := c.cc.Invoke(ctx, Msg_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteTask(ctx context.Context, in *MsgDeleteTask, opts ...grpc.CallOption) (*MsgDeleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgDeleteTaskResponse)
	err := c.cc.Invoke(ctx, Msg_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateSubscription(ctx context.Context, in *MsgCreateSubscription, opts ...grpc.CallOption) (*MsgCreateSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCreateSubscriptionResponse)
	err := c.cc.Invoke(ctx, Msg_CreateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteSubscription(ctx context.Context, in *MsgDeleteSubscription, opts ...grpc.CallOption) (*MsgDeleteSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgDeleteSubscriptionResponse)
	err := c.cc.Invoke(ctx, Msg_DeleteSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RenewSubscription(ctx context.Context, in *MsgRenewSubscription, opts ...grpc.CallOption) (*MsgRenewSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRenewSubscriptionResponse)
	err := c.cc.Invoke(ctx, Msg_RenewSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the crontask Msg service
type MsgServer interface {
	// CreateTask creates a new scheduled task with specified execution time and
	// messages.
	//
	// Behavior:
	// - Creates a task scheduled for execution at a future timestamp.
	// - Parses flexible timestamp formats (Unix timestamps or duration offsets
	// like
	// "+1h30m").
	// - Validates scheduling constraints and gas limits against module
	// parameters.
	// - Calculates gas price from fee and limit, stores task with unpacked
	// messages.
	// - Tasks remain in SCHEDULED status until execution time.
	//
	// Validation:
	// - Creator address must be valid.
	// - Scheduled timestamp must be in the future and within MaxScheduledTime
	// limit.
	// - Expiry timestamp must be after scheduled time (defaults to scheduled +
	// ExpiryLimit if not provided).
	// - Gas limit must be positive and not exceed BlockGasLimit.
	// - Gas fee must be positive and denominated in "udys".
	// - At least one message must be provided in the task.
	//
	// Emits:
	// - EventTaskCreated(task_id, creator) on successful task creation.
	//
	// Returns:
	// - MsgCreateTaskResponse with allocated task ID.
	CreateTask(context.Context, *MsgCreateTask) (*MsgCreateTaskResponse, error)
	// DeleteTask permanently removes a scheduled task.
	//
	// Behavior:
	// - Permanently removes a task from storage before execution.
	// - Only the creator of the task can delete it.
	// - No refunds are provided for task fees or gas.
	//
	// Validation:
	// - Task must exist with the provided ID.
	// - Creator must match the task's creator field.
	//
	// Emits:
	// - EventTaskDeleted(task_id, creator) on successful deletion.
	//
	// Returns:
	// - Empty MsgDeleteTaskResponse.
	DeleteTask(context.Context, *MsgDeleteTask) (*MsgDeleteTaskResponse, error)
	// UpdateParams updates the parameters of the x/crontask module via
	// governance proposal.
	//
	// Behavior:
	// - Updates all module parameters in a single governance operation.
	// - Authority is typically the x/gov module account.
	// - Parameters control task scheduling limits, gas constraints, and
	// subscription rules.
	//
	// Validation:
	// - Authority must be valid (typically x/gov module account).
	// - All parameter values must pass individual validation (Validate method).
	//
	// Emits:
	// - No events are emitted for parameter updates.
	//
	// Returns:
	// - Empty MsgUpdateParamsResponse.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// CreateSubscription creates a new event-triggered subscription with upfront
	// fee payment.
	//
	// Behavior:
	// - Creates a subscription that triggers script execution when events match
	// the filter.
	// - Enforces minimum stake requirements across all creator's subscriptions.
	// - Deducts anti-spam fee to fee_collector module account.
	// - Allocates unique subscription ID and sets expiry to current time +
	// max_subscription_duration.
	// - Minifies JSON args/kwargs for storage efficiency.
	// - Initializes subscription with "enabled" status and zero trigger count.
	//
	// Validation:
	// - Creator address must be valid.
	// - Script address must be valid and non-empty.
	// - Function name must be non-empty.
	// - Task gas limit must be positive.
	// - Task gas fee must be positive.
	// - Filter, script_address, function, args, kwargs must not exceed length
	// limits.
	// - Creator must have sufficient bonded stake if MinStakePerSubscription is
	// configured.
	// - Args/kwargs must be valid JSON (array for args, object for kwargs).
	//
	// Emits:
	// - EventSubscriptionCreated(subscription_id, creator) on successful
	// creation.
	//
	// Returns:
	// - MsgCreateSubscriptionResponse with allocated subscription ID.
	CreateSubscription(context.Context, *MsgCreateSubscription) (*MsgCreateSubscriptionResponse, error)
	// DeleteSubscription permanently removes an existing subscription.
	//
	// Behavior:
	// - Permanently removes a subscription from storage.
	// - Only the creator of the subscription can delete it.
	// - No refunds are provided for remaining subscription time or fees.
	//
	// Validation:
	// - Creator address must be valid.
	// - Subscription must exist.
	// - Creator must match the subscription's creator field.
	//
	// Emits:
	// - EventSubscriptionDeleted(subscription_id, creator) on successful
	// deletion.
	//
	// Returns:
	// - Empty MsgDeleteSubscriptionResponse.
	DeleteSubscription(context.Context, *MsgDeleteSubscription) (*MsgDeleteSubscriptionResponse, error)
	// RenewSubscription extends subscription expiry and recharges the fee.
	//
	// Behavior:
	// - Extends subscription expiry to current time + max_subscription_duration.
	// - Recharges the task gas fee from creator to fee_collector.
	// - Re-enables "disabled" subscriptions (time-expired or insufficient funds).
	// - Does NOT re-enable "error" subscriptions (unrecoverable issues).
	// - Enforces minimum stake requirements before renewal.
	//
	// Validation:
	// - Creator address must be valid.
	// - Subscription must exist.
	// - Creator must match the subscription's creator field.
	// - Creator must have sufficient bonded stake if MinStakePerSubscription is
	// configured.
	//
	// Emits:
	// - No events are emitted for renewal (subscription remains active).
	//
	// Returns:
	// - Empty MsgRenewSubscriptionResponse.
	RenewSubscription(context.Context, *MsgRenewSubscription) (*MsgRenewSubscriptionResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) CreateTask(context.Context, *MsgCreateTask) (*MsgCreateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedMsgServer) DeleteTask(context.Context, *MsgDeleteTask) (*MsgDeleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) CreateSubscription(context.Context, *MsgCreateSubscription) (*MsgCreateSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedMsgServer) DeleteSubscription(context.Context, *MsgDeleteSubscription) (*MsgDeleteSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (UnimplementedMsgServer) RenewSubscription(context.Context, *MsgRenewSubscription) (*MsgRenewSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewSubscription not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateTask(ctx, req.(*MsgCreateTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteTask(ctx, req.(*MsgDeleteTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateSubscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateSubscription(ctx, req.(*MsgCreateSubscription))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteSubscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeleteSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteSubscription(ctx, req.(*MsgDeleteSubscription))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RenewSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRenewSubscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RenewSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RenewSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RenewSubscription(ctx, req.(*MsgRenewSubscription))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dysonprotocol.crontask.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _Msg_CreateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _Msg_DeleteTask_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _Msg_CreateSubscription_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _Msg_DeleteSubscription_Handler,
		},
		{
			MethodName: "RenewSubscription",
			Handler:    _Msg_RenewSubscription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dysonprotocol/crontask/v1/tx.proto",
}
