// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file dysonprotocol/whaleswap/v1/events.proto (package dysonprotocol.whaleswap.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Coin } from "../../../cosmos/base/v1beta1/coin_pb.js";

/**
 * @generated from message dysonprotocol.whaleswap.v1.EventPoolCreated
 */
export class EventPoolCreated extends Message<EventPoolCreated> {
  /**
   * @generated from field: uint64 pool_id = 1;
   */
  poolId = protoInt64.zero;

  constructor(data?: PartialMessage<EventPoolCreated>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.EventPoolCreated";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pool_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventPoolCreated {
    return new EventPoolCreated().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventPoolCreated {
    return new EventPoolCreated().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventPoolCreated {
    return new EventPoolCreated().fromJsonString(jsonString, options);
  }

  static equals(a: EventPoolCreated | PlainMessage<EventPoolCreated> | undefined, b: EventPoolCreated | PlainMessage<EventPoolCreated> | undefined): boolean {
    return proto3.util.equals(EventPoolCreated, a, b);
  }
}

/**
 * @generated from message dysonprotocol.whaleswap.v1.EventPoolUpdate
 */
export class EventPoolUpdate extends Message<EventPoolUpdate> {
  /**
   * @generated from field: uint64 pool_id = 1;
   */
  poolId = protoInt64.zero;

  constructor(data?: PartialMessage<EventPoolUpdate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.EventPoolUpdate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pool_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventPoolUpdate {
    return new EventPoolUpdate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventPoolUpdate {
    return new EventPoolUpdate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventPoolUpdate {
    return new EventPoolUpdate().fromJsonString(jsonString, options);
  }

  static equals(a: EventPoolUpdate | PlainMessage<EventPoolUpdate> | undefined, b: EventPoolUpdate | PlainMessage<EventPoolUpdate> | undefined): boolean {
    return proto3.util.equals(EventPoolUpdate, a, b);
  }
}

/**
 * @generated from message dysonprotocol.whaleswap.v1.EventPoolSwap
 */
export class EventPoolSwap extends Message<EventPoolSwap> {
  /**
   * @generated from field: uint64 pool_id = 1;
   */
  poolId = protoInt64.zero;

  /**
   * @generated from field: uint64 trade_id = 2;
   */
  tradeId = protoInt64.zero;

  /**
   * @generated from field: uint32 operation_index = 3;
   */
  operationIndex = 0;

  constructor(data?: PartialMessage<EventPoolSwap>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.EventPoolSwap";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pool_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "trade_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "operation_index", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventPoolSwap {
    return new EventPoolSwap().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventPoolSwap {
    return new EventPoolSwap().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventPoolSwap {
    return new EventPoolSwap().fromJsonString(jsonString, options);
  }

  static equals(a: EventPoolSwap | PlainMessage<EventPoolSwap> | undefined, b: EventPoolSwap | PlainMessage<EventPoolSwap> | undefined): boolean {
    return proto3.util.equals(EventPoolSwap, a, b);
  }
}

/**
 * @generated from message dysonprotocol.whaleswap.v1.EventPoolLiquidityAdded
 */
export class EventPoolLiquidityAdded extends Message<EventPoolLiquidityAdded> {
  /**
   * @generated from field: uint64 pool_id = 1;
   */
  poolId = protoInt64.zero;

  /**
   * sdk.Int string
   *
   * @generated from field: string shares = 2;
   */
  shares = "";

  constructor(data?: PartialMessage<EventPoolLiquidityAdded>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.EventPoolLiquidityAdded";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pool_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "shares", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventPoolLiquidityAdded {
    return new EventPoolLiquidityAdded().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventPoolLiquidityAdded {
    return new EventPoolLiquidityAdded().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventPoolLiquidityAdded {
    return new EventPoolLiquidityAdded().fromJsonString(jsonString, options);
  }

  static equals(a: EventPoolLiquidityAdded | PlainMessage<EventPoolLiquidityAdded> | undefined, b: EventPoolLiquidityAdded | PlainMessage<EventPoolLiquidityAdded> | undefined): boolean {
    return proto3.util.equals(EventPoolLiquidityAdded, a, b);
  }
}

/**
 * @generated from message dysonprotocol.whaleswap.v1.EventPoolLiquidityRemoved
 */
export class EventPoolLiquidityRemoved extends Message<EventPoolLiquidityRemoved> {
  /**
   * @generated from field: uint64 pool_id = 1;
   */
  poolId = protoInt64.zero;

  /**
   * sdk.Int string
   *
   * @generated from field: string shares = 2;
   */
  shares = "";

  constructor(data?: PartialMessage<EventPoolLiquidityRemoved>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.EventPoolLiquidityRemoved";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pool_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "shares", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventPoolLiquidityRemoved {
    return new EventPoolLiquidityRemoved().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventPoolLiquidityRemoved {
    return new EventPoolLiquidityRemoved().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventPoolLiquidityRemoved {
    return new EventPoolLiquidityRemoved().fromJsonString(jsonString, options);
  }

  static equals(a: EventPoolLiquidityRemoved | PlainMessage<EventPoolLiquidityRemoved> | undefined, b: EventPoolLiquidityRemoved | PlainMessage<EventPoolLiquidityRemoved> | undefined): boolean {
    return proto3.util.equals(EventPoolLiquidityRemoved, a, b);
  }
}

/**
 * @generated from message dysonprotocol.whaleswap.v1.EventOfferCreated
 */
export class EventOfferCreated extends Message<EventOfferCreated> {
  /**
   * @generated from field: uint64 offer_id = 1;
   */
  offerId = protoInt64.zero;

  constructor(data?: PartialMessage<EventOfferCreated>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.EventOfferCreated";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "offer_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventOfferCreated {
    return new EventOfferCreated().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventOfferCreated {
    return new EventOfferCreated().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventOfferCreated {
    return new EventOfferCreated().fromJsonString(jsonString, options);
  }

  static equals(a: EventOfferCreated | PlainMessage<EventOfferCreated> | undefined, b: EventOfferCreated | PlainMessage<EventOfferCreated> | undefined): boolean {
    return proto3.util.equals(EventOfferCreated, a, b);
  }
}

/**
 * @generated from message dysonprotocol.whaleswap.v1.EventOfferTaken
 */
export class EventOfferTaken extends Message<EventOfferTaken> {
  /**
   * @generated from field: uint64 offer_id = 1;
   */
  offerId = protoInt64.zero;

  /**
   * @generated from field: uint64 trade_id = 2;
   */
  tradeId = protoInt64.zero;

  /**
   * @generated from field: string units_taken = 3;
   */
  unitsTaken = "";

  constructor(data?: PartialMessage<EventOfferTaken>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.EventOfferTaken";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "offer_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "trade_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "units_taken", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventOfferTaken {
    return new EventOfferTaken().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventOfferTaken {
    return new EventOfferTaken().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventOfferTaken {
    return new EventOfferTaken().fromJsonString(jsonString, options);
  }

  static equals(a: EventOfferTaken | PlainMessage<EventOfferTaken> | undefined, b: EventOfferTaken | PlainMessage<EventOfferTaken> | undefined): boolean {
    return proto3.util.equals(EventOfferTaken, a, b);
  }
}

/**
 * @generated from message dysonprotocol.whaleswap.v1.EventOfferCancelled
 */
export class EventOfferCancelled extends Message<EventOfferCancelled> {
  /**
   * @generated from field: uint64 offer_id = 1;
   */
  offerId = protoInt64.zero;

  constructor(data?: PartialMessage<EventOfferCancelled>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.EventOfferCancelled";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "offer_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventOfferCancelled {
    return new EventOfferCancelled().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventOfferCancelled {
    return new EventOfferCancelled().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventOfferCancelled {
    return new EventOfferCancelled().fromJsonString(jsonString, options);
  }

  static equals(a: EventOfferCancelled | PlainMessage<EventOfferCancelled> | undefined, b: EventOfferCancelled | PlainMessage<EventOfferCancelled> | undefined): boolean {
    return proto3.util.equals(EventOfferCancelled, a, b);
  }
}

/**
 * @generated from message dysonprotocol.whaleswap.v1.EventPfandLocked
 */
export class EventPfandLocked extends Message<EventPfandLocked> {
  /**
   * @generated from field: cosmos.base.v1beta1.Coin amount = 1;
   */
  amount?: Coin;

  /**
   * @generated from field: uint64 offer_id = 2;
   */
  offerId = protoInt64.zero;

  constructor(data?: PartialMessage<EventPfandLocked>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.EventPfandLocked";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "amount", kind: "message", T: Coin },
    { no: 2, name: "offer_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventPfandLocked {
    return new EventPfandLocked().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventPfandLocked {
    return new EventPfandLocked().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventPfandLocked {
    return new EventPfandLocked().fromJsonString(jsonString, options);
  }

  static equals(a: EventPfandLocked | PlainMessage<EventPfandLocked> | undefined, b: EventPfandLocked | PlainMessage<EventPfandLocked> | undefined): boolean {
    return proto3.util.equals(EventPfandLocked, a, b);
  }
}

/**
 * @generated from message dysonprotocol.whaleswap.v1.EventPfandReleased
 */
export class EventPfandReleased extends Message<EventPfandReleased> {
  /**
   * @generated from field: cosmos.base.v1beta1.Coin amount = 1;
   */
  amount?: Coin;

  /**
   * @generated from field: uint64 offer_id = 2;
   */
  offerId = protoInt64.zero;

  /**
   * @generated from field: uint64 trade_id = 3;
   */
  tradeId = protoInt64.zero;

  constructor(data?: PartialMessage<EventPfandReleased>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.EventPfandReleased";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "amount", kind: "message", T: Coin },
    { no: 2, name: "offer_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "trade_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventPfandReleased {
    return new EventPfandReleased().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventPfandReleased {
    return new EventPfandReleased().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventPfandReleased {
    return new EventPfandReleased().fromJsonString(jsonString, options);
  }

  static equals(a: EventPfandReleased | PlainMessage<EventPfandReleased> | undefined, b: EventPfandReleased | PlainMessage<EventPfandReleased> | undefined): boolean {
    return proto3.util.equals(EventPfandReleased, a, b);
  }
}

/**
 * @generated from message dysonprotocol.whaleswap.v1.EventAuctionCreated
 */
export class EventAuctionCreated extends Message<EventAuctionCreated> {
  /**
   * @generated from field: uint64 auction_id = 1;
   */
  auctionId = protoInt64.zero;

  constructor(data?: PartialMessage<EventAuctionCreated>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.EventAuctionCreated";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "auction_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventAuctionCreated {
    return new EventAuctionCreated().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventAuctionCreated {
    return new EventAuctionCreated().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventAuctionCreated {
    return new EventAuctionCreated().fromJsonString(jsonString, options);
  }

  static equals(a: EventAuctionCreated | PlainMessage<EventAuctionCreated> | undefined, b: EventAuctionCreated | PlainMessage<EventAuctionCreated> | undefined): boolean {
    return proto3.util.equals(EventAuctionCreated, a, b);
  }
}

/**
 * @generated from message dysonprotocol.whaleswap.v1.EventAuctionRedeemed
 */
export class EventAuctionRedeemed extends Message<EventAuctionRedeemed> {
  /**
   * @generated from field: uint64 auction_id = 1;
   */
  auctionId = protoInt64.zero;

  /**
   * @generated from field: uint64 trade_id = 2;
   */
  tradeId = protoInt64.zero;

  constructor(data?: PartialMessage<EventAuctionRedeemed>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.EventAuctionRedeemed";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "auction_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "trade_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventAuctionRedeemed {
    return new EventAuctionRedeemed().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventAuctionRedeemed {
    return new EventAuctionRedeemed().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventAuctionRedeemed {
    return new EventAuctionRedeemed().fromJsonString(jsonString, options);
  }

  static equals(a: EventAuctionRedeemed | PlainMessage<EventAuctionRedeemed> | undefined, b: EventAuctionRedeemed | PlainMessage<EventAuctionRedeemed> | undefined): boolean {
    return proto3.util.equals(EventAuctionRedeemed, a, b);
  }
}

/**
 * Emitted once per Trade after all operations complete (summary event).
 * Operation details are in domain events (EventPoolSwap, EventOfferTaken, etc).
 *
 * @generated from message dysonprotocol.whaleswap.v1.EventTradeRecorded
 */
export class EventTradeRecorded extends Message<EventTradeRecorded> {
  /**
   * @generated from field: uint64 trade_id = 1;
   */
  tradeId = protoInt64.zero;

  /**
   * @generated from field: string trader = 2;
   */
  trader = "";

  /**
   * @generated from field: uint32 num_operations = 3;
   */
  numOperations = 0;

  /**
   * @generated from field: string note = 4;
   */
  note = "";

  constructor(data?: PartialMessage<EventTradeRecorded>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.EventTradeRecorded";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "trade_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "trader", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "num_operations", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "note", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventTradeRecorded {
    return new EventTradeRecorded().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventTradeRecorded {
    return new EventTradeRecorded().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventTradeRecorded {
    return new EventTradeRecorded().fromJsonString(jsonString, options);
  }

  static equals(a: EventTradeRecorded | PlainMessage<EventTradeRecorded> | undefined, b: EventTradeRecorded | PlainMessage<EventTradeRecorded> | undefined): boolean {
    return proto3.util.equals(EventTradeRecorded, a, b);
  }
}

