// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file dysonprotocol/whaleswap/v1/tx.proto (package dysonprotocol.whaleswap.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgAddCollateral, MsgAddCollateralResponse, MsgAddLiquidity, MsgAddLiquidityResponse, MsgCancelOffer, MsgCancelOfferResponse, MsgClosePosition, MsgClosePositionResponse, MsgCreatePool, MsgCreatePoolResponse, MsgFinalizeLiquidation, MsgFinalizeLiquidationResponse, MsgInitializeLiquidation, MsgInitializeLiquidationResponse, MsgMakeOffer, MsgMakeOfferResponse, MsgMakeTrade, MsgMakeTradeResponse, MsgOpenAuction, MsgOpenAuctionResponse, MsgOpenPosition, MsgOpenPositionResponse, MsgPoolSwap, MsgPoolSwapResponse, MsgRedeemAuction, MsgRedeemAuctionResponse, MsgRemoveLiquidity, MsgRemoveLiquidityResponse, MsgTakeOffer, MsgTakeOfferResponse, MsgUpdateParams, MsgUpdateParamsResponse, MsgUpdatePoolConfig, MsgUpdatePoolConfigResponse } from "./tx_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 *
 * Conventions used across whaleswap messages:
 *
 * - Denom pair canonicalization: Internally, any denom pair is ordered
 *   lexicographically as pairKey = min(denom1, denom2) | max(denom1, denom2).
 *   Callers may provide denoms in any order; the keeper normalizes.
 *
 * - Price orientation: Unless otherwise stated, price is expressed as
 *   want-per-have in the high-per-low orientation relative to the canonical
 *   pair: P = (amount of high denom) / (amount of low denom). This choice makes
 *   lexicographic ordering of fixed-precision decimal strings align with
 *   numeric ordering for indexes and range scans.
 *
 * - Decimal fields: cosmos.Dec are encoded as strings; callers MUST provide
 *   syntactically valid decimal strings, and the keeper validates ranges.
 *
 * - Coins arrays in price bands: When used to express a ratio, the field must
 *   be either empty (unset) or contain exactly two coins whose denoms match the
 *   pool's reserve denoms, representing coin_b / coin_a.
 *
 * - Settlement modes: Orderbook offers specify how the 'have' is funded:
 *   ESCROW (escrow base have at creation) or LIQUID (no escrow; lock PFAND and
 *   settle from maker balance at take).
 *
 * Msg defines the whaleswap Msg service.
 *
 * @generated from service dysonprotocol.whaleswap.v1.Msg
 */
export const Msg = {
  typeName: "dysonprotocol.whaleswap.v1.Msg",
  methods: {
    /**
     * AMM
     *
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.CreatePool
     */
    createPool: {
      name: "CreatePool",
      I: MsgCreatePool,
      O: MsgCreatePoolResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.UpdatePoolConfig
     */
    updatePoolConfig: {
      name: "UpdatePoolConfig",
      I: MsgUpdatePoolConfig,
      O: MsgUpdatePoolConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.AddLiquidity
     */
    addLiquidity: {
      name: "AddLiquidity",
      I: MsgAddLiquidity,
      O: MsgAddLiquidityResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.RemoveLiquidity
     */
    removeLiquidity: {
      name: "RemoveLiquidity",
      I: MsgRemoveLiquidity,
      O: MsgRemoveLiquidityResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.PoolSwap
     */
    poolSwap: {
      name: "PoolSwap",
      I: MsgPoolSwap,
      O: MsgPoolSwapResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Mixed operations: combine orderbook takes and pool swaps in one tx
     *
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.MakeTrade
     */
    makeTrade: {
      name: "MakeTrade",
      I: MsgMakeTrade,
      O: MsgMakeTradeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Orderbook
     *
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.MakeOffer
     */
    makeOffer: {
      name: "MakeOffer",
      I: MsgMakeOffer,
      O: MsgMakeOfferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.TakeOffer
     */
    takeOffer: {
      name: "TakeOffer",
      I: MsgTakeOffer,
      O: MsgTakeOfferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.CancelOffer
     */
    cancelOffer: {
      name: "CancelOffer",
      I: MsgCancelOffer,
      O: MsgCancelOfferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Auctions
     *
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.OpenAuction
     */
    openAuction: {
      name: "OpenAuction",
      I: MsgOpenAuction,
      O: MsgOpenAuctionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.RedeemAuction
     */
    redeemAuction: {
      name: "RedeemAuction",
      I: MsgRedeemAuction,
      O: MsgRedeemAuctionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Leverage
     *
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.OpenPosition
     */
    openPosition: {
      name: "OpenPosition",
      I: MsgOpenPosition,
      O: MsgOpenPositionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.ClosePosition
     */
    closePosition: {
      name: "ClosePosition",
      I: MsgClosePosition,
      O: MsgClosePositionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.AddCollateral
     */
    addCollateral: {
      name: "AddCollateral",
      I: MsgAddCollateral,
      O: MsgAddCollateralResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.InitializeLiquidation
     */
    initializeLiquidation: {
      name: "InitializeLiquidation",
      I: MsgInitializeLiquidation,
      O: MsgInitializeLiquidationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.FinalizeLiquidation
     */
    finalizeLiquidation: {
      name: "FinalizeLiquidation",
      I: MsgFinalizeLiquidation,
      O: MsgFinalizeLiquidationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Params
     *
     * @generated from rpc dysonprotocol.whaleswap.v1.Msg.UpdateParams
     */
    updateParams: {
      name: "UpdateParams",
      I: MsgUpdateParams,
      O: MsgUpdateParamsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

