// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dysonprotocol/whaleswap/v1/leverage.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LiquidationStatus int32

const (
	LiquidationStatus_LIQUIDATION_STATUS_UNSPECIFIED LiquidationStatus = 0
	LiquidationStatus_LIQUIDATION_STATUS_NONE        LiquidationStatus = 1
	LiquidationStatus_LIQUIDATION_STATUS_INITIALIZED LiquidationStatus = 2
)

var LiquidationStatus_name = map[int32]string{
	0: "LIQUIDATION_STATUS_UNSPECIFIED",
	1: "LIQUIDATION_STATUS_NONE",
	2: "LIQUIDATION_STATUS_INITIALIZED",
}

var LiquidationStatus_value = map[string]int32{
	"LIQUIDATION_STATUS_UNSPECIFIED": 0,
	"LIQUIDATION_STATUS_NONE":        1,
	"LIQUIDATION_STATUS_INITIALIZED": 2,
}

func (x LiquidationStatus) String() string {
	return proto.EnumName(LiquidationStatus_name, int32(x))
}

func (LiquidationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef2aed91e4083e34, []int{0}
}

type PositionStatus int32

const (
	PositionStatus_POSITION_STATUS_UNSPECIFIED PositionStatus = 0
	PositionStatus_POSITION_STATUS_OPEN        PositionStatus = 1
	PositionStatus_POSITION_STATUS_CLOSED      PositionStatus = 2
	PositionStatus_POSITION_STATUS_LIQUIDATING PositionStatus = 3
	PositionStatus_POSITION_STATUS_LIQUIDATED  PositionStatus = 4
)

var PositionStatus_name = map[int32]string{
	0: "POSITION_STATUS_UNSPECIFIED",
	1: "POSITION_STATUS_OPEN",
	2: "POSITION_STATUS_CLOSED",
	3: "POSITION_STATUS_LIQUIDATING",
	4: "POSITION_STATUS_LIQUIDATED",
}

var PositionStatus_value = map[string]int32{
	"POSITION_STATUS_UNSPECIFIED": 0,
	"POSITION_STATUS_OPEN":        1,
	"POSITION_STATUS_CLOSED":      2,
	"POSITION_STATUS_LIQUIDATING": 3,
	"POSITION_STATUS_LIQUIDATED":  4,
}

func (x PositionStatus) String() string {
	return proto.EnumName(PositionStatus_name, int32(x))
}

func (PositionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef2aed91e4083e34, []int{1}
}

// DecCoinValue represents a decimal coin value that serializes as {denom,
// amount} object.
type DecCoinValue struct {
	Denom  string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *DecCoinValue) Reset()         { *m = DecCoinValue{} }
func (m *DecCoinValue) String() string { return proto.CompactTextString(m) }
func (*DecCoinValue) ProtoMessage()    {}
func (*DecCoinValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef2aed91e4083e34, []int{0}
}
func (m *DecCoinValue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DecCoinValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DecCoinValue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DecCoinValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecCoinValue.Merge(m, src)
}
func (m *DecCoinValue) XXX_Size() int {
	return m.Size()
}
func (m *DecCoinValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DecCoinValue.DiscardUnknown(m)
}

var xxx_messageInfo_DecCoinValue proto.InternalMessageInfo

func (m *DecCoinValue) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *DecCoinValue) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// LeveragePosition represents an active leverage position for a trader.
type LeveragePosition struct {
	PositionId                        uint64            `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	PoolId                            uint64            `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	User                              string            `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Status                            PositionStatus    `protobuf:"varint,4,opt,name=status,proto3,enum=dysonprotocol.whaleswap.v1.PositionStatus" json:"status,omitempty"`
	Borrowed                          types.Coin        `protobuf:"bytes,5,opt,name=borrowed,proto3" json:"borrowed"`
	Held                              types.Coin        `protobuf:"bytes,6,opt,name=held,proto3" json:"held"`
	Collateral                        types.Coin        `protobuf:"bytes,7,opt,name=collateral,proto3" json:"collateral"`
	CreatedHeight                     uint64            `protobuf:"varint,8,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	CreatedTime                       *time.Time        `protobuf:"bytes,9,opt,name=created_time,json=createdTime,proto3,stdtime" json:"created_time,omitempty"`
	LiquidationInitializedBlockHeight uint64            `protobuf:"varint,10,opt,name=liquidation_initialized_block_height,json=liquidationInitializedBlockHeight,proto3" json:"liquidation_initialized_block_height,omitempty"`
	LiquidationStatus                 LiquidationStatus `protobuf:"varint,11,opt,name=liquidation_status,json=liquidationStatus,proto3,enum=dysonprotocol.whaleswap.v1.LiquidationStatus" json:"liquidation_status,omitempty"`
	// Unpaid interest carried forward from prior settlements (borrowed denom).
	AccruedInterest types.Coin `protobuf:"bytes,12,opt,name=accrued_interest,json=accruedInterest,proto3" json:"accrued_interest"`
	UpdatedHeight   uint64     `protobuf:"varint,13,opt,name=updated_height,json=updatedHeight,proto3" json:"updated_height,omitempty"`
	UpdatedTime     *time.Time `protobuf:"bytes,14,opt,name=updated_time,json=updatedTime,proto3,stdtime" json:"updated_time,omitempty"`
	// ═════ PER-POSITION SNAPSHOTS (sticky to this position) ═════
	// Annual interest rate for the borrowed denom (APR as LegacyDec string).
	InterestRate types.DecCoin `protobuf:"bytes,22,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate"`
	// Minimum collateral ratio used for health/liquidation checks (cosmos.Dec
	// string).
	MinCollateralRatio string `protobuf:"bytes,23,opt,name=min_collateral_ratio,json=minCollateralRatio,proto3" json:"min_collateral_ratio,omitempty"`
	// Liquidation threshold used for liquidation checks (cosmos.Dec string).
	LiquidationThreshold string `protobuf:"bytes,24,opt,name=liquidation_threshold,json=liquidationThreshold,proto3" json:"liquidation_threshold,omitempty"`
	// Opening principal snapshot for analytics/limits (borrowed denom).
	InitialBorrowed types.Coin `protobuf:"bytes,25,opt,name=initial_borrowed,json=initialBorrowed,proto3" json:"initial_borrowed"`
	// Opening principal snapshot for analytics/limits (held denom).
	InitialHeld types.Coin `protobuf:"bytes,33,opt,name=initial_held,json=initialHeld,proto3" json:"initial_held"`
	// Opening principal snapshot for analytics/limits (collateral denom).
	InitialCollateral types.Coin `protobuf:"bytes,34,opt,name=initial_collateral,json=initialCollateral,proto3" json:"initial_collateral"`
	// Lifetime interest paid by the user (borrowed denom).
	TotalInterestPaid types.Coin `protobuf:"bytes,26,opt,name=total_interest_paid,json=totalInterestPaid,proto3" json:"total_interest_paid"`
	// Timestamp of the last time interest was settled into accrued_interest.
	LastInterestSettlementTime *time.Time `protobuf:"bytes,27,opt,name=last_interest_settlement_time,json=lastInterestSettlementTime,proto3,stdtime" json:"last_interest_settlement_time,omitempty"`
	// Fractional interest remainder (<1 borrowed coin) preserved between
	// settlements.
	AccruedInterestRemainder DecCoinValue `protobuf:"bytes,28,opt,name=accrued_interest_remainder,json=accruedInterestRemainder,proto3" json:"accrued_interest_remainder"`
	// Trade IDs associated with this position over its lifetime.
	//
	// Semantics:
	// - Includes the opening trade that created the position.
	// - Includes all trades from partial and full closes.
	// - Includes trades from liquidation paths.
	// - Includes trades from MsgCoverPosition (covers) auto-close path.
	//
	// Values are whaleswap Trade.trade_id (uint64).
	TradeIds []uint64 `protobuf:"varint,29,rep,packed,name=trade_ids,json=tradeIds,proto3" json:"trade_ids,omitempty"`
	// ═════ REALIZED P&L (PER POSITION) ═════
	// Cumulative realized profit from this position over its lifetime,
	// denominated in the borrowed denom. Includes:
	// - Profits from ClosePosition (full and partial closes)
	// - Profits from MsgCoverPosition auto-close path
	TotalRealizedProfit types.Coin `protobuf:"bytes,30,opt,name=total_realized_profit,json=totalRealizedProfit,proto3" json:"total_realized_profit"`
	// Cumulative realized loss from this position over its lifetime,
	// denominated in the borrowed denom. Includes:
	// - Losses realized in ClosePosition (full and partial closes)
	// - Losses realized during liquidation flows (if any)
	TotalRealizedLoss types.Coin `protobuf:"bytes,31,opt,name=total_realized_loss,json=totalRealizedLoss,proto3" json:"total_realized_loss"`
	// ═════ FINAL COLLATERAL RETURNED ═════
	// The amount of collateral returned to the user when the position was fully
	// closed. For partial closes, this accumulates the returned amount.
	CollateralReturned types.Coin `protobuf:"bytes,32,opt,name=collateral_returned,json=collateralReturned,proto3" json:"collateral_returned"`
}

func (m *LeveragePosition) Reset()         { *m = LeveragePosition{} }
func (m *LeveragePosition) String() string { return proto.CompactTextString(m) }
func (*LeveragePosition) ProtoMessage()    {}
func (*LeveragePosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef2aed91e4083e34, []int{1}
}
func (m *LeveragePosition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LeveragePosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LeveragePosition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LeveragePosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeveragePosition.Merge(m, src)
}
func (m *LeveragePosition) XXX_Size() int {
	return m.Size()
}
func (m *LeveragePosition) XXX_DiscardUnknown() {
	xxx_messageInfo_LeveragePosition.DiscardUnknown(m)
}

var xxx_messageInfo_LeveragePosition proto.InternalMessageInfo

func (m *LeveragePosition) GetPositionId() uint64 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

func (m *LeveragePosition) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *LeveragePosition) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *LeveragePosition) GetStatus() PositionStatus {
	if m != nil {
		return m.Status
	}
	return PositionStatus_POSITION_STATUS_UNSPECIFIED
}

func (m *LeveragePosition) GetBorrowed() types.Coin {
	if m != nil {
		return m.Borrowed
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetHeld() types.Coin {
	if m != nil {
		return m.Held
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetCollateral() types.Coin {
	if m != nil {
		return m.Collateral
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetCreatedHeight() uint64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

func (m *LeveragePosition) GetCreatedTime() *time.Time {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *LeveragePosition) GetLiquidationInitializedBlockHeight() uint64 {
	if m != nil {
		return m.LiquidationInitializedBlockHeight
	}
	return 0
}

func (m *LeveragePosition) GetLiquidationStatus() LiquidationStatus {
	if m != nil {
		return m.LiquidationStatus
	}
	return LiquidationStatus_LIQUIDATION_STATUS_UNSPECIFIED
}

func (m *LeveragePosition) GetAccruedInterest() types.Coin {
	if m != nil {
		return m.AccruedInterest
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetUpdatedHeight() uint64 {
	if m != nil {
		return m.UpdatedHeight
	}
	return 0
}

func (m *LeveragePosition) GetUpdatedTime() *time.Time {
	if m != nil {
		return m.UpdatedTime
	}
	return nil
}

func (m *LeveragePosition) GetInterestRate() types.DecCoin {
	if m != nil {
		return m.InterestRate
	}
	return types.DecCoin{}
}

func (m *LeveragePosition) GetMinCollateralRatio() string {
	if m != nil {
		return m.MinCollateralRatio
	}
	return ""
}

func (m *LeveragePosition) GetLiquidationThreshold() string {
	if m != nil {
		return m.LiquidationThreshold
	}
	return ""
}

func (m *LeveragePosition) GetInitialBorrowed() types.Coin {
	if m != nil {
		return m.InitialBorrowed
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetInitialHeld() types.Coin {
	if m != nil {
		return m.InitialHeld
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetInitialCollateral() types.Coin {
	if m != nil {
		return m.InitialCollateral
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetTotalInterestPaid() types.Coin {
	if m != nil {
		return m.TotalInterestPaid
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetLastInterestSettlementTime() *time.Time {
	if m != nil {
		return m.LastInterestSettlementTime
	}
	return nil
}

func (m *LeveragePosition) GetAccruedInterestRemainder() DecCoinValue {
	if m != nil {
		return m.AccruedInterestRemainder
	}
	return DecCoinValue{}
}

func (m *LeveragePosition) GetTradeIds() []uint64 {
	if m != nil {
		return m.TradeIds
	}
	return nil
}

func (m *LeveragePosition) GetTotalRealizedProfit() types.Coin {
	if m != nil {
		return m.TotalRealizedProfit
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetTotalRealizedLoss() types.Coin {
	if m != nil {
		return m.TotalRealizedLoss
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetCollateralReturned() types.Coin {
	if m != nil {
		return m.CollateralReturned
	}
	return types.Coin{}
}

func init() {
	proto.RegisterEnum("dysonprotocol.whaleswap.v1.LiquidationStatus", LiquidationStatus_name, LiquidationStatus_value)
	proto.RegisterEnum("dysonprotocol.whaleswap.v1.PositionStatus", PositionStatus_name, PositionStatus_value)
	proto.RegisterType((*DecCoinValue)(nil), "dysonprotocol.whaleswap.v1.DecCoinValue")
	proto.RegisterType((*LeveragePosition)(nil), "dysonprotocol.whaleswap.v1.LeveragePosition")
}

func init() {
	proto.RegisterFile("dysonprotocol/whaleswap/v1/leverage.proto", fileDescriptor_ef2aed91e4083e34)
}

var fileDescriptor_ef2aed91e4083e34 = []byte{
	// 1021 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x4e, 0x1b, 0x47,
	0x14, 0x66, 0x83, 0x43, 0x60, 0x00, 0xd7, 0x4c, 0x1c, 0x18, 0x4c, 0x62, 0x13, 0xfa, 0x23, 0x8a,
	0xca, 0x5a, 0x24, 0x97, 0x55, 0xd5, 0xe2, 0x9f, 0x36, 0x5b, 0x59, 0xb6, 0xbb, 0x36, 0x95, 0x1a,
	0x55, 0x5a, 0x8d, 0x77, 0x26, 0xf6, 0xa8, 0xe3, 0x1d, 0x77, 0x67, 0x0c, 0x49, 0x9f, 0x22, 0x8f,
	0xd1, 0x07, 0xe0, 0xbe, 0xb7, 0xb9, 0x8c, 0xb8, 0xea, 0x55, 0x5b, 0xc1, 0x8b, 0x54, 0x3b, 0x3b,
	0x6b, 0x2f, 0x14, 0xa2, 0xed, 0x9d, 0xf7, 0x9c, 0xef, 0xfb, 0xce, 0xf1, 0x77, 0xce, 0xf1, 0x1a,
	0x7c, 0x4e, 0xde, 0x48, 0x11, 0x4c, 0x42, 0xa1, 0x84, 0x2f, 0x78, 0xf5, 0x6c, 0x84, 0x39, 0x95,
	0x67, 0x78, 0x52, 0x3d, 0x3d, 0xaa, 0x72, 0x7a, 0x4a, 0x43, 0x3c, 0xa4, 0xb6, 0x4e, 0xc3, 0xd2,
	0x35, 0xa8, 0x3d, 0x83, 0xda, 0xa7, 0x47, 0xa5, 0xe2, 0x50, 0x0c, 0x85, 0x4e, 0x55, 0xa3, 0x4f,
	0x31, 0xa3, 0x54, 0xf6, 0x85, 0x1c, 0x0b, 0x59, 0x1d, 0x60, 0x49, 0xab, 0xa7, 0x47, 0x03, 0xaa,
	0xf0, 0x51, 0xd5, 0x17, 0x2c, 0x30, 0xf9, 0xed, 0x38, 0xef, 0xc5, 0xc4, 0xf8, 0xc1, 0xa4, 0x2a,
	0x43, 0x21, 0x86, 0x9c, 0x56, 0xf5, 0xd3, 0x60, 0xfa, 0xaa, 0xaa, 0xd8, 0x98, 0x4a, 0x85, 0xc7,
	0x93, 0x18, 0xb0, 0xd7, 0x02, 0x6b, 0x0d, 0xea, 0xd7, 0x05, 0x0b, 0x7e, 0xc4, 0x7c, 0x4a, 0x61,
	0x11, 0xdc, 0x27, 0x34, 0x10, 0x63, 0x64, 0xed, 0x5a, 0xfb, 0x2b, 0x6e, 0xfc, 0x00, 0x3f, 0x03,
	0x4b, 0x78, 0x2c, 0xa6, 0x81, 0x42, 0xf7, 0xa2, 0x70, 0x2d, 0x7f, 0x71, 0x7e, 0x08, 0x4c, 0xa1,
	0x06, 0xf5, 0x5d, 0x93, 0xdd, 0xfb, 0x23, 0x0f, 0x0a, 0x2d, 0xf3, 0x75, 0xbb, 0x42, 0x32, 0xc5,
	0x44, 0x00, 0x2b, 0x60, 0x75, 0x62, 0x3e, 0x7b, 0x8c, 0x68, 0xe1, 0x9c, 0x0b, 0x92, 0x90, 0x43,
	0xe0, 0x16, 0x78, 0x30, 0x11, 0x82, 0x47, 0xc9, 0x7b, 0x3a, 0xb9, 0x14, 0x3d, 0x3a, 0x04, 0x7e,
	0x01, 0x72, 0x53, 0x49, 0x43, 0xb4, 0xa8, 0x8b, 0xa2, 0x8b, 0xf3, 0xc3, 0xa2, 0x29, 0x7a, 0x4c,
	0x48, 0x48, 0xa5, 0xec, 0xa9, 0x90, 0x05, 0x43, 0x57, 0xa3, 0x60, 0x0d, 0x2c, 0x49, 0x85, 0xd5,
	0x54, 0xa2, 0xdc, 0xae, 0xb5, 0x9f, 0x7f, 0x76, 0x60, 0xdf, 0xed, 0xb4, 0x9d, 0x74, 0xd7, 0xd3,
	0x0c, 0xd7, 0x30, 0xe1, 0x97, 0x60, 0x79, 0x20, 0xc2, 0x50, 0x9c, 0x51, 0x82, 0xee, 0xef, 0x5a,
	0xfb, 0xab, 0xcf, 0xb6, 0x6d, 0x53, 0x32, 0x72, 0xdf, 0x36, 0xee, 0xdb, 0x91, 0x61, 0xb5, 0xdc,
	0xbb, 0xbf, 0x2a, 0x0b, 0xee, 0x8c, 0x00, 0x9f, 0x83, 0xdc, 0x88, 0x72, 0x82, 0x96, 0xb2, 0x11,
	0x35, 0x18, 0x7e, 0x0d, 0x80, 0x2f, 0x38, 0xc7, 0x8a, 0x86, 0x98, 0xa3, 0x07, 0xd9, 0xa8, 0x29,
	0x0a, 0xfc, 0x14, 0xe4, 0xfd, 0x90, 0x62, 0x45, 0x89, 0x37, 0xa2, 0x6c, 0x38, 0x52, 0x68, 0x59,
	0x9b, 0xb8, 0x6e, 0xa2, 0x2f, 0x74, 0x10, 0xd6, 0xc1, 0x5a, 0x02, 0x8b, 0x76, 0x00, 0xad, 0xe8,
	0x4a, 0x25, 0x3b, 0x5e, 0x10, 0x3b, 0x59, 0x10, 0xbb, 0x9f, 0x2c, 0x48, 0x2d, 0xf7, 0xf6, 0xef,
	0x8a, 0xe5, 0xae, 0x1a, 0x56, 0x14, 0x87, 0x1d, 0xf0, 0x09, 0x67, 0xbf, 0x4e, 0x19, 0xc1, 0xf1,
	0x34, 0x03, 0xa6, 0x18, 0xe6, 0xec, 0x37, 0x4a, 0xbc, 0x01, 0x17, 0xfe, 0x2f, 0x49, 0x07, 0x40,
	0x77, 0xf0, 0x34, 0x85, 0x75, 0xe6, 0xd0, 0x5a, 0x84, 0x34, 0x5d, 0xfd, 0x0c, 0x60, 0x5a, 0xd0,
	0xcc, 0x6f, 0x55, 0xcf, 0xef, 0xf0, 0x43, 0xf3, 0x6b, 0xcd, 0x59, 0x66, 0x84, 0x1b, 0xfc, 0x66,
	0x08, 0x7e, 0x0f, 0x0a, 0xd8, 0xf7, 0xc3, 0x29, 0x25, 0x1e, 0x0b, 0x14, 0x0d, 0xa9, 0x54, 0x68,
	0x2d, 0x9b, 0xc3, 0x1f, 0x19, 0xa2, 0x63, 0x78, 0x91, 0xcd, 0xd3, 0x09, 0x49, 0xdb, 0xbc, 0x1e,
	0xdb, 0x6c, 0xa2, 0x73, 0x9b, 0x13, 0x98, 0xb6, 0x39, 0x9f, 0xd5, 0x66, 0xc3, 0xd2, 0x36, 0xff,
	0x04, 0xd6, 0x93, 0x7e, 0xbd, 0x10, 0x2b, 0x8a, 0x36, 0xb5, 0xca, 0xe3, 0x5b, 0x9b, 0x36, 0xe7,
	0x5b, 0xdb, 0x8c, 0xfa, 0xbe, 0x38, 0x3f, 0xcc, 0xcf, 0xef, 0x32, 0x8a, 0xbb, 0x6b, 0x89, 0x94,
	0x8b, 0x15, 0x85, 0xdf, 0x80, 0xe2, 0x98, 0x05, 0xde, 0x7c, 0x7f, 0xa2, 0x02, 0x4c, 0xa0, 0xad,
	0x5b, 0xef, 0x1a, 0x8e, 0x59, 0x50, 0x9f, 0x41, 0xdd, 0x08, 0x09, 0xeb, 0xe0, 0x51, 0x7a, 0x64,
	0x6a, 0x14, 0x52, 0x39, 0x12, 0x9c, 0x20, 0x74, 0xab, 0x44, 0x31, 0x05, 0xee, 0x27, 0xd8, 0x68,
	0x32, 0x66, 0x79, 0xbc, 0xd9, 0xbd, 0x6d, 0x67, 0x9c, 0x8c, 0x21, 0xd6, 0x92, 0xb3, 0xab, 0x81,
	0xb5, 0x44, 0x4b, 0x9f, 0xdf, 0xd3, 0x6c, 0x3a, 0xab, 0x86, 0xf4, 0x22, 0xba, 0xc2, 0x36, 0x80,
	0x89, 0x46, 0xea, 0x1a, 0xf7, 0xb2, 0x29, 0x6d, 0x18, 0xea, 0xdc, 0x29, 0xd8, 0x01, 0x0f, 0x95,
	0x50, 0x98, 0xcf, 0xf6, 0xce, 0x9b, 0x60, 0x46, 0x50, 0x29, 0xa3, 0xa0, 0xe6, 0x26, 0xab, 0xd7,
	0xc5, 0x8c, 0x40, 0x1f, 0x3c, 0xe1, 0x58, 0xaa, 0xb9, 0x9e, 0xa4, 0x4a, 0x71, 0x3a, 0xa6, 0x81,
	0x8a, 0x17, 0x6d, 0x27, 0xe3, 0xa2, 0x95, 0x22, 0x99, 0x44, 0xba, 0x37, 0x13, 0xd1, 0x7b, 0xc7,
	0x41, 0xe9, 0xe6, 0xbd, 0x78, 0x21, 0x1d, 0x63, 0x16, 0x10, 0x1a, 0xa2, 0xc7, 0xba, 0xc2, 0xfe,
	0x87, 0xae, 0x32, 0xfd, 0x2a, 0x31, 0xdf, 0x05, 0xdd, 0x38, 0x24, 0x37, 0xd1, 0x83, 0x3b, 0x60,
	0x45, 0x85, 0x98, 0x50, 0x8f, 0x11, 0x89, 0x9e, 0xec, 0x2e, 0xee, 0xe7, 0xdc, 0x65, 0x1d, 0x70,
	0x88, 0x84, 0x3d, 0xf0, 0x28, 0x36, 0x30, 0xa4, 0xe6, 0x07, 0x66, 0x12, 0x8a, 0x57, 0x4c, 0xa1,
	0x72, 0x36, 0x0b, 0x63, 0xfb, 0x5d, 0x43, 0xee, 0x6a, 0xee, 0x7c, 0x2a, 0x33, 0x51, 0x2e, 0xa4,
	0x44, 0x95, 0xff, 0x33, 0x95, 0x44, 0xb2, 0x25, 0xa4, 0x84, 0x5d, 0xf0, 0x30, 0x7d, 0x49, 0x54,
	0x4d, 0xc3, 0x80, 0x12, 0xb4, 0x9b, 0x4d, 0x10, 0xce, 0xb9, 0xae, 0xa1, 0x1e, 0xbc, 0x06, 0x1b,
	0xff, 0xf9, 0x69, 0x83, 0x7b, 0xa0, 0xdc, 0x72, 0x7e, 0x38, 0x71, 0x1a, 0xc7, 0x7d, 0xa7, 0xd3,
	0xf6, 0x7a, 0xfd, 0xe3, 0xfe, 0x49, 0xcf, 0x3b, 0x69, 0xf7, 0xba, 0xcd, 0xba, 0xf3, 0xad, 0xd3,
	0x6c, 0x14, 0x16, 0xe0, 0x0e, 0xd8, 0xba, 0x05, 0xd3, 0xee, 0xb4, 0x9b, 0x05, 0xeb, 0x0e, 0x01,
	0xa7, 0xed, 0xf4, 0x9d, 0xe3, 0x96, 0xf3, 0xb2, 0xd9, 0x28, 0xdc, 0x3b, 0xf8, 0xdd, 0x02, 0xf9,
	0xeb, 0x6f, 0x45, 0x58, 0x01, 0x3b, 0xdd, 0x4e, 0xcf, 0xb9, 0xbb, 0x28, 0x02, 0xc5, 0x9b, 0x80,
	0x4e, 0xb7, 0xd9, 0x2e, 0x58, 0xb0, 0x04, 0x36, 0x6f, 0x66, 0xea, 0xad, 0x4e, 0x2f, 0xaa, 0x74,
	0x9b, 0xec, 0xac, 0xbb, 0xf6, 0x77, 0x85, 0x45, 0x58, 0x06, 0xa5, 0xbb, 0x00, 0xcd, 0x46, 0x21,
	0x57, 0xfb, 0xea, 0xdd, 0x65, 0xd9, 0x7a, 0x7f, 0x59, 0xb6, 0xfe, 0xb9, 0x2c, 0x5b, 0x6f, 0xaf,
	0xca, 0x0b, 0xef, 0xaf, 0xca, 0x0b, 0x7f, 0x5e, 0x95, 0x17, 0x5e, 0x7e, 0x7c, 0x7d, 0x39, 0x7d,
	0x31, 0xae, 0xbe, 0x4e, 0xfd, 0x1b, 0x53, 0x6f, 0x26, 0x54, 0x0e, 0x96, 0x74, 0xfe, 0xf9, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xf1, 0x93, 0xe1, 0xb5, 0x09, 0x00, 0x00,
}

func (m *DecCoinValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DecCoinValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DecCoinValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintLeverage(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintLeverage(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LeveragePosition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LeveragePosition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LeveragePosition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.InitialCollateral.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0x92
	{
		size, err := m.InitialHeld.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0x8a
	{
		size, err := m.CollateralReturned.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2
	i--
	dAtA[i] = 0x82
	{
		size, err := m.TotalRealizedLoss.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xfa
	{
		size, err := m.TotalRealizedProfit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xf2
	if len(m.TradeIds) > 0 {
		dAtA7 := make([]byte, len(m.TradeIds)*10)
		var j6 int
		for _, num := range m.TradeIds {
			for num >= 1<<7 {
				dAtA7[j6] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j6++
			}
			dAtA7[j6] = uint8(num)
			j6++
		}
		i -= j6
		copy(dAtA[i:], dAtA7[:j6])
		i = encodeVarintLeverage(dAtA, i, uint64(j6))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xea
	}
	{
		size, err := m.AccruedInterestRemainder.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xe2
	if m.LastInterestSettlementTime != nil {
		n9, err9 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.LastInterestSettlementTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastInterestSettlementTime):])
		if err9 != nil {
			return 0, err9
		}
		i -= n9
		i = encodeVarintLeverage(dAtA, i, uint64(n9))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xda
	}
	{
		size, err := m.TotalInterestPaid.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xd2
	{
		size, err := m.InitialBorrowed.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xca
	if len(m.LiquidationThreshold) > 0 {
		i -= len(m.LiquidationThreshold)
		copy(dAtA[i:], m.LiquidationThreshold)
		i = encodeVarintLeverage(dAtA, i, uint64(len(m.LiquidationThreshold)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc2
	}
	if len(m.MinCollateralRatio) > 0 {
		i -= len(m.MinCollateralRatio)
		copy(dAtA[i:], m.MinCollateralRatio)
		i = encodeVarintLeverage(dAtA, i, uint64(len(m.MinCollateralRatio)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xba
	}
	{
		size, err := m.InterestRate.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xb2
	if m.UpdatedTime != nil {
		n13, err13 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.UpdatedTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.UpdatedTime):])
		if err13 != nil {
			return 0, err13
		}
		i -= n13
		i = encodeVarintLeverage(dAtA, i, uint64(n13))
		i--
		dAtA[i] = 0x72
	}
	if m.UpdatedHeight != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.UpdatedHeight))
		i--
		dAtA[i] = 0x68
	}
	{
		size, err := m.AccruedInterest.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if m.LiquidationStatus != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.LiquidationStatus))
		i--
		dAtA[i] = 0x58
	}
	if m.LiquidationInitializedBlockHeight != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.LiquidationInitializedBlockHeight))
		i--
		dAtA[i] = 0x50
	}
	if m.CreatedTime != nil {
		n15, err15 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.CreatedTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.CreatedTime):])
		if err15 != nil {
			return 0, err15
		}
		i -= n15
		i = encodeVarintLeverage(dAtA, i, uint64(n15))
		i--
		dAtA[i] = 0x4a
	}
	if m.CreatedHeight != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.CreatedHeight))
		i--
		dAtA[i] = 0x40
	}
	{
		size, err := m.Collateral.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.Held.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.Borrowed.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Status != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if len(m.User) > 0 {
		i -= len(m.User)
		copy(dAtA[i:], m.User)
		i = encodeVarintLeverage(dAtA, i, uint64(len(m.User)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PoolId != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x10
	}
	if m.PositionId != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.PositionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLeverage(dAtA []byte, offset int, v uint64) int {
	offset -= sovLeverage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DecCoinValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovLeverage(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovLeverage(uint64(l))
	}
	return n
}

func (m *LeveragePosition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PositionId != 0 {
		n += 1 + sovLeverage(uint64(m.PositionId))
	}
	if m.PoolId != 0 {
		n += 1 + sovLeverage(uint64(m.PoolId))
	}
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovLeverage(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovLeverage(uint64(m.Status))
	}
	l = m.Borrowed.Size()
	n += 1 + l + sovLeverage(uint64(l))
	l = m.Held.Size()
	n += 1 + l + sovLeverage(uint64(l))
	l = m.Collateral.Size()
	n += 1 + l + sovLeverage(uint64(l))
	if m.CreatedHeight != 0 {
		n += 1 + sovLeverage(uint64(m.CreatedHeight))
	}
	if m.CreatedTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.CreatedTime)
		n += 1 + l + sovLeverage(uint64(l))
	}
	if m.LiquidationInitializedBlockHeight != 0 {
		n += 1 + sovLeverage(uint64(m.LiquidationInitializedBlockHeight))
	}
	if m.LiquidationStatus != 0 {
		n += 1 + sovLeverage(uint64(m.LiquidationStatus))
	}
	l = m.AccruedInterest.Size()
	n += 1 + l + sovLeverage(uint64(l))
	if m.UpdatedHeight != 0 {
		n += 1 + sovLeverage(uint64(m.UpdatedHeight))
	}
	if m.UpdatedTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.UpdatedTime)
		n += 1 + l + sovLeverage(uint64(l))
	}
	l = m.InterestRate.Size()
	n += 2 + l + sovLeverage(uint64(l))
	l = len(m.MinCollateralRatio)
	if l > 0 {
		n += 2 + l + sovLeverage(uint64(l))
	}
	l = len(m.LiquidationThreshold)
	if l > 0 {
		n += 2 + l + sovLeverage(uint64(l))
	}
	l = m.InitialBorrowed.Size()
	n += 2 + l + sovLeverage(uint64(l))
	l = m.TotalInterestPaid.Size()
	n += 2 + l + sovLeverage(uint64(l))
	if m.LastInterestSettlementTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastInterestSettlementTime)
		n += 2 + l + sovLeverage(uint64(l))
	}
	l = m.AccruedInterestRemainder.Size()
	n += 2 + l + sovLeverage(uint64(l))
	if len(m.TradeIds) > 0 {
		l = 0
		for _, e := range m.TradeIds {
			l += sovLeverage(uint64(e))
		}
		n += 2 + sovLeverage(uint64(l)) + l
	}
	l = m.TotalRealizedProfit.Size()
	n += 2 + l + sovLeverage(uint64(l))
	l = m.TotalRealizedLoss.Size()
	n += 2 + l + sovLeverage(uint64(l))
	l = m.CollateralReturned.Size()
	n += 2 + l + sovLeverage(uint64(l))
	l = m.InitialHeld.Size()
	n += 2 + l + sovLeverage(uint64(l))
	l = m.InitialCollateral.Size()
	n += 2 + l + sovLeverage(uint64(l))
	return n
}

func sovLeverage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLeverage(x uint64) (n int) {
	return sovLeverage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DecCoinValue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLeverage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DecCoinValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DecCoinValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLeverage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLeverage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LeveragePosition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLeverage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LeveragePosition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LeveragePosition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PositionId", wireType)
			}
			m.PositionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PositionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PositionStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Borrowed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Borrowed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Held", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Held.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Collateral.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedHeight", wireType)
			}
			m.CreatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedTime == nil {
				m.CreatedTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.CreatedTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationInitializedBlockHeight", wireType)
			}
			m.LiquidationInitializedBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidationInitializedBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationStatus", wireType)
			}
			m.LiquidationStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidationStatus |= LiquidationStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccruedInterest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AccruedInterest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedHeight", wireType)
			}
			m.UpdatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedTime == nil {
				m.UpdatedTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.UpdatedTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InterestRate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InterestRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCollateralRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinCollateralRatio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 24:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidationThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialBorrowed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialBorrowed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 26:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalInterestPaid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalInterestPaid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 27:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastInterestSettlementTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastInterestSettlementTime == nil {
				m.LastInterestSettlementTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.LastInterestSettlementTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 28:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccruedInterestRemainder", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AccruedInterestRemainder.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 29:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLeverage
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.TradeIds = append(m.TradeIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLeverage
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthLeverage
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthLeverage
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.TradeIds) == 0 {
					m.TradeIds = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLeverage
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.TradeIds = append(m.TradeIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeIds", wireType)
			}
		case 30:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRealizedProfit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalRealizedProfit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 31:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRealizedLoss", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalRealizedLoss.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 32:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralReturned", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollateralReturned.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 33:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialHeld", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialHeld.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 34:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialCollateral", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialCollateral.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLeverage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLeverage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLeverage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLeverage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLeverage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLeverage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLeverage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLeverage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLeverage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLeverage = fmt.Errorf("proto: unexpected end of group")
)
