// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dysonprotocol/whaleswap/v1/leverage.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LiquidationStatus int32

const (
	LiquidationStatus_LIQUIDATION_STATUS_UNSPECIFIED LiquidationStatus = 0
	LiquidationStatus_LIQUIDATION_STATUS_NONE        LiquidationStatus = 1
	LiquidationStatus_LIQUIDATION_STATUS_INITIALIZED LiquidationStatus = 2
)

var LiquidationStatus_name = map[int32]string{
	0: "LIQUIDATION_STATUS_UNSPECIFIED",
	1: "LIQUIDATION_STATUS_NONE",
	2: "LIQUIDATION_STATUS_INITIALIZED",
}

var LiquidationStatus_value = map[string]int32{
	"LIQUIDATION_STATUS_UNSPECIFIED": 0,
	"LIQUIDATION_STATUS_NONE":        1,
	"LIQUIDATION_STATUS_INITIALIZED": 2,
}

func (x LiquidationStatus) String() string {
	return proto.EnumName(LiquidationStatus_name, int32(x))
}

func (LiquidationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef2aed91e4083e34, []int{0}
}

type PositionStatus int32

const (
	PositionStatus_POSITION_STATUS_UNSPECIFIED PositionStatus = 0
	PositionStatus_POSITION_STATUS_OPEN        PositionStatus = 1
	PositionStatus_POSITION_STATUS_CLOSED      PositionStatus = 2
	PositionStatus_POSITION_STATUS_LIQUIDATING PositionStatus = 3
	PositionStatus_POSITION_STATUS_LIQUIDATED  PositionStatus = 4
)

var PositionStatus_name = map[int32]string{
	0: "POSITION_STATUS_UNSPECIFIED",
	1: "POSITION_STATUS_OPEN",
	2: "POSITION_STATUS_CLOSED",
	3: "POSITION_STATUS_LIQUIDATING",
	4: "POSITION_STATUS_LIQUIDATED",
}

var PositionStatus_value = map[string]int32{
	"POSITION_STATUS_UNSPECIFIED": 0,
	"POSITION_STATUS_OPEN":        1,
	"POSITION_STATUS_CLOSED":      2,
	"POSITION_STATUS_LIQUIDATING": 3,
	"POSITION_STATUS_LIQUIDATED":  4,
}

func (x PositionStatus) String() string {
	return proto.EnumName(PositionStatus_name, int32(x))
}

func (PositionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef2aed91e4083e34, []int{1}
}

// LeveragePosition represents an active leverage position for a trader.
type LeveragePosition struct {
	PositionId                        uint64            `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	PoolId                            uint64            `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	User                              string            `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Status                            PositionStatus    `protobuf:"varint,4,opt,name=status,proto3,enum=dysonprotocol.whaleswap.v1.PositionStatus" json:"status,omitempty"`
	Borrowed                          types.Coin        `protobuf:"bytes,5,opt,name=borrowed,proto3" json:"borrowed"`
	Held                              types.Coin        `protobuf:"bytes,6,opt,name=held,proto3" json:"held"`
	Collateral                        types.Coin        `protobuf:"bytes,7,opt,name=collateral,proto3" json:"collateral"`
	CreatedHeight                     uint64            `protobuf:"varint,8,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	CreatedTime                       *time.Time        `protobuf:"bytes,9,opt,name=created_time,json=createdTime,proto3,stdtime" json:"created_time,omitempty"`
	LiquidationInitializedBlockHeight uint64            `protobuf:"varint,10,opt,name=liquidation_initialized_block_height,json=liquidationInitializedBlockHeight,proto3" json:"liquidation_initialized_block_height,omitempty"`
	LiquidationStatus                 LiquidationStatus `protobuf:"varint,11,opt,name=liquidation_status,json=liquidationStatus,proto3,enum=dysonprotocol.whaleswap.v1.LiquidationStatus" json:"liquidation_status,omitempty"`
	// Unpaid interest carried forward from prior settlements (borrowed denom).
	AccruedInterest types.Coin `protobuf:"bytes,12,opt,name=accrued_interest,json=accruedInterest,proto3" json:"accrued_interest"`
	UpdatedHeight   uint64     `protobuf:"varint,13,opt,name=updated_height,json=updatedHeight,proto3" json:"updated_height,omitempty"`
	UpdatedTime     *time.Time `protobuf:"bytes,14,opt,name=updated_time,json=updatedTime,proto3,stdtime" json:"updated_time,omitempty"`
	// ═════ PER-POSITION SNAPSHOTS (sticky to this position) ═════
	// Annual interest rates per reserve denom (exactly two, canonical order).
	// Each amount is a LegacyDec string representing APR (per-year accrual).
	InterestRate github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,22,rep,name=interest_rate,json=interestRate,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"interest_rate"`
	// Minimum collateral ratio used for health/liquidation checks (cosmos.Dec
	// string).
	MinCollateralRatio string `protobuf:"bytes,23,opt,name=min_collateral_ratio,json=minCollateralRatio,proto3" json:"min_collateral_ratio,omitempty"`
	// Liquidation threshold used for liquidation checks (cosmos.Dec string).
	LiquidationThreshold string `protobuf:"bytes,24,opt,name=liquidation_threshold,json=liquidationThreshold,proto3" json:"liquidation_threshold,omitempty"`
	// Opening principal snapshot for analytics/limits (borrowed denom).
	InitialBorrowed types.Coin `protobuf:"bytes,25,opt,name=initial_borrowed,json=initialBorrowed,proto3" json:"initial_borrowed"`
	// Lifetime interest paid by the user (borrowed denom).
	TotalInterestPaid types.Coin `protobuf:"bytes,26,opt,name=total_interest_paid,json=totalInterestPaid,proto3" json:"total_interest_paid"`
	// Timestamp of the last time interest was settled into accrued_interest.
	LastInterestSettlementTime *time.Time `protobuf:"bytes,27,opt,name=last_interest_settlement_time,json=lastInterestSettlementTime,proto3,stdtime" json:"last_interest_settlement_time,omitempty"`
	// Fractional interest remainder (<1 borrowed coin) preserved between
	// settlements.
	AccruedInterestRemainder string `protobuf:"bytes,28,opt,name=accrued_interest_remainder,json=accruedInterestRemainder,proto3" json:"accrued_interest_remainder,omitempty"`
	// Trade IDs associated with this position over its lifetime.
	//
	// Semantics:
	// - Includes the opening trade that created the position.
	// - Includes all trades from partial and full closes.
	// - Includes trades from liquidation paths.
	// - Includes trades from MsgCoverPosition (covers) auto-close path.
	//
	// Values are whaleswap Trade.trade_id (uint64).
	TradeIds []uint64 `protobuf:"varint,29,rep,packed,name=trade_ids,json=tradeIds,proto3" json:"trade_ids,omitempty"`
}

func (m *LeveragePosition) Reset()         { *m = LeveragePosition{} }
func (m *LeveragePosition) String() string { return proto.CompactTextString(m) }
func (*LeveragePosition) ProtoMessage()    {}
func (*LeveragePosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef2aed91e4083e34, []int{0}
}
func (m *LeveragePosition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LeveragePosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LeveragePosition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LeveragePosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeveragePosition.Merge(m, src)
}
func (m *LeveragePosition) XXX_Size() int {
	return m.Size()
}
func (m *LeveragePosition) XXX_DiscardUnknown() {
	xxx_messageInfo_LeveragePosition.DiscardUnknown(m)
}

var xxx_messageInfo_LeveragePosition proto.InternalMessageInfo

func (m *LeveragePosition) GetPositionId() uint64 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

func (m *LeveragePosition) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *LeveragePosition) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *LeveragePosition) GetStatus() PositionStatus {
	if m != nil {
		return m.Status
	}
	return PositionStatus_POSITION_STATUS_UNSPECIFIED
}

func (m *LeveragePosition) GetBorrowed() types.Coin {
	if m != nil {
		return m.Borrowed
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetHeld() types.Coin {
	if m != nil {
		return m.Held
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetCollateral() types.Coin {
	if m != nil {
		return m.Collateral
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetCreatedHeight() uint64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

func (m *LeveragePosition) GetCreatedTime() *time.Time {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *LeveragePosition) GetLiquidationInitializedBlockHeight() uint64 {
	if m != nil {
		return m.LiquidationInitializedBlockHeight
	}
	return 0
}

func (m *LeveragePosition) GetLiquidationStatus() LiquidationStatus {
	if m != nil {
		return m.LiquidationStatus
	}
	return LiquidationStatus_LIQUIDATION_STATUS_UNSPECIFIED
}

func (m *LeveragePosition) GetAccruedInterest() types.Coin {
	if m != nil {
		return m.AccruedInterest
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetUpdatedHeight() uint64 {
	if m != nil {
		return m.UpdatedHeight
	}
	return 0
}

func (m *LeveragePosition) GetUpdatedTime() *time.Time {
	if m != nil {
		return m.UpdatedTime
	}
	return nil
}

func (m *LeveragePosition) GetInterestRate() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.InterestRate
	}
	return nil
}

func (m *LeveragePosition) GetMinCollateralRatio() string {
	if m != nil {
		return m.MinCollateralRatio
	}
	return ""
}

func (m *LeveragePosition) GetLiquidationThreshold() string {
	if m != nil {
		return m.LiquidationThreshold
	}
	return ""
}

func (m *LeveragePosition) GetInitialBorrowed() types.Coin {
	if m != nil {
		return m.InitialBorrowed
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetTotalInterestPaid() types.Coin {
	if m != nil {
		return m.TotalInterestPaid
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetLastInterestSettlementTime() *time.Time {
	if m != nil {
		return m.LastInterestSettlementTime
	}
	return nil
}

func (m *LeveragePosition) GetAccruedInterestRemainder() string {
	if m != nil {
		return m.AccruedInterestRemainder
	}
	return ""
}

func (m *LeveragePosition) GetTradeIds() []uint64 {
	if m != nil {
		return m.TradeIds
	}
	return nil
}

func init() {
	proto.RegisterEnum("dysonprotocol.whaleswap.v1.LiquidationStatus", LiquidationStatus_name, LiquidationStatus_value)
	proto.RegisterEnum("dysonprotocol.whaleswap.v1.PositionStatus", PositionStatus_name, PositionStatus_value)
	proto.RegisterType((*LeveragePosition)(nil), "dysonprotocol.whaleswap.v1.LeveragePosition")
}

func init() {
	proto.RegisterFile("dysonprotocol/whaleswap/v1/leverage.proto", fileDescriptor_ef2aed91e4083e34)
}

var fileDescriptor_ef2aed91e4083e34 = []byte{
	// 907 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xdf, 0x6e, 0xe2, 0xc6,
	0x17, 0xc6, 0x1b, 0x7e, 0xd9, 0x64, 0x48, 0xf8, 0x91, 0x29, 0xdd, 0x4c, 0xc8, 0xae, 0xa1, 0xdb,
	0x56, 0xa2, 0x69, 0x63, 0x2b, 0xc9, 0x65, 0x55, 0xb5, 0xe1, 0x4f, 0x5b, 0x57, 0x08, 0xa8, 0x21,
	0x37, 0xab, 0x4a, 0xd6, 0xe0, 0x99, 0xc2, 0x68, 0x8d, 0x87, 0x7a, 0x06, 0xb2, 0xdb, 0xa7, 0xd8,
	0xc7, 0xa8, 0x7a, 0xd5, 0x8b, 0x7d, 0x88, 0xbd, 0x5c, 0xed, 0x55, 0xaf, 0xba, 0x55, 0xf2, 0x22,
	0x95, 0xc7, 0x63, 0x20, 0x94, 0x54, 0x5c, 0x61, 0x9f, 0xf3, 0x7d, 0xe7, 0x1c, 0x7d, 0xdf, 0x39,
	0x06, 0x7c, 0x46, 0x5e, 0x0a, 0x1e, 0x4e, 0x22, 0x2e, 0xb9, 0xcf, 0x03, 0xfb, 0x7a, 0x84, 0x03,
	0x2a, 0xae, 0xf1, 0xc4, 0x9e, 0x9d, 0xd9, 0x01, 0x9d, 0xd1, 0x08, 0x0f, 0xa9, 0xa5, 0xd2, 0xb0,
	0x74, 0x07, 0x6a, 0xcd, 0xa1, 0xd6, 0xec, 0xac, 0x54, 0x1c, 0xf2, 0x21, 0x57, 0x29, 0x3b, 0x7e,
	0x4a, 0x18, 0x25, 0xd3, 0xe7, 0x62, 0xcc, 0x85, 0x3d, 0xc0, 0x82, 0xda, 0xb3, 0xb3, 0x01, 0x95,
	0xf8, 0xcc, 0xf6, 0x39, 0x0b, 0x75, 0xfe, 0x28, 0xc9, 0x7b, 0x09, 0x31, 0x79, 0xd1, 0xa9, 0xf2,
	0x90, 0xf3, 0x61, 0x40, 0x6d, 0xf5, 0x36, 0x98, 0xfe, 0x6c, 0x4b, 0x36, 0xa6, 0x42, 0xe2, 0xf1,
	0x24, 0x01, 0x3c, 0xfd, 0x23, 0x07, 0x0a, 0x2d, 0x3d, 0x60, 0x97, 0x0b, 0x26, 0x19, 0x0f, 0x61,
	0x19, 0xe4, 0x26, 0xfa, 0xd9, 0x63, 0x04, 0x19, 0x15, 0xa3, 0x9a, 0x75, 0x41, 0x1a, 0x72, 0x08,
	0x3c, 0x04, 0x0f, 0x27, 0x9c, 0x07, 0x71, 0xf2, 0x81, 0x4a, 0x6e, 0xc7, 0xaf, 0x0e, 0x81, 0x5f,
	0x80, 0xec, 0x54, 0xd0, 0x08, 0x6d, 0x55, 0x8c, 0xea, 0x6e, 0x0d, 0xbd, 0x7b, 0x7d, 0x5a, 0xd4,
	0xf3, 0x5c, 0x12, 0x12, 0x51, 0x21, 0x7a, 0x32, 0x62, 0xe1, 0xd0, 0x55, 0x28, 0x58, 0x03, 0xdb,
	0x42, 0x62, 0x39, 0x15, 0x28, 0x5b, 0x31, 0xaa, 0xf9, 0xf3, 0x13, 0xeb, 0x7e, 0x6d, 0xac, 0x74,
	0xba, 0x9e, 0x62, 0xb8, 0x9a, 0x09, 0xbf, 0x04, 0x3b, 0x03, 0x1e, 0x45, 0xfc, 0x9a, 0x12, 0xf4,
	0xbf, 0x8a, 0x51, 0xcd, 0x9d, 0x1f, 0x59, 0xba, 0x65, 0xac, 0x97, 0xa5, 0xf5, 0xb2, 0xea, 0x9c,
	0x85, 0xb5, 0xec, 0x9b, 0xbf, 0xca, 0x19, 0x77, 0x4e, 0x80, 0x17, 0x20, 0x3b, 0xa2, 0x01, 0x41,
	0xdb, 0x9b, 0x11, 0x15, 0x18, 0x7e, 0x0d, 0x80, 0xcf, 0x83, 0x00, 0x4b, 0x1a, 0xe1, 0x00, 0x3d,
	0xdc, 0x8c, 0xba, 0x44, 0x81, 0x9f, 0x82, 0xbc, 0x1f, 0x51, 0x2c, 0x29, 0xf1, 0x46, 0x94, 0x0d,
	0x47, 0x12, 0xed, 0x28, 0x11, 0xf7, 0x75, 0xf4, 0x7b, 0x15, 0x84, 0x75, 0xb0, 0x97, 0xc2, 0x62,
	0xd7, 0xd0, 0xae, 0xea, 0x54, 0xb2, 0x12, 0x4b, 0xad, 0xd4, 0x52, 0xab, 0x9f, 0x5a, 0x5a, 0xcb,
	0xbe, 0x7a, 0x5f, 0x36, 0xdc, 0x9c, 0x66, 0xc5, 0x71, 0xd8, 0x01, 0x9f, 0x04, 0xec, 0x97, 0x29,
	0x23, 0x38, 0x71, 0x33, 0x64, 0x92, 0xe1, 0x80, 0xfd, 0x4a, 0x89, 0x37, 0x08, 0xb8, 0xff, 0x3c,
	0x9d, 0x00, 0xa8, 0x09, 0x3e, 0x5a, 0xc2, 0x3a, 0x0b, 0x68, 0x2d, 0x46, 0xea, 0xa9, 0x7e, 0x02,
	0x70, 0xb9, 0xa0, 0xf6, 0x2f, 0xa7, 0xfc, 0x3b, 0xfd, 0x2f, 0xff, 0x5a, 0x0b, 0x96, 0xb6, 0xf0,
	0x20, 0x58, 0x0d, 0xc1, 0x1f, 0x40, 0x01, 0xfb, 0x7e, 0x34, 0xa5, 0xc4, 0x63, 0xa1, 0xa4, 0x11,
	0x15, 0x12, 0xed, 0x6d, 0xa6, 0xf0, 0xff, 0x35, 0xd1, 0xd1, 0xbc, 0x58, 0xe6, 0xe9, 0x84, 0x2c,
	0xcb, 0xbc, 0x9f, 0xc8, 0xac, 0xa3, 0x0b, 0x99, 0x53, 0x98, 0x92, 0x39, 0xbf, 0xa9, 0xcc, 0x9a,
	0xa5, 0x64, 0x9e, 0x81, 0xfd, 0x74, 0x5e, 0x2f, 0xc2, 0x92, 0xa2, 0x47, 0x95, 0xad, 0x6a, 0xee,
	0xfc, 0xf1, 0xda, 0xa1, 0x1b, 0xd4, 0x57, 0x73, 0x5f, 0xc4, 0x73, 0xff, 0xfe, 0xbe, 0xfc, 0xf9,
	0x90, 0xc9, 0xd1, 0x74, 0x60, 0xf9, 0x7c, 0xac, 0xaf, 0x57, 0xff, 0x9c, 0x0a, 0xf2, 0xdc, 0x96,
	0x2f, 0x27, 0x54, 0xa4, 0x1c, 0xe1, 0xee, 0xa5, 0x7d, 0x5c, 0x2c, 0x29, 0xfc, 0x06, 0x14, 0xc7,
	0x2c, 0xf4, 0x16, 0xcb, 0x15, 0x77, 0x67, 0x1c, 0x1d, 0xaa, 0xfb, 0xcb, 0xbf, 0x7b, 0x7d, 0x0a,
	0xf4, 0x04, 0x0d, 0xea, 0xbb, 0x70, 0xcc, 0xc2, 0xfa, 0x1c, 0xea, 0xc6, 0x48, 0x58, 0x07, 0x1f,
	0x2e, 0xfb, 0x29, 0x47, 0x11, 0x15, 0x23, 0x1e, 0x10, 0x84, 0xd6, 0x96, 0x28, 0x2e, 0x81, 0xfb,
	0x29, 0x36, 0xb6, 0x4d, 0x6f, 0x96, 0x37, 0x3f, 0xc6, 0xa3, 0x0d, 0x6d, 0xd3, 0xc4, 0x5a, 0x7a,
	0x93, 0x1d, 0xf0, 0x81, 0xe4, 0x12, 0x07, 0xf3, 0x05, 0xf0, 0x26, 0x98, 0x11, 0x54, 0xda, 0xac,
	0xdc, 0x81, 0xe2, 0xa6, 0x3b, 0xd0, 0xc5, 0x8c, 0x40, 0x1f, 0x3c, 0x09, 0xb0, 0x90, 0x8b, 0x7a,
	0x82, 0x4a, 0x19, 0xd0, 0x31, 0x0d, 0x65, 0xe2, 0xf8, 0xf1, 0x86, 0x8e, 0x97, 0xe2, 0x32, 0x69,
	0xe9, 0xde, 0xbc, 0x88, 0x5a, 0x80, 0x16, 0x28, 0xad, 0x2e, 0xae, 0x17, 0xd1, 0x31, 0x66, 0x21,
	0xa1, 0x11, 0x7a, 0xbc, 0x56, 0x4b, 0xb4, 0xb2, 0xb1, 0x6e, 0x8a, 0x87, 0xc7, 0x60, 0x57, 0x46,
	0x98, 0x50, 0x8f, 0x11, 0x81, 0x9e, 0x54, 0xb6, 0xaa, 0x59, 0x77, 0x47, 0x05, 0x1c, 0x22, 0x4e,
	0x5e, 0x80, 0x83, 0x7f, 0xdd, 0x12, 0x7c, 0x0a, 0xcc, 0x96, 0xf3, 0xe3, 0x95, 0xd3, 0xb8, 0xec,
	0x3b, 0x9d, 0xb6, 0xd7, 0xeb, 0x5f, 0xf6, 0xaf, 0x7a, 0xde, 0x55, 0xbb, 0xd7, 0x6d, 0xd6, 0x9d,
	0x6f, 0x9d, 0x66, 0xa3, 0x90, 0x81, 0xc7, 0xe0, 0x70, 0x0d, 0xa6, 0xdd, 0x69, 0x37, 0x0b, 0xc6,
	0x3d, 0x05, 0x9c, 0xb6, 0xd3, 0x77, 0x2e, 0x5b, 0xce, 0xb3, 0x66, 0xa3, 0xf0, 0xe0, 0xe4, 0x37,
	0x03, 0xe4, 0xef, 0x7e, 0x86, 0x61, 0x19, 0x1c, 0x77, 0x3b, 0x3d, 0xe7, 0xfe, 0xa6, 0x08, 0x14,
	0x57, 0x01, 0x9d, 0x6e, 0xb3, 0x5d, 0x30, 0x60, 0x09, 0x3c, 0x5a, 0xcd, 0xd4, 0x5b, 0x9d, 0x5e,
	0xdc, 0x69, 0x5d, 0xd9, 0xf9, 0x74, 0xed, 0xef, 0x0a, 0x5b, 0xd0, 0x04, 0xa5, 0xfb, 0x00, 0xcd,
	0x46, 0x21, 0x5b, 0xfb, 0xea, 0xcd, 0x8d, 0x69, 0xbc, 0xbd, 0x31, 0x8d, 0xbf, 0x6f, 0x4c, 0xe3,
	0xd5, 0xad, 0x99, 0x79, 0x7b, 0x6b, 0x66, 0xfe, 0xbc, 0x35, 0x33, 0xcf, 0x3e, 0xbe, 0xfb, 0x8d,
	0x8a, 0x8f, 0xee, 0xc5, 0xd2, 0x1f, 0xb6, 0x3a, 0xb7, 0xc1, 0xb6, 0xca, 0x5f, 0xfc, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x2b, 0x73, 0x24, 0x79, 0xd8, 0x07, 0x00, 0x00,
}

func (m *LeveragePosition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LeveragePosition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LeveragePosition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TradeIds) > 0 {
		dAtA2 := make([]byte, len(m.TradeIds)*10)
		var j1 int
		for _, num := range m.TradeIds {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintLeverage(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xea
	}
	if len(m.AccruedInterestRemainder) > 0 {
		i -= len(m.AccruedInterestRemainder)
		copy(dAtA[i:], m.AccruedInterestRemainder)
		i = encodeVarintLeverage(dAtA, i, uint64(len(m.AccruedInterestRemainder)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe2
	}
	if m.LastInterestSettlementTime != nil {
		n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.LastInterestSettlementTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastInterestSettlementTime):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintLeverage(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xda
	}
	{
		size, err := m.TotalInterestPaid.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xd2
	{
		size, err := m.InitialBorrowed.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xca
	if len(m.LiquidationThreshold) > 0 {
		i -= len(m.LiquidationThreshold)
		copy(dAtA[i:], m.LiquidationThreshold)
		i = encodeVarintLeverage(dAtA, i, uint64(len(m.LiquidationThreshold)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc2
	}
	if len(m.MinCollateralRatio) > 0 {
		i -= len(m.MinCollateralRatio)
		copy(dAtA[i:], m.MinCollateralRatio)
		i = encodeVarintLeverage(dAtA, i, uint64(len(m.MinCollateralRatio)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xba
	}
	if len(m.InterestRate) > 0 {
		for iNdEx := len(m.InterestRate) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InterestRate[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLeverage(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xb2
		}
	}
	if m.UpdatedTime != nil {
		n6, err6 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.UpdatedTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.UpdatedTime):])
		if err6 != nil {
			return 0, err6
		}
		i -= n6
		i = encodeVarintLeverage(dAtA, i, uint64(n6))
		i--
		dAtA[i] = 0x72
	}
	if m.UpdatedHeight != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.UpdatedHeight))
		i--
		dAtA[i] = 0x68
	}
	{
		size, err := m.AccruedInterest.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if m.LiquidationStatus != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.LiquidationStatus))
		i--
		dAtA[i] = 0x58
	}
	if m.LiquidationInitializedBlockHeight != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.LiquidationInitializedBlockHeight))
		i--
		dAtA[i] = 0x50
	}
	if m.CreatedTime != nil {
		n8, err8 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.CreatedTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.CreatedTime):])
		if err8 != nil {
			return 0, err8
		}
		i -= n8
		i = encodeVarintLeverage(dAtA, i, uint64(n8))
		i--
		dAtA[i] = 0x4a
	}
	if m.CreatedHeight != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.CreatedHeight))
		i--
		dAtA[i] = 0x40
	}
	{
		size, err := m.Collateral.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.Held.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.Borrowed.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Status != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if len(m.User) > 0 {
		i -= len(m.User)
		copy(dAtA[i:], m.User)
		i = encodeVarintLeverage(dAtA, i, uint64(len(m.User)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PoolId != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x10
	}
	if m.PositionId != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.PositionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLeverage(dAtA []byte, offset int, v uint64) int {
	offset -= sovLeverage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LeveragePosition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PositionId != 0 {
		n += 1 + sovLeverage(uint64(m.PositionId))
	}
	if m.PoolId != 0 {
		n += 1 + sovLeverage(uint64(m.PoolId))
	}
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovLeverage(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovLeverage(uint64(m.Status))
	}
	l = m.Borrowed.Size()
	n += 1 + l + sovLeverage(uint64(l))
	l = m.Held.Size()
	n += 1 + l + sovLeverage(uint64(l))
	l = m.Collateral.Size()
	n += 1 + l + sovLeverage(uint64(l))
	if m.CreatedHeight != 0 {
		n += 1 + sovLeverage(uint64(m.CreatedHeight))
	}
	if m.CreatedTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.CreatedTime)
		n += 1 + l + sovLeverage(uint64(l))
	}
	if m.LiquidationInitializedBlockHeight != 0 {
		n += 1 + sovLeverage(uint64(m.LiquidationInitializedBlockHeight))
	}
	if m.LiquidationStatus != 0 {
		n += 1 + sovLeverage(uint64(m.LiquidationStatus))
	}
	l = m.AccruedInterest.Size()
	n += 1 + l + sovLeverage(uint64(l))
	if m.UpdatedHeight != 0 {
		n += 1 + sovLeverage(uint64(m.UpdatedHeight))
	}
	if m.UpdatedTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.UpdatedTime)
		n += 1 + l + sovLeverage(uint64(l))
	}
	if len(m.InterestRate) > 0 {
		for _, e := range m.InterestRate {
			l = e.Size()
			n += 2 + l + sovLeverage(uint64(l))
		}
	}
	l = len(m.MinCollateralRatio)
	if l > 0 {
		n += 2 + l + sovLeverage(uint64(l))
	}
	l = len(m.LiquidationThreshold)
	if l > 0 {
		n += 2 + l + sovLeverage(uint64(l))
	}
	l = m.InitialBorrowed.Size()
	n += 2 + l + sovLeverage(uint64(l))
	l = m.TotalInterestPaid.Size()
	n += 2 + l + sovLeverage(uint64(l))
	if m.LastInterestSettlementTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastInterestSettlementTime)
		n += 2 + l + sovLeverage(uint64(l))
	}
	l = len(m.AccruedInterestRemainder)
	if l > 0 {
		n += 2 + l + sovLeverage(uint64(l))
	}
	if len(m.TradeIds) > 0 {
		l = 0
		for _, e := range m.TradeIds {
			l += sovLeverage(uint64(e))
		}
		n += 2 + sovLeverage(uint64(l)) + l
	}
	return n
}

func sovLeverage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLeverage(x uint64) (n int) {
	return sovLeverage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LeveragePosition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLeverage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LeveragePosition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LeveragePosition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PositionId", wireType)
			}
			m.PositionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PositionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PositionStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Borrowed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Borrowed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Held", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Held.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Collateral.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedHeight", wireType)
			}
			m.CreatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedTime == nil {
				m.CreatedTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.CreatedTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationInitializedBlockHeight", wireType)
			}
			m.LiquidationInitializedBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidationInitializedBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationStatus", wireType)
			}
			m.LiquidationStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidationStatus |= LiquidationStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccruedInterest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AccruedInterest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedHeight", wireType)
			}
			m.UpdatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedTime == nil {
				m.UpdatedTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.UpdatedTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InterestRate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InterestRate = append(m.InterestRate, types.DecCoin{})
			if err := m.InterestRate[len(m.InterestRate)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCollateralRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinCollateralRatio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 24:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidationThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialBorrowed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialBorrowed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 26:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalInterestPaid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalInterestPaid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 27:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastInterestSettlementTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastInterestSettlementTime == nil {
				m.LastInterestSettlementTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.LastInterestSettlementTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 28:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccruedInterestRemainder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccruedInterestRemainder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 29:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLeverage
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.TradeIds = append(m.TradeIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLeverage
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthLeverage
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthLeverage
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.TradeIds) == 0 {
					m.TradeIds = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLeverage
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.TradeIds = append(m.TradeIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeIds", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLeverage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLeverage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLeverage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLeverage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLeverage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLeverage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLeverage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLeverage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLeverage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLeverage = fmt.Errorf("proto: unexpected end of group")
)
