// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dysonprotocol/whaleswap/v1/leverage.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LiquidationStatus int32

const (
	LiquidationStatus_LIQUIDATION_STATUS_UNSPECIFIED LiquidationStatus = 0
	LiquidationStatus_LIQUIDATION_STATUS_NONE        LiquidationStatus = 1
	LiquidationStatus_LIQUIDATION_STATUS_INITIALIZED LiquidationStatus = 2
)

var LiquidationStatus_name = map[int32]string{
	0: "LIQUIDATION_STATUS_UNSPECIFIED",
	1: "LIQUIDATION_STATUS_NONE",
	2: "LIQUIDATION_STATUS_INITIALIZED",
}

var LiquidationStatus_value = map[string]int32{
	"LIQUIDATION_STATUS_UNSPECIFIED": 0,
	"LIQUIDATION_STATUS_NONE":        1,
	"LIQUIDATION_STATUS_INITIALIZED": 2,
}

func (x LiquidationStatus) String() string {
	return proto.EnumName(LiquidationStatus_name, int32(x))
}

func (LiquidationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef2aed91e4083e34, []int{0}
}

type PositionStatus int32

const (
	PositionStatus_POSITION_STATUS_UNSPECIFIED PositionStatus = 0
	PositionStatus_POSITION_STATUS_OPEN        PositionStatus = 1
	PositionStatus_POSITION_STATUS_CLOSED      PositionStatus = 2
	PositionStatus_POSITION_STATUS_LIQUIDATING PositionStatus = 3
	PositionStatus_POSITION_STATUS_LIQUIDATED  PositionStatus = 4
)

var PositionStatus_name = map[int32]string{
	0: "POSITION_STATUS_UNSPECIFIED",
	1: "POSITION_STATUS_OPEN",
	2: "POSITION_STATUS_CLOSED",
	3: "POSITION_STATUS_LIQUIDATING",
	4: "POSITION_STATUS_LIQUIDATED",
}

var PositionStatus_value = map[string]int32{
	"POSITION_STATUS_UNSPECIFIED": 0,
	"POSITION_STATUS_OPEN":        1,
	"POSITION_STATUS_CLOSED":      2,
	"POSITION_STATUS_LIQUIDATING": 3,
	"POSITION_STATUS_LIQUIDATED":  4,
}

func (x PositionStatus) String() string {
	return proto.EnumName(PositionStatus_name, int32(x))
}

func (PositionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef2aed91e4083e34, []int{1}
}

// LeveragePosition represents an active leverage position for a trader.
type LeveragePosition struct {
	PositionId                        uint64            `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	PoolId                            uint64            `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	User                              string            `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Status                            PositionStatus    `protobuf:"varint,4,opt,name=status,proto3,enum=dysonprotocol.whaleswap.v1.PositionStatus" json:"status,omitempty"`
	Borrowed                          types.Coin        `protobuf:"bytes,5,opt,name=borrowed,proto3" json:"borrowed"`
	Held                              types.Coin        `protobuf:"bytes,6,opt,name=held,proto3" json:"held"`
	Collateral                        types.Coin        `protobuf:"bytes,7,opt,name=collateral,proto3" json:"collateral"`
	BorrowTime                        *time.Time        `protobuf:"bytes,8,opt,name=borrow_time,json=borrowTime,proto3,stdtime" json:"borrow_time,omitempty"`
	CreatedBlockHeight                uint64            `protobuf:"varint,9,opt,name=created_block_height,json=createdBlockHeight,proto3" json:"created_block_height,omitempty"`
	LiquidationInitializedBlockHeight uint64            `protobuf:"varint,10,opt,name=liquidation_initialized_block_height,json=liquidationInitializedBlockHeight,proto3" json:"liquidation_initialized_block_height,omitempty"`
	LiquidationStatus                 LiquidationStatus `protobuf:"varint,11,opt,name=liquidation_status,json=liquidationStatus,proto3,enum=dysonprotocol.whaleswap.v1.LiquidationStatus" json:"liquidation_status,omitempty"`
	AccruedInterest                   types.Coin        `protobuf:"bytes,12,opt,name=accrued_interest,json=accruedInterest,proto3" json:"accrued_interest"`
	// ═════ PER-POSITION SNAPSHOTS (sticky to this position) ═════
	// Annual interest rates per reserve denom (exactly two, canonical order).
	// Each amount is a LegacyDec string representing APR (per-year accrual).
	InterestRate github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,22,rep,name=interest_rate,json=interestRate,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"interest_rate"`
	// Minimum collateral ratio used for health/liquidation checks (cosmos.Dec
	// string).
	MinCollateralRatio string `protobuf:"bytes,23,opt,name=min_collateral_ratio,json=minCollateralRatio,proto3" json:"min_collateral_ratio,omitempty"`
	// Liquidation threshold used for liquidation checks (cosmos.Dec string).
	LiquidationThreshold string `protobuf:"bytes,24,opt,name=liquidation_threshold,json=liquidationThreshold,proto3" json:"liquidation_threshold,omitempty"`
}

func (m *LeveragePosition) Reset()         { *m = LeveragePosition{} }
func (m *LeveragePosition) String() string { return proto.CompactTextString(m) }
func (*LeveragePosition) ProtoMessage()    {}
func (*LeveragePosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef2aed91e4083e34, []int{0}
}
func (m *LeveragePosition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LeveragePosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LeveragePosition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LeveragePosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeveragePosition.Merge(m, src)
}
func (m *LeveragePosition) XXX_Size() int {
	return m.Size()
}
func (m *LeveragePosition) XXX_DiscardUnknown() {
	xxx_messageInfo_LeveragePosition.DiscardUnknown(m)
}

var xxx_messageInfo_LeveragePosition proto.InternalMessageInfo

func (m *LeveragePosition) GetPositionId() uint64 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

func (m *LeveragePosition) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *LeveragePosition) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *LeveragePosition) GetStatus() PositionStatus {
	if m != nil {
		return m.Status
	}
	return PositionStatus_POSITION_STATUS_UNSPECIFIED
}

func (m *LeveragePosition) GetBorrowed() types.Coin {
	if m != nil {
		return m.Borrowed
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetHeld() types.Coin {
	if m != nil {
		return m.Held
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetCollateral() types.Coin {
	if m != nil {
		return m.Collateral
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetBorrowTime() *time.Time {
	if m != nil {
		return m.BorrowTime
	}
	return nil
}

func (m *LeveragePosition) GetCreatedBlockHeight() uint64 {
	if m != nil {
		return m.CreatedBlockHeight
	}
	return 0
}

func (m *LeveragePosition) GetLiquidationInitializedBlockHeight() uint64 {
	if m != nil {
		return m.LiquidationInitializedBlockHeight
	}
	return 0
}

func (m *LeveragePosition) GetLiquidationStatus() LiquidationStatus {
	if m != nil {
		return m.LiquidationStatus
	}
	return LiquidationStatus_LIQUIDATION_STATUS_UNSPECIFIED
}

func (m *LeveragePosition) GetAccruedInterest() types.Coin {
	if m != nil {
		return m.AccruedInterest
	}
	return types.Coin{}
}

func (m *LeveragePosition) GetInterestRate() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.InterestRate
	}
	return nil
}

func (m *LeveragePosition) GetMinCollateralRatio() string {
	if m != nil {
		return m.MinCollateralRatio
	}
	return ""
}

func (m *LeveragePosition) GetLiquidationThreshold() string {
	if m != nil {
		return m.LiquidationThreshold
	}
	return ""
}

func init() {
	proto.RegisterEnum("dysonprotocol.whaleswap.v1.LiquidationStatus", LiquidationStatus_name, LiquidationStatus_value)
	proto.RegisterEnum("dysonprotocol.whaleswap.v1.PositionStatus", PositionStatus_name, PositionStatus_value)
	proto.RegisterType((*LeveragePosition)(nil), "dysonprotocol.whaleswap.v1.LeveragePosition")
}

func init() {
	proto.RegisterFile("dysonprotocol/whaleswap/v1/leverage.proto", fileDescriptor_ef2aed91e4083e34)
}

var fileDescriptor_ef2aed91e4083e34 = []byte{
	// 760 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcf, 0x52, 0xc3, 0x44,
	0x18, 0x6f, 0xa0, 0x16, 0xd8, 0x22, 0x86, 0x9d, 0x0a, 0xa1, 0x38, 0x69, 0x45, 0x0f, 0x15, 0x6d,
	0x62, 0xe1, 0xe8, 0x38, 0xda, 0x7f, 0x6a, 0x9c, 0x4e, 0x5b, 0xd3, 0x72, 0x61, 0x9c, 0xc9, 0xa4,
	0xc9, 0x9a, 0xee, 0x90, 0x66, 0x6b, 0x76, 0x5b, 0xc0, 0xa7, 0xe0, 0x31, 0x1c, 0xcf, 0x3c, 0x04,
	0x47, 0x86, 0x93, 0x27, 0x61, 0xe0, 0x45, 0x9c, 0x6c, 0x36, 0xa5, 0xd4, 0xd6, 0xe1, 0x94, 0xdd,
	0xfd, 0xfd, 0xf9, 0xbe, 0xf9, 0x7e, 0xbb, 0x01, 0x5f, 0xb8, 0xd7, 0x94, 0x04, 0xe3, 0x90, 0x30,
	0xe2, 0x10, 0x5f, 0xbf, 0x1c, 0xda, 0x3e, 0xa2, 0x97, 0xf6, 0x58, 0x9f, 0x56, 0x74, 0x1f, 0x4d,
	0x51, 0x68, 0x7b, 0x48, 0xe3, 0x30, 0xcc, 0xbf, 0xa1, 0x6a, 0x33, 0xaa, 0x36, 0xad, 0xe4, 0x73,
	0x1e, 0xf1, 0x08, 0x87, 0xf4, 0x68, 0x15, 0x2b, 0xf2, 0xaa, 0x43, 0xe8, 0x88, 0x50, 0x7d, 0x60,
	0x53, 0xa4, 0x4f, 0x2b, 0x03, 0xc4, 0xec, 0x8a, 0xee, 0x10, 0x1c, 0x08, 0xfc, 0x20, 0xc6, 0xad,
	0x58, 0x18, 0x6f, 0x04, 0x54, 0xf0, 0x08, 0xf1, 0x7c, 0xa4, 0xf3, 0xdd, 0x60, 0xf2, 0x9b, 0xce,
	0xf0, 0x08, 0x51, 0x66, 0x8f, 0xc6, 0x31, 0xe1, 0xe8, 0x69, 0x03, 0xc8, 0x2d, 0xd1, 0x60, 0x97,
	0x50, 0xcc, 0x30, 0x09, 0x60, 0x01, 0x64, 0xc7, 0x62, 0x6d, 0x61, 0x57, 0x91, 0x8a, 0x52, 0x29,
	0x6d, 0x82, 0xe4, 0xc8, 0x70, 0xe1, 0x3e, 0xd8, 0x18, 0x13, 0xe2, 0x47, 0xe0, 0x1a, 0x07, 0x33,
	0xd1, 0xd6, 0x70, 0xe1, 0x57, 0x20, 0x3d, 0xa1, 0x28, 0x54, 0xd6, 0x8b, 0x52, 0x69, 0xab, 0xa6,
	0x3c, 0xdc, 0x96, 0x73, 0xa2, 0x9f, 0xaa, 0xeb, 0x86, 0x88, 0xd2, 0x1e, 0x0b, 0x71, 0xe0, 0x99,
	0x9c, 0x05, 0x6b, 0x20, 0x43, 0x99, 0xcd, 0x26, 0x54, 0x49, 0x17, 0xa5, 0xd2, 0xce, 0xc9, 0xb1,
	0xb6, 0x7a, 0x36, 0x5a, 0xd2, 0x5d, 0x8f, 0x2b, 0x4c, 0xa1, 0x84, 0xdf, 0x80, 0xcd, 0x01, 0x09,
	0x43, 0x72, 0x89, 0x5c, 0xe5, 0x83, 0xa2, 0x54, 0xca, 0x9e, 0x1c, 0x68, 0xa2, 0x64, 0x34, 0x2f,
	0x4d, 0xcc, 0x4b, 0xab, 0x13, 0x1c, 0xd4, 0xd2, 0x77, 0xff, 0x14, 0x52, 0xe6, 0x4c, 0x00, 0x4f,
	0x41, 0x7a, 0x88, 0x7c, 0x57, 0xc9, 0xbc, 0x4f, 0xc8, 0xc9, 0xf0, 0x3b, 0x00, 0x1c, 0xe2, 0xfb,
	0x36, 0x43, 0xa1, 0xed, 0x2b, 0x1b, 0xef, 0x93, 0xce, 0x49, 0x60, 0x15, 0x64, 0xe3, 0x0e, 0xac,
	0x28, 0x0d, 0x65, 0x93, 0x3b, 0xe4, 0xb5, 0x38, 0x2a, 0x2d, 0x89, 0x4a, 0xeb, 0x27, 0x51, 0xd5,
	0xd2, 0x37, 0x8f, 0x05, 0xc9, 0x04, 0xb1, 0x28, 0x3a, 0x86, 0x5f, 0x83, 0x9c, 0x13, 0x22, 0x9b,
	0x21, 0xd7, 0x1a, 0xf8, 0xc4, 0xb9, 0xb0, 0x86, 0x08, 0x7b, 0x43, 0xa6, 0x6c, 0xf1, 0x34, 0xa0,
	0xc0, 0x6a, 0x11, 0xf4, 0x13, 0x47, 0x60, 0x07, 0x7c, 0xee, 0xe3, 0xdf, 0x27, 0xd8, 0xb5, 0xe3,
	0x58, 0x03, 0xcc, 0xb0, 0xed, 0xe3, 0x3f, 0x16, 0x1d, 0x00, 0x77, 0xf8, 0x74, 0x8e, 0x6b, 0xbc,
	0x52, 0xe7, 0x0d, 0x7f, 0x05, 0x70, 0xde, 0x50, 0x04, 0x99, 0xe5, 0x41, 0x96, 0xff, 0x2f, 0xc8,
	0xd6, 0xab, 0x4a, 0x64, 0xb9, 0xeb, 0x2f, 0x1e, 0xc1, 0x9f, 0x81, 0x6c, 0x3b, 0x4e, 0x38, 0x41,
	0xae, 0x85, 0x03, 0x86, 0x42, 0x44, 0x99, 0xb2, 0xfd, 0xbe, 0x51, 0x7f, 0x24, 0x84, 0x86, 0xd0,
	0xc1, 0x29, 0xf8, 0x30, 0xf1, 0xb0, 0x42, 0x9b, 0x21, 0x65, 0xaf, 0xb8, 0x5e, 0xca, 0x9e, 0x7c,
	0xb2, 0xd4, 0xa8, 0x81, 0x1c, 0xee, 0x75, 0x1a, 0x79, 0xfd, 0xf5, 0x58, 0xf8, 0xd2, 0xc3, 0x6c,
	0x38, 0x19, 0x68, 0x0e, 0x19, 0x89, 0xa7, 0x25, 0x3e, 0x65, 0xea, 0x5e, 0xe8, 0xec, 0x7a, 0x8c,
	0x68, 0xa2, 0xa1, 0xe6, 0x76, 0x52, 0xc7, 0xb4, 0x19, 0x82, 0xdf, 0x83, 0xdc, 0x08, 0x07, 0xd6,
	0x6b, 0xf2, 0x51, 0x75, 0x4c, 0x94, 0x7d, 0xfe, 0x38, 0x76, 0x1e, 0x6e, 0xcb, 0x40, 0x74, 0xd0,
	0x40, 0x8e, 0x09, 0x47, 0x38, 0xa8, 0xcf, 0xa8, 0x66, 0xc4, 0x84, 0x75, 0xf0, 0xf1, 0xfc, 0x8c,
	0xd9, 0x30, 0x44, 0x74, 0x48, 0x7c, 0x57, 0x51, 0x96, 0x5a, 0xe4, 0xe6, 0xc8, 0xfd, 0x84, 0x7b,
	0x7c, 0x05, 0x76, 0xff, 0x33, 0x72, 0x78, 0x04, 0xd4, 0x96, 0xf1, 0xcb, 0x99, 0xd1, 0xa8, 0xf6,
	0x8d, 0x4e, 0xdb, 0xea, 0xf5, 0xab, 0xfd, 0xb3, 0x9e, 0x75, 0xd6, 0xee, 0x75, 0x9b, 0x75, 0xe3,
	0x07, 0xa3, 0xd9, 0x90, 0x53, 0xf0, 0x10, 0xec, 0x2f, 0xe1, 0xb4, 0x3b, 0xed, 0xa6, 0x2c, 0xad,
	0x30, 0x30, 0xda, 0x46, 0xdf, 0xa8, 0xb6, 0x8c, 0xf3, 0x66, 0x43, 0x5e, 0x3b, 0xfe, 0x53, 0x02,
	0x3b, 0x6f, 0x9f, 0x2d, 0x2c, 0x80, 0xc3, 0x6e, 0xa7, 0x67, 0xac, 0x2e, 0xaa, 0x80, 0xdc, 0x22,
	0xa1, 0xd3, 0x6d, 0xb6, 0x65, 0x09, 0xe6, 0xc1, 0xde, 0x22, 0x52, 0x6f, 0x75, 0x7a, 0x51, 0xa5,
	0x65, 0xb6, 0xb3, 0xee, 0xda, 0x3f, 0xca, 0xeb, 0x50, 0x05, 0xf9, 0x55, 0x84, 0x66, 0x43, 0x4e,
	0xd7, 0xbe, 0xbd, 0x7b, 0x56, 0xa5, 0xfb, 0x67, 0x55, 0x7a, 0x7a, 0x56, 0xa5, 0x9b, 0x17, 0x35,
	0x75, 0xff, 0xa2, 0xa6, 0xfe, 0x7e, 0x51, 0x53, 0xe7, 0x9f, 0xbd, 0xbd, 0xca, 0xd1, 0x3d, 0xb8,
	0x9a, 0xfb, 0xc1, 0xf3, 0x1b, 0x30, 0xc8, 0x70, 0xfc, 0xf4, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa3, 0xc5, 0xd8, 0xd3, 0x08, 0x06, 0x00, 0x00,
}

func (m *LeveragePosition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LeveragePosition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LeveragePosition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LiquidationThreshold) > 0 {
		i -= len(m.LiquidationThreshold)
		copy(dAtA[i:], m.LiquidationThreshold)
		i = encodeVarintLeverage(dAtA, i, uint64(len(m.LiquidationThreshold)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc2
	}
	if len(m.MinCollateralRatio) > 0 {
		i -= len(m.MinCollateralRatio)
		copy(dAtA[i:], m.MinCollateralRatio)
		i = encodeVarintLeverage(dAtA, i, uint64(len(m.MinCollateralRatio)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xba
	}
	if len(m.InterestRate) > 0 {
		for iNdEx := len(m.InterestRate) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InterestRate[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLeverage(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xb2
		}
	}
	{
		size, err := m.AccruedInterest.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if m.LiquidationStatus != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.LiquidationStatus))
		i--
		dAtA[i] = 0x58
	}
	if m.LiquidationInitializedBlockHeight != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.LiquidationInitializedBlockHeight))
		i--
		dAtA[i] = 0x50
	}
	if m.CreatedBlockHeight != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.CreatedBlockHeight))
		i--
		dAtA[i] = 0x48
	}
	if m.BorrowTime != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.BorrowTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.BorrowTime):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintLeverage(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x42
	}
	{
		size, err := m.Collateral.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.Held.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.Borrowed.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLeverage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Status != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if len(m.User) > 0 {
		i -= len(m.User)
		copy(dAtA[i:], m.User)
		i = encodeVarintLeverage(dAtA, i, uint64(len(m.User)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PoolId != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x10
	}
	if m.PositionId != 0 {
		i = encodeVarintLeverage(dAtA, i, uint64(m.PositionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLeverage(dAtA []byte, offset int, v uint64) int {
	offset -= sovLeverage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LeveragePosition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PositionId != 0 {
		n += 1 + sovLeverage(uint64(m.PositionId))
	}
	if m.PoolId != 0 {
		n += 1 + sovLeverage(uint64(m.PoolId))
	}
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovLeverage(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovLeverage(uint64(m.Status))
	}
	l = m.Borrowed.Size()
	n += 1 + l + sovLeverage(uint64(l))
	l = m.Held.Size()
	n += 1 + l + sovLeverage(uint64(l))
	l = m.Collateral.Size()
	n += 1 + l + sovLeverage(uint64(l))
	if m.BorrowTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.BorrowTime)
		n += 1 + l + sovLeverage(uint64(l))
	}
	if m.CreatedBlockHeight != 0 {
		n += 1 + sovLeverage(uint64(m.CreatedBlockHeight))
	}
	if m.LiquidationInitializedBlockHeight != 0 {
		n += 1 + sovLeverage(uint64(m.LiquidationInitializedBlockHeight))
	}
	if m.LiquidationStatus != 0 {
		n += 1 + sovLeverage(uint64(m.LiquidationStatus))
	}
	l = m.AccruedInterest.Size()
	n += 1 + l + sovLeverage(uint64(l))
	if len(m.InterestRate) > 0 {
		for _, e := range m.InterestRate {
			l = e.Size()
			n += 2 + l + sovLeverage(uint64(l))
		}
	}
	l = len(m.MinCollateralRatio)
	if l > 0 {
		n += 2 + l + sovLeverage(uint64(l))
	}
	l = len(m.LiquidationThreshold)
	if l > 0 {
		n += 2 + l + sovLeverage(uint64(l))
	}
	return n
}

func sovLeverage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLeverage(x uint64) (n int) {
	return sovLeverage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LeveragePosition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLeverage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LeveragePosition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LeveragePosition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PositionId", wireType)
			}
			m.PositionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PositionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PositionStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Borrowed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Borrowed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Held", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Held.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Collateral.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BorrowTime == nil {
				m.BorrowTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.BorrowTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedBlockHeight", wireType)
			}
			m.CreatedBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationInitializedBlockHeight", wireType)
			}
			m.LiquidationInitializedBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidationInitializedBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationStatus", wireType)
			}
			m.LiquidationStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidationStatus |= LiquidationStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccruedInterest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AccruedInterest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InterestRate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InterestRate = append(m.InterestRate, types.DecCoin{})
			if err := m.InterestRate[len(m.InterestRate)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCollateralRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinCollateralRatio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 24:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLeverage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLeverage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidationThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLeverage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLeverage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLeverage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLeverage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLeverage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLeverage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLeverage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLeverage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLeverage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLeverage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLeverage = fmt.Errorf("proto: unexpected end of group")
)
