// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dysonprotocol/whaleswap/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ArbitrageMode determines how the protocol handles arbitrage opportunities.
type ArbitrageMode int32

const (
	// ARBITRAGE_MODE_UNSPECIFIED defaults to AUTO for backwards compatibility.
	ArbitrageMode_ARBITRAGE_MODE_UNSPECIFIED ArbitrageMode = 0
	// ARBITRAGE_MODE_DISABLED completely disables arbitrage detection and
	// execution.
	ArbitrageMode_ARBITRAGE_MODE_DISABLED ArbitrageMode = 1
	// ARBITRAGE_MODE_MANUAL allows arbitrage queries/simulation but no automatic
	// execution.
	ArbitrageMode_ARBITRAGE_MODE_MANUAL ArbitrageMode = 2
	// ARBITRAGE_MODE_AUTO enables automatic arbitrage execution after trades.
	ArbitrageMode_ARBITRAGE_MODE_AUTO ArbitrageMode = 3
)

var ArbitrageMode_name = map[int32]string{
	0: "ARBITRAGE_MODE_UNSPECIFIED",
	1: "ARBITRAGE_MODE_DISABLED",
	2: "ARBITRAGE_MODE_MANUAL",
	3: "ARBITRAGE_MODE_AUTO",
}

var ArbitrageMode_value = map[string]int32{
	"ARBITRAGE_MODE_UNSPECIFIED": 0,
	"ARBITRAGE_MODE_DISABLED":    1,
	"ARBITRAGE_MODE_MANUAL":      2,
	"ARBITRAGE_MODE_AUTO":        3,
}

func (x ArbitrageMode) String() string {
	return proto.EnumName(ArbitrageMode_name, int32(x))
}

func (ArbitrageMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6afa625d503958c8, []int{0}
}

type Params struct {
	// pfand_per_offer is the PFAND coin required for liquid-mode offers.
	PfandPerOffer types.Coin `protobuf:"bytes,1,opt,name=pfand_per_offer,json=pfandPerOffer,proto3" json:"pfand_per_offer" yaml:"pfand_per_offer"`
	// valuation_fee_pct is the percentage applied per valuation_period.
	ValuationFeePct string `protobuf:"bytes,2,opt,name=valuation_fee_pct,json=valuationFeePct,proto3" json:"valuation_fee_pct,omitempty" yaml:"valuation_fee_pct"`
	// valuation_period defines the time duration to which valuation_fee_pct
	// applies.
	ValuationPeriod time.Duration `protobuf:"bytes,3,opt,name=valuation_period,json=valuationPeriod,proto3,stdduration" json:"valuation_period" yaml:"valuation_period"`
	// bid_timeout defines the minimum duration a placed bid must remain pending
	// before it can be claimed by the bidder.
	BidTimeout time.Duration `protobuf:"bytes,4,opt,name=bid_timeout,json=bidTimeout,proto3,stdduration" json:"bid_timeout" yaml:"bid_timeout"`
	// minimum_bid_percent_increase specifies the minimum percent increase
	// required over the current valuation for a new bid to be accepted.
	MinimumBidPercentIncrease string `protobuf:"bytes,5,opt,name=minimum_bid_percent_increase,json=minimumBidPercentIncrease,proto3" json:"minimum_bid_percent_increase,omitempty" yaml:"minimum_bid_percent_increase"`
	MaxNoteLength             uint32 `protobuf:"varint,6,opt,name=max_note_length,json=maxNoteLength,proto3" json:"max_note_length,omitempty" yaml:"max_note_length"`
	// ═════ LEVERAGE PARAMETERS ═════
	// Block delay before position owner can close position
	BlockDelayBeforeClose uint64 `protobuf:"varint,7,opt,name=block_delay_before_close,json=blockDelayBeforeClose,proto3" json:"block_delay_before_close,omitempty" yaml:"block_delay_before_close"`
	// Block delay before liquidation can be finalized after initialization
	BlockDelayBeforeLiquidation uint64 `protobuf:"varint,8,opt,name=block_delay_before_liquidation,json=blockDelayBeforeLiquidation,proto3" json:"block_delay_before_liquidation,omitempty" yaml:"block_delay_before_liquidation"`
	// ═════ ARBITRAGE PARAMETERS ═════
	// arbitrage_mode controls protocol arbitrage behavior.
	ArbitrageMode ArbitrageMode `protobuf:"varint,9,opt,name=arbitrage_mode,json=arbitrageMode,proto3,enum=dysonprotocol.whaleswap.v1.ArbitrageMode" json:"arbitrage_mode,omitempty" yaml:"arbitrage_mode"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6afa625d503958c8, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetPfandPerOffer() types.Coin {
	if m != nil {
		return m.PfandPerOffer
	}
	return types.Coin{}
}

func (m *Params) GetValuationFeePct() string {
	if m != nil {
		return m.ValuationFeePct
	}
	return ""
}

func (m *Params) GetValuationPeriod() time.Duration {
	if m != nil {
		return m.ValuationPeriod
	}
	return 0
}

func (m *Params) GetBidTimeout() time.Duration {
	if m != nil {
		return m.BidTimeout
	}
	return 0
}

func (m *Params) GetMinimumBidPercentIncrease() string {
	if m != nil {
		return m.MinimumBidPercentIncrease
	}
	return ""
}

func (m *Params) GetMaxNoteLength() uint32 {
	if m != nil {
		return m.MaxNoteLength
	}
	return 0
}

func (m *Params) GetBlockDelayBeforeClose() uint64 {
	if m != nil {
		return m.BlockDelayBeforeClose
	}
	return 0
}

func (m *Params) GetBlockDelayBeforeLiquidation() uint64 {
	if m != nil {
		return m.BlockDelayBeforeLiquidation
	}
	return 0
}

func (m *Params) GetArbitrageMode() ArbitrageMode {
	if m != nil {
		return m.ArbitrageMode
	}
	return ArbitrageMode_ARBITRAGE_MODE_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("dysonprotocol.whaleswap.v1.ArbitrageMode", ArbitrageMode_name, ArbitrageMode_value)
	proto.RegisterType((*Params)(nil), "dysonprotocol.whaleswap.v1.Params")
}

func init() {
	proto.RegisterFile("dysonprotocol/whaleswap/v1/params.proto", fileDescriptor_6afa625d503958c8)
}

var fileDescriptor_6afa625d503958c8 = []byte{
	// 691 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcf, 0x4e, 0xdb, 0x4a,
	0x14, 0xc6, 0x63, 0xe0, 0xc2, 0x65, 0x50, 0x20, 0xd7, 0xb7, 0x14, 0x27, 0x54, 0x76, 0xe4, 0xa8,
	0x6a, 0x40, 0xaa, 0xad, 0x50, 0x75, 0x53, 0xa9, 0x8b, 0x98, 0x84, 0x2a, 0x52, 0x80, 0xc8, 0x40,
	0x17, 0xa8, 0xd2, 0x68, 0x6c, 0x9f, 0x84, 0x11, 0xb6, 0xc7, 0xb5, 0x9d, 0x40, 0x76, 0xed, 0x1b,
	0x74, 0xd9, 0x07, 0xe9, 0x43, 0xb0, 0x44, 0x5d, 0x75, 0x95, 0x56, 0xf0, 0x06, 0x79, 0x82, 0xca,
	0x7f, 0x02, 0x89, 0x5b, 0xda, 0x5d, 0xce, 0xf9, 0x7e, 0xe7, 0x7c, 0x27, 0xdf, 0x28, 0x41, 0xcf,
	0xac, 0x61, 0xc0, 0x5c, 0xcf, 0x67, 0x21, 0x33, 0x99, 0xad, 0x5e, 0x9c, 0x11, 0x1b, 0x82, 0x0b,
	0xe2, 0xa9, 0x83, 0x9a, 0xea, 0x11, 0x9f, 0x38, 0x81, 0x12, 0x8b, 0x7c, 0x69, 0x06, 0x54, 0xee,
	0x40, 0x65, 0x50, 0x2b, 0x3d, 0xea, 0xb1, 0x1e, 0x8b, 0x25, 0x35, 0xfa, 0x94, 0x4c, 0x94, 0x8a,
	0x26, 0x0b, 0x1c, 0x16, 0xe0, 0x44, 0x48, 0x8a, 0x54, 0x12, 0x7b, 0x8c, 0xf5, 0x6c, 0x50, 0xe3,
	0xca, 0xe8, 0x77, 0x55, 0xab, 0xef, 0x93, 0x90, 0x32, 0x77, 0xa2, 0x27, 0xb4, 0x6a, 0x90, 0x00,
	0xd4, 0x41, 0xcd, 0x80, 0x90, 0xd4, 0x54, 0x93, 0xd1, 0x54, 0x97, 0x3f, 0x2e, 0xa1, 0xc5, 0x4e,
	0x7c, 0x1d, 0x4f, 0xd0, 0x9a, 0xd7, 0x25, 0xae, 0x85, 0x3d, 0xf0, 0x31, 0xeb, 0x76, 0xc1, 0x17,
	0xb8, 0x32, 0x57, 0x5d, 0xd9, 0x29, 0x2a, 0xa9, 0x65, 0xb4, 0x44, 0x49, 0x97, 0x28, 0xbb, 0x8c,
	0xba, 0x9a, 0x78, 0x35, 0x92, 0x72, 0xe3, 0x91, 0xf4, 0x78, 0x48, 0x1c, 0xfb, 0x95, 0x9c, 0x99,
	0x97, 0xf5, 0x7c, 0xdc, 0xe9, 0x80, 0x7f, 0x18, 0xd5, 0xfc, 0x5b, 0xf4, 0xdf, 0x80, 0xd8, 0xfd,
	0xf8, 0x40, 0xdc, 0x05, 0xc0, 0x9e, 0x19, 0x0a, 0x73, 0x65, 0xae, 0xba, 0xac, 0x6d, 0x8f, 0x47,
	0x92, 0x90, 0x6c, 0xf9, 0x05, 0x91, 0xbf, 0x7e, 0x79, 0x8e, 0xd2, 0x1b, 0x1a, 0x60, 0xea, 0x6b,
	0x77, 0xc4, 0x1e, 0x40, 0xc7, 0x0c, 0x79, 0x8a, 0x0a, 0xf7, 0x43, 0x1e, 0xf8, 0x94, 0x59, 0xc2,
	0x7c, 0x7a, 0x7b, 0x12, 0x90, 0x32, 0x09, 0x48, 0x69, 0xa4, 0x01, 0x69, 0x95, 0xf4, 0xf6, 0x8d,
	0xac, 0x6b, 0xb2, 0x40, 0xfe, 0xfc, 0x5d, 0xe2, 0xa6, 0xac, 0x3a, 0x71, 0x97, 0x3f, 0x45, 0x2b,
	0x06, 0xb5, 0x70, 0x48, 0x1d, 0x60, 0xfd, 0x50, 0x58, 0xf8, 0x9b, 0xcb, 0x24, 0x21, 0x3e, 0x71,
	0x99, 0x9a, 0x4d, 0x0c, 0x90, 0x41, 0xad, 0xe3, 0xa4, 0xc1, 0x0f, 0xd0, 0x13, 0x87, 0xba, 0xd4,
	0xe9, 0x3b, 0x38, 0xe2, 0x3c, 0xf0, 0x4d, 0x70, 0x43, 0x4c, 0x5d, 0xd3, 0x07, 0x12, 0x80, 0xf0,
	0x4f, 0x9c, 0xd4, 0xcb, 0xf1, 0x48, 0xaa, 0x24, 0xdb, 0xfe, 0x44, 0x67, 0x43, 0x2b, 0xa6, 0xb0,
	0x46, 0xa3, 0xf7, 0x88, 0xd0, 0x56, 0x4a, 0xf2, 0x1a, 0x5a, 0x73, 0xc8, 0x25, 0x76, 0x59, 0x08,
	0xd8, 0x06, 0xb7, 0x17, 0x9e, 0x09, 0x8b, 0x65, 0xae, 0x9a, 0xd7, 0x4a, 0xf7, 0x4f, 0x9b, 0x01,
	0x64, 0x3d, 0xef, 0x90, 0xcb, 0x03, 0x16, 0x42, 0x3b, 0xae, 0xf9, 0x77, 0x48, 0x30, 0x6c, 0x66,
	0x9e, 0x63, 0x0b, 0x6c, 0x32, 0xc4, 0x06, 0x74, 0x99, 0x0f, 0xd8, 0xb4, 0x59, 0x00, 0xc2, 0x52,
	0x99, 0xab, 0x2e, 0x68, 0x95, 0xf1, 0x48, 0x92, 0xd2, 0x14, 0x1e, 0x20, 0x65, 0x7d, 0x3d, 0x96,
	0x1a, 0x91, 0xa2, 0xc5, 0xc2, 0x6e, 0xd4, 0xe7, 0x5d, 0x24, 0xfe, 0x66, 0xc6, 0xa6, 0xef, 0xfb,
	0xd4, 0x8a, 0x73, 0x16, 0xfe, 0x8d, 0x3d, 0xb6, 0xc6, 0x23, 0xe9, 0xe9, 0x83, 0x1e, 0x53, 0xbc,
	0xac, 0x6f, 0x66, 0x9d, 0xda, 0xf7, 0x2a, 0x7f, 0x8e, 0x56, 0x89, 0x6f, 0xd0, 0xd0, 0x27, 0x3d,
	0xc0, 0x0e, 0xb3, 0x40, 0x58, 0x2e, 0x73, 0xd5, 0xd5, 0x9d, 0x2d, 0xe5, 0xe1, 0x1f, 0xaf, 0x52,
	0x9f, 0x4c, 0xec, 0x33, 0x0b, 0xb4, 0xe2, 0x78, 0x24, 0xad, 0x27, 0xa7, 0xcc, 0xae, 0x92, 0xf5,
	0x3c, 0x99, 0x26, 0xb7, 0x3f, 0x70, 0x28, 0x3f, 0x33, 0xcb, 0x8b, 0xa8, 0x54, 0xd7, 0xb5, 0xd6,
	0xb1, 0x5e, 0x7f, 0xd3, 0xc4, 0xfb, 0x87, 0x8d, 0x26, 0x3e, 0x39, 0x38, 0xea, 0x34, 0x77, 0x5b,
	0x7b, 0xad, 0x66, 0xa3, 0x90, 0xe3, 0x37, 0xd1, 0x46, 0x46, 0x6f, 0xb4, 0x8e, 0xea, 0x5a, 0xbb,
	0xd9, 0x28, 0x70, 0x7c, 0x11, 0xad, 0x67, 0xc4, 0xfd, 0xfa, 0xc1, 0x49, 0xbd, 0x5d, 0x98, 0xe3,
	0x37, 0xd0, 0xff, 0x19, 0xa9, 0x7e, 0x72, 0x7c, 0x58, 0x98, 0xd7, 0x5e, 0x5f, 0xdd, 0x88, 0xdc,
	0xf5, 0x8d, 0xc8, 0xfd, 0xb8, 0x11, 0xb9, 0x4f, 0xb7, 0x62, 0xee, 0xfa, 0x56, 0xcc, 0x7d, 0xbb,
	0x15, 0x73, 0xa7, 0x95, 0xd9, 0x2f, 0x6c, 0x32, 0x47, 0xbd, 0x9c, 0xfa, 0x73, 0x0b, 0x87, 0x1e,
	0x04, 0xc6, 0x62, 0xac, 0xbf, 0xf8, 0x19, 0x00, 0x00, 0xff, 0xff, 0x76, 0xc6, 0xd9, 0x5d, 0x04,
	0x05, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ArbitrageMode != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ArbitrageMode))
		i--
		dAtA[i] = 0x48
	}
	if m.BlockDelayBeforeLiquidation != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BlockDelayBeforeLiquidation))
		i--
		dAtA[i] = 0x40
	}
	if m.BlockDelayBeforeClose != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BlockDelayBeforeClose))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxNoteLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxNoteLength))
		i--
		dAtA[i] = 0x30
	}
	if len(m.MinimumBidPercentIncrease) > 0 {
		i -= len(m.MinimumBidPercentIncrease)
		copy(dAtA[i:], m.MinimumBidPercentIncrease)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MinimumBidPercentIncrease)))
		i--
		dAtA[i] = 0x2a
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.BidTimeout, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.BidTimeout):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x22
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ValuationPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ValuationPeriod):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	if len(m.ValuationFeePct) > 0 {
		i -= len(m.ValuationFeePct)
		copy(dAtA[i:], m.ValuationFeePct)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ValuationFeePct)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.PfandPerOffer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PfandPerOffer.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.ValuationFeePct)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ValuationPeriod)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.BidTimeout)
	n += 1 + l + sovParams(uint64(l))
	l = len(m.MinimumBidPercentIncrease)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MaxNoteLength != 0 {
		n += 1 + sovParams(uint64(m.MaxNoteLength))
	}
	if m.BlockDelayBeforeClose != 0 {
		n += 1 + sovParams(uint64(m.BlockDelayBeforeClose))
	}
	if m.BlockDelayBeforeLiquidation != 0 {
		n += 1 + sovParams(uint64(m.BlockDelayBeforeLiquidation))
	}
	if m.ArbitrageMode != 0 {
		n += 1 + sovParams(uint64(m.ArbitrageMode))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PfandPerOffer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PfandPerOffer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValuationFeePct", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValuationFeePct = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValuationPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ValuationPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.BidTimeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumBidPercentIncrease", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinimumBidPercentIncrease = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNoteLength", wireType)
			}
			m.MaxNoteLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxNoteLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockDelayBeforeClose", wireType)
			}
			m.BlockDelayBeforeClose = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockDelayBeforeClose |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockDelayBeforeLiquidation", wireType)
			}
			m.BlockDelayBeforeLiquidation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockDelayBeforeLiquidation |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArbitrageMode", wireType)
			}
			m.ArbitrageMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ArbitrageMode |= ArbitrageMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
