// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dysonprotocol/whaleswap/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_CreatePool_FullMethodName            = "/dysonprotocol.whaleswap.v1.Msg/CreatePool"
	Msg_UpdatePoolConfig_FullMethodName      = "/dysonprotocol.whaleswap.v1.Msg/UpdatePoolConfig"
	Msg_AddLiquidity_FullMethodName          = "/dysonprotocol.whaleswap.v1.Msg/AddLiquidity"
	Msg_RemoveLiquidity_FullMethodName       = "/dysonprotocol.whaleswap.v1.Msg/RemoveLiquidity"
	Msg_PoolSwap_FullMethodName              = "/dysonprotocol.whaleswap.v1.Msg/PoolSwap"
	Msg_MakeTrade_FullMethodName             = "/dysonprotocol.whaleswap.v1.Msg/MakeTrade"
	Msg_MakeOffer_FullMethodName             = "/dysonprotocol.whaleswap.v1.Msg/MakeOffer"
	Msg_TakeOffer_FullMethodName             = "/dysonprotocol.whaleswap.v1.Msg/TakeOffer"
	Msg_CancelOffer_FullMethodName           = "/dysonprotocol.whaleswap.v1.Msg/CancelOffer"
	Msg_OpenAuction_FullMethodName           = "/dysonprotocol.whaleswap.v1.Msg/OpenAuction"
	Msg_RedeemAuction_FullMethodName         = "/dysonprotocol.whaleswap.v1.Msg/RedeemAuction"
	Msg_OpenPosition_FullMethodName          = "/dysonprotocol.whaleswap.v1.Msg/OpenPosition"
	Msg_ClosePosition_FullMethodName         = "/dysonprotocol.whaleswap.v1.Msg/ClosePosition"
	Msg_AddCollateral_FullMethodName         = "/dysonprotocol.whaleswap.v1.Msg/AddCollateral"
	Msg_CoverPosition_FullMethodName         = "/dysonprotocol.whaleswap.v1.Msg/CoverPosition"
	Msg_InitializeLiquidation_FullMethodName = "/dysonprotocol.whaleswap.v1.Msg/InitializeLiquidation"
	Msg_FinalizeLiquidation_FullMethodName   = "/dysonprotocol.whaleswap.v1.Msg/FinalizeLiquidation"
	Msg_UpdateParams_FullMethodName          = "/dysonprotocol.whaleswap.v1.Msg/UpdateParams"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Conventions used across whaleswap messages:
//
//   - Denom pair canonicalization: Internally, any denom pair is ordered
//     lexicographically as pairKey = min(denom1, denom2) | max(denom1, denom2).
//     Callers may provide denoms in any order; the keeper normalizes.
//
//   - Price orientation: Unless otherwise stated, price is expressed as
//     want-per-have in the high-per-low orientation relative to the canonical
//     pair: P = (amount of high denom) / (amount of low denom). This choice makes
//     lexicographic ordering of fixed-precision decimal strings align with
//     numeric ordering for indexes and range scans.
//
//   - Decimal fields: cosmos.Dec are encoded as strings; callers MUST provide
//     syntactically valid decimal strings, and the keeper validates ranges.
//
//   - Coins arrays in price bands: When used to express a ratio, the field must
//     be either empty (unset) or contain exactly two coins whose denoms match the
//     pool's reserve denoms, representing coin_b / coin_a.
//
//   - Settlement modes: Orderbook offers specify how the 'have' is funded:
//     ESCROW (escrow base have at creation) or LIQUID (no escrow; lock PFAND and
//     settle from maker balance at take).
//
// Msg defines the whaleswap Msg service.
type MsgClient interface {
	// *
	// CreatePool creates a two-asset pool with per-denom fee/interest/leverage
	// parameters and optional directional bound_percent limits.
	//
	// Behavior:
	//   - Input normalization: canonicalizes `coins` (exactly two positive coins)
	//     to the pool's denom order.
	//   - Fees and rates: normalizes `fee_rate` and `interest_rate` to exactly two
	//     DecCoins in pool order; requires 0 <= fee_rate < 1 per denom and
	//     interest_rate >= 0 per denom.
	//   - Leverage configuration: `min_inital_collateral_ratio` (required) and
	//     `liquidation_threshold` (required).
	//   - `max_borrow_percent` (required) must have exactly two entries with
	//
	// amounts in [0,1).
	//   - Bound percent (optional): when omitted defaults to 1 (unbounded) for both
	//     denoms. When provided, must contain exactly two DecCoins matching pool
	//     denoms with amounts in (0,1]; 1 disables the bound for that denom.
	//   - Funds and shares: sends initial reserves from `creator` → module;
	//     allocates a new pool_id; persists the pool; computes initial shares as
	//     floor(sqrt(x*y)); ensures at least one share; mints pool shares and sends
	//     them to the creator.
	//   - Invariants: asserts AMM and module invariants before returning.
	//
	// Validation:
	// - coins must contain exactly two positive coins with valid denoms.
	// - fee_rate amounts must satisfy 0 <= x < 1 for both denoms when provided.
	// - interest_rate amounts must be >= 0 for both denoms when provided.
	// - min_inital_collateral_ratio must have exactly two entries (> 1) matching
	// pool denoms in canonical order.
	//   - liquidation_threshold must have exactly two entries (> 1) matching pool
	//     denoms in canonical order.
	//   - max_borrow_percent must have exactly two entries with amounts in [0,1)
	//     matching pool denoms in canonical order.
	//   - bound_percent when provided must contain at most two entries with amounts
	//     in (0,1] matching pool denoms.
	//
	// Emits:
	// - EventPoolCreated(pool_id)
	// - EventPoolUpdate(pool_id)
	//
	// Returns:
	// - pool_id of the newly created pool (see response).
	CreatePool(ctx context.Context, in *MsgCreatePool, opts ...grpc.CallOption) (*MsgCreatePoolResponse, error)
	// *
	// UpdatePoolConfig updates pool fees, leverage/threshold params, interest,
	// optional max_borrow_percent, and bound_percent; majority-owner only.
	//
	// Behavior:
	// - Loads pool; validates signer and majority-ownership.
	// - Fee rates: optional; normalizes to two DecCoins (pool order); 0 <= x < 1.
	// - Leverage config: required `min_inital_collateral_ratio` with exactly two
	// entries matching pool denoms; each > 1.
	// - Liquidation threshold: required with exactly two entries; each > 1.
	// - Interest rate: allows 0/1/2 entries; normalizes to two; each >= 0.
	// - Max borrow percent: optional; if provided exactly two entries; 0 <= x
	// < 1.
	//   - Bound percent: optional; when provided must contain exactly two DecCoins
	//     matching pool denoms with amounts in (0,1]; 1 disables the bound. Omit to
	//     leave existing bounds unchanged.
	//   - Persists pool with `updated` timestamp; emits EventPoolUpdate; asserts
	//
	// AMM and module invariants.
	//
	// Validation:
	// - Pool must exist.
	// - Signer must be valid address and hold majority of pool shares.
	// - Fee rates when provided must satisfy 0 <= x < 1 for both denoms.
	// - Leverage config (min_inital_collateral_ratio) must have exactly two
	// entries (> 1) matching pool denoms in canonical order.
	//   - Liquidation threshold must have exactly two entries (> 1) matching pool
	//     denoms in canonical order.
	//   - Interest rates when provided must be >= 0 for both denoms.
	//   - Max borrow percent when provided must have exactly two entries with
	//
	// amounts in [0,1) matching pool denoms in canonical order.
	//   - Bound percent when provided must contain at most two entries with amounts
	//     in (0,1] matching pool denoms.
	//
	// Emits:
	// - EventPoolUpdate(pool_id)
	//
	// Returns:
	// - Empty response.
	UpdatePoolConfig(ctx context.Context, in *MsgUpdatePoolConfig, opts ...grpc.CallOption) (*MsgUpdatePoolConfigResponse, error)
	// *
	// AddLiquidity (owner-only) escrows provided amounts, refunds any unused
	// amounts, mints shares, and asserts AMM invariants.
	//
	// Behavior:
	//   - Loads pool; validates signer majority ownership.
	//   - Escrows full provided amounts first, then refunds unused surplus.
	//   - Computes shares as floor(min(add1/R1, add2/R2) × totalShares).
	//   - Updates pool reserves with used amounts.
	//   - Mints computed shares via nameservice and transfers to signer.
	//   - Persists pool with updated reserves/timestamp; emits events; asserts AMM
	//     and module invariants.
	//
	// Validation:
	//   - Pool must exist and have exactly two positive reserves.
	//   - Signer must be valid address and hold majority of pool shares.
	//   - Amounts must contain exactly two positive coins matching pool denoms in
	//     canonical order.
	//
	// Emits:
	// - EventPoolUpdate (after persisting pool state)
	// - EventPoolLiquidityAdded (pool_id, shares_minted)
	AddLiquidity(ctx context.Context, in *MsgAddLiquidity, opts ...grpc.CallOption) (*MsgAddLiquidityResponse, error)
	// *
	// RemoveLiquidity burns the caller's shares and returns the underlying
	// reserves proportional to the share burned.
	RemoveLiquidity(ctx context.Context, in *MsgRemoveLiquidity, opts ...grpc.CallOption) (*MsgRemoveLiquidityResponse, error)
	// *
	// PoolSwap executes one or more exact-in or exact-out pool swap legs with a
	// single end-of-tx settlement. Applies output-side fees per leg and enforces
	// aggregate max_input caps and min_output guarantees.
	PoolSwap(ctx context.Context, in *MsgPoolSwap, opts ...grpc.CallOption) (*MsgPoolSwapResponse, error)
	// *
	// MakeTrade combines AMM pool swaps and orderbook takes into a single
	// transaction with end-of-tx settlement.
	MakeTrade(ctx context.Context, in *MsgMakeTrade, opts ...grpc.CallOption) (*MsgMakeTradeResponse, error)
	// *
	// MakeOffer creates an orderbook offer. ESCROW: base "have" is escrowed.
	// LIQUID: lock PFAND; settlement draws from maker balance at take. Units are
	// derived via GCD for partial fills.
	MakeOffer(ctx context.Context, in *MsgMakeOffer, opts ...grpc.CallOption) (*MsgMakeOfferResponse, error)
	// *
	// TakeOffer executes one or more orderbook takes with netting and settlement.
	TakeOffer(ctx context.Context, in *MsgTakeOffer, opts ...grpc.CallOption) (*MsgTakeOfferResponse, error)
	// *
	// CancelOffer (maker or authorized third party) cancels an open offer and
	// refunds escrowed assets to the maker while releasing PFAND to the closer.
	CancelOffer(ctx context.Context, in *MsgCancelOffer, opts ...grpc.CallOption) (*MsgCancelOfferResponse, error)
	// *
	// OpenAuction escrows the sell coin and mints an NFT under a class keyed by
	// bid_denom; class policy (listing/valuation/bid timeouts/allowed denoms) is
	// set from module params.
	OpenAuction(ctx context.Context, in *MsgOpenAuction, opts ...grpc.CallOption) (*MsgOpenAuctionResponse, error)
	// *
	// RedeemAuction lets the current NFT owner redeem when no bid is active;
	// burns the NFT and returns escrow. If owner != original seller and a
	// valuation exists in bid_denom, a trade record is emitted.
	RedeemAuction(ctx context.Context, in *MsgRedeemAuction, opts ...grpc.CallOption) (*MsgRedeemAuctionResponse, error)
	// *
	// OpenPosition creates a leveraged position by borrowing against collateral,
	// swapping to held asset, and recording the position with interest snapshots.
	OpenPosition(ctx context.Context, in *MsgOpenPosition, opts ...grpc.CallOption) (*MsgOpenPositionResponse, error)
	// *
	// ClosePosition swaps held to borrowed, repays principal+interest, returns
	// remaining collateral and any profit, updates pool accounting, and deletes
	// the position (respects block delay).
	ClosePosition(ctx context.Context, in *MsgClosePosition, opts ...grpc.CallOption) (*MsgClosePositionResponse, error)
	// *
	// AddCollateral deposits additional collateral to a leveraged position and
	// clears liquidation markers.
	AddCollateral(ctx context.Context, in *MsgAddCollateral, opts ...grpc.CallOption) (*MsgAddCollateralResponse, error)
	// *
	// CoverPosition repays accrued interest; optionally reduces principal or
	// auto-closes on full repayment.
	CoverPosition(ctx context.Context, in *MsgCoverPosition, opts ...grpc.CallOption) (*MsgCoverPositionResponse, error)
	// *
	// InitializeLiquidation (permissionless) marks a position liquidatable when
	// its collateral ratio (with accrued interest at the snapshotted rate) falls
	// below the pool's liquidation_threshold and starts the block-delay
	// countdown.
	InitializeLiquidation(ctx context.Context, in *MsgInitializeLiquidation, opts ...grpc.CallOption) (*MsgInitializeLiquidationResponse, error)
	// *
	// FinalizeLiquidation (permissionless) completes leveraged position
	// liquidation.
	FinalizeLiquidation(ctx context.Context, in *MsgFinalizeLiquidation, opts ...grpc.CallOption) (*MsgFinalizeLiquidationResponse, error)
	// *
	// UpdateParams (authority-only) updates module parameters.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreatePool(ctx context.Context, in *MsgCreatePool, opts ...grpc.CallOption) (*MsgCreatePoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCreatePoolResponse)
	err := c.cc.Invoke(ctx, Msg_CreatePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdatePoolConfig(ctx context.Context, in *MsgUpdatePoolConfig, opts ...grpc.CallOption) (*MsgUpdatePoolConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdatePoolConfigResponse)
	err := c.cc.Invoke(ctx, Msg_UpdatePoolConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddLiquidity(ctx context.Context, in *MsgAddLiquidity, opts ...grpc.CallOption) (*MsgAddLiquidityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgAddLiquidityResponse)
	err := c.cc.Invoke(ctx, Msg_AddLiquidity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveLiquidity(ctx context.Context, in *MsgRemoveLiquidity, opts ...grpc.CallOption) (*MsgRemoveLiquidityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRemoveLiquidityResponse)
	err := c.cc.Invoke(ctx, Msg_RemoveLiquidity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PoolSwap(ctx context.Context, in *MsgPoolSwap, opts ...grpc.CallOption) (*MsgPoolSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgPoolSwapResponse)
	err := c.cc.Invoke(ctx, Msg_PoolSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MakeTrade(ctx context.Context, in *MsgMakeTrade, opts ...grpc.CallOption) (*MsgMakeTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgMakeTradeResponse)
	err := c.cc.Invoke(ctx, Msg_MakeTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MakeOffer(ctx context.Context, in *MsgMakeOffer, opts ...grpc.CallOption) (*MsgMakeOfferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgMakeOfferResponse)
	err := c.cc.Invoke(ctx, Msg_MakeOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TakeOffer(ctx context.Context, in *MsgTakeOffer, opts ...grpc.CallOption) (*MsgTakeOfferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgTakeOfferResponse)
	err := c.cc.Invoke(ctx, Msg_TakeOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelOffer(ctx context.Context, in *MsgCancelOffer, opts ...grpc.CallOption) (*MsgCancelOfferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCancelOfferResponse)
	err := c.cc.Invoke(ctx, Msg_CancelOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) OpenAuction(ctx context.Context, in *MsgOpenAuction, opts ...grpc.CallOption) (*MsgOpenAuctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgOpenAuctionResponse)
	err := c.cc.Invoke(ctx, Msg_OpenAuction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RedeemAuction(ctx context.Context, in *MsgRedeemAuction, opts ...grpc.CallOption) (*MsgRedeemAuctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRedeemAuctionResponse)
	err := c.cc.Invoke(ctx, Msg_RedeemAuction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) OpenPosition(ctx context.Context, in *MsgOpenPosition, opts ...grpc.CallOption) (*MsgOpenPositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgOpenPositionResponse)
	err := c.cc.Invoke(ctx, Msg_OpenPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClosePosition(ctx context.Context, in *MsgClosePosition, opts ...grpc.CallOption) (*MsgClosePositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgClosePositionResponse)
	err := c.cc.Invoke(ctx, Msg_ClosePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddCollateral(ctx context.Context, in *MsgAddCollateral, opts ...grpc.CallOption) (*MsgAddCollateralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgAddCollateralResponse)
	err := c.cc.Invoke(ctx, Msg_AddCollateral_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CoverPosition(ctx context.Context, in *MsgCoverPosition, opts ...grpc.CallOption) (*MsgCoverPositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCoverPositionResponse)
	err := c.cc.Invoke(ctx, Msg_CoverPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InitializeLiquidation(ctx context.Context, in *MsgInitializeLiquidation, opts ...grpc.CallOption) (*MsgInitializeLiquidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgInitializeLiquidationResponse)
	err := c.cc.Invoke(ctx, Msg_InitializeLiquidation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FinalizeLiquidation(ctx context.Context, in *MsgFinalizeLiquidation, opts ...grpc.CallOption) (*MsgFinalizeLiquidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgFinalizeLiquidationResponse)
	err := c.cc.Invoke(ctx, Msg_FinalizeLiquidation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Conventions used across whaleswap messages:
//
//   - Denom pair canonicalization: Internally, any denom pair is ordered
//     lexicographically as pairKey = min(denom1, denom2) | max(denom1, denom2).
//     Callers may provide denoms in any order; the keeper normalizes.
//
//   - Price orientation: Unless otherwise stated, price is expressed as
//     want-per-have in the high-per-low orientation relative to the canonical
//     pair: P = (amount of high denom) / (amount of low denom). This choice makes
//     lexicographic ordering of fixed-precision decimal strings align with
//     numeric ordering for indexes and range scans.
//
//   - Decimal fields: cosmos.Dec are encoded as strings; callers MUST provide
//     syntactically valid decimal strings, and the keeper validates ranges.
//
//   - Coins arrays in price bands: When used to express a ratio, the field must
//     be either empty (unset) or contain exactly two coins whose denoms match the
//     pool's reserve denoms, representing coin_b / coin_a.
//
//   - Settlement modes: Orderbook offers specify how the 'have' is funded:
//     ESCROW (escrow base have at creation) or LIQUID (no escrow; lock PFAND and
//     settle from maker balance at take).
//
// Msg defines the whaleswap Msg service.
type MsgServer interface {
	// *
	// CreatePool creates a two-asset pool with per-denom fee/interest/leverage
	// parameters and optional directional bound_percent limits.
	//
	// Behavior:
	//   - Input normalization: canonicalizes `coins` (exactly two positive coins)
	//     to the pool's denom order.
	//   - Fees and rates: normalizes `fee_rate` and `interest_rate` to exactly two
	//     DecCoins in pool order; requires 0 <= fee_rate < 1 per denom and
	//     interest_rate >= 0 per denom.
	//   - Leverage configuration: `min_inital_collateral_ratio` (required) and
	//     `liquidation_threshold` (required).
	//   - `max_borrow_percent` (required) must have exactly two entries with
	//
	// amounts in [0,1).
	//   - Bound percent (optional): when omitted defaults to 1 (unbounded) for both
	//     denoms. When provided, must contain exactly two DecCoins matching pool
	//     denoms with amounts in (0,1]; 1 disables the bound for that denom.
	//   - Funds and shares: sends initial reserves from `creator` → module;
	//     allocates a new pool_id; persists the pool; computes initial shares as
	//     floor(sqrt(x*y)); ensures at least one share; mints pool shares and sends
	//     them to the creator.
	//   - Invariants: asserts AMM and module invariants before returning.
	//
	// Validation:
	// - coins must contain exactly two positive coins with valid denoms.
	// - fee_rate amounts must satisfy 0 <= x < 1 for both denoms when provided.
	// - interest_rate amounts must be >= 0 for both denoms when provided.
	// - min_inital_collateral_ratio must have exactly two entries (> 1) matching
	// pool denoms in canonical order.
	//   - liquidation_threshold must have exactly two entries (> 1) matching pool
	//     denoms in canonical order.
	//   - max_borrow_percent must have exactly two entries with amounts in [0,1)
	//     matching pool denoms in canonical order.
	//   - bound_percent when provided must contain at most two entries with amounts
	//     in (0,1] matching pool denoms.
	//
	// Emits:
	// - EventPoolCreated(pool_id)
	// - EventPoolUpdate(pool_id)
	//
	// Returns:
	// - pool_id of the newly created pool (see response).
	CreatePool(context.Context, *MsgCreatePool) (*MsgCreatePoolResponse, error)
	// *
	// UpdatePoolConfig updates pool fees, leverage/threshold params, interest,
	// optional max_borrow_percent, and bound_percent; majority-owner only.
	//
	// Behavior:
	// - Loads pool; validates signer and majority-ownership.
	// - Fee rates: optional; normalizes to two DecCoins (pool order); 0 <= x < 1.
	// - Leverage config: required `min_inital_collateral_ratio` with exactly two
	// entries matching pool denoms; each > 1.
	// - Liquidation threshold: required with exactly two entries; each > 1.
	// - Interest rate: allows 0/1/2 entries; normalizes to two; each >= 0.
	// - Max borrow percent: optional; if provided exactly two entries; 0 <= x
	// < 1.
	//   - Bound percent: optional; when provided must contain exactly two DecCoins
	//     matching pool denoms with amounts in (0,1]; 1 disables the bound. Omit to
	//     leave existing bounds unchanged.
	//   - Persists pool with `updated` timestamp; emits EventPoolUpdate; asserts
	//
	// AMM and module invariants.
	//
	// Validation:
	// - Pool must exist.
	// - Signer must be valid address and hold majority of pool shares.
	// - Fee rates when provided must satisfy 0 <= x < 1 for both denoms.
	// - Leverage config (min_inital_collateral_ratio) must have exactly two
	// entries (> 1) matching pool denoms in canonical order.
	//   - Liquidation threshold must have exactly two entries (> 1) matching pool
	//     denoms in canonical order.
	//   - Interest rates when provided must be >= 0 for both denoms.
	//   - Max borrow percent when provided must have exactly two entries with
	//
	// amounts in [0,1) matching pool denoms in canonical order.
	//   - Bound percent when provided must contain at most two entries with amounts
	//     in (0,1] matching pool denoms.
	//
	// Emits:
	// - EventPoolUpdate(pool_id)
	//
	// Returns:
	// - Empty response.
	UpdatePoolConfig(context.Context, *MsgUpdatePoolConfig) (*MsgUpdatePoolConfigResponse, error)
	// *
	// AddLiquidity (owner-only) escrows provided amounts, refunds any unused
	// amounts, mints shares, and asserts AMM invariants.
	//
	// Behavior:
	//   - Loads pool; validates signer majority ownership.
	//   - Escrows full provided amounts first, then refunds unused surplus.
	//   - Computes shares as floor(min(add1/R1, add2/R2) × totalShares).
	//   - Updates pool reserves with used amounts.
	//   - Mints computed shares via nameservice and transfers to signer.
	//   - Persists pool with updated reserves/timestamp; emits events; asserts AMM
	//     and module invariants.
	//
	// Validation:
	//   - Pool must exist and have exactly two positive reserves.
	//   - Signer must be valid address and hold majority of pool shares.
	//   - Amounts must contain exactly two positive coins matching pool denoms in
	//     canonical order.
	//
	// Emits:
	// - EventPoolUpdate (after persisting pool state)
	// - EventPoolLiquidityAdded (pool_id, shares_minted)
	AddLiquidity(context.Context, *MsgAddLiquidity) (*MsgAddLiquidityResponse, error)
	// *
	// RemoveLiquidity burns the caller's shares and returns the underlying
	// reserves proportional to the share burned.
	RemoveLiquidity(context.Context, *MsgRemoveLiquidity) (*MsgRemoveLiquidityResponse, error)
	// *
	// PoolSwap executes one or more exact-in or exact-out pool swap legs with a
	// single end-of-tx settlement. Applies output-side fees per leg and enforces
	// aggregate max_input caps and min_output guarantees.
	PoolSwap(context.Context, *MsgPoolSwap) (*MsgPoolSwapResponse, error)
	// *
	// MakeTrade combines AMM pool swaps and orderbook takes into a single
	// transaction with end-of-tx settlement.
	MakeTrade(context.Context, *MsgMakeTrade) (*MsgMakeTradeResponse, error)
	// *
	// MakeOffer creates an orderbook offer. ESCROW: base "have" is escrowed.
	// LIQUID: lock PFAND; settlement draws from maker balance at take. Units are
	// derived via GCD for partial fills.
	MakeOffer(context.Context, *MsgMakeOffer) (*MsgMakeOfferResponse, error)
	// *
	// TakeOffer executes one or more orderbook takes with netting and settlement.
	TakeOffer(context.Context, *MsgTakeOffer) (*MsgTakeOfferResponse, error)
	// *
	// CancelOffer (maker or authorized third party) cancels an open offer and
	// refunds escrowed assets to the maker while releasing PFAND to the closer.
	CancelOffer(context.Context, *MsgCancelOffer) (*MsgCancelOfferResponse, error)
	// *
	// OpenAuction escrows the sell coin and mints an NFT under a class keyed by
	// bid_denom; class policy (listing/valuation/bid timeouts/allowed denoms) is
	// set from module params.
	OpenAuction(context.Context, *MsgOpenAuction) (*MsgOpenAuctionResponse, error)
	// *
	// RedeemAuction lets the current NFT owner redeem when no bid is active;
	// burns the NFT and returns escrow. If owner != original seller and a
	// valuation exists in bid_denom, a trade record is emitted.
	RedeemAuction(context.Context, *MsgRedeemAuction) (*MsgRedeemAuctionResponse, error)
	// *
	// OpenPosition creates a leveraged position by borrowing against collateral,
	// swapping to held asset, and recording the position with interest snapshots.
	OpenPosition(context.Context, *MsgOpenPosition) (*MsgOpenPositionResponse, error)
	// *
	// ClosePosition swaps held to borrowed, repays principal+interest, returns
	// remaining collateral and any profit, updates pool accounting, and deletes
	// the position (respects block delay).
	ClosePosition(context.Context, *MsgClosePosition) (*MsgClosePositionResponse, error)
	// *
	// AddCollateral deposits additional collateral to a leveraged position and
	// clears liquidation markers.
	AddCollateral(context.Context, *MsgAddCollateral) (*MsgAddCollateralResponse, error)
	// *
	// CoverPosition repays accrued interest; optionally reduces principal or
	// auto-closes on full repayment.
	CoverPosition(context.Context, *MsgCoverPosition) (*MsgCoverPositionResponse, error)
	// *
	// InitializeLiquidation (permissionless) marks a position liquidatable when
	// its collateral ratio (with accrued interest at the snapshotted rate) falls
	// below the pool's liquidation_threshold and starts the block-delay
	// countdown.
	InitializeLiquidation(context.Context, *MsgInitializeLiquidation) (*MsgInitializeLiquidationResponse, error)
	// *
	// FinalizeLiquidation (permissionless) completes leveraged position
	// liquidation.
	FinalizeLiquidation(context.Context, *MsgFinalizeLiquidation) (*MsgFinalizeLiquidationResponse, error)
	// *
	// UpdateParams (authority-only) updates module parameters.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) CreatePool(context.Context, *MsgCreatePool) (*MsgCreatePoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePool not implemented")
}
func (UnimplementedMsgServer) UpdatePoolConfig(context.Context, *MsgUpdatePoolConfig) (*MsgUpdatePoolConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePoolConfig not implemented")
}
func (UnimplementedMsgServer) AddLiquidity(context.Context, *MsgAddLiquidity) (*MsgAddLiquidityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLiquidity not implemented")
}
func (UnimplementedMsgServer) RemoveLiquidity(context.Context, *MsgRemoveLiquidity) (*MsgRemoveLiquidityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveLiquidity not implemented")
}
func (UnimplementedMsgServer) PoolSwap(context.Context, *MsgPoolSwap) (*MsgPoolSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PoolSwap not implemented")
}
func (UnimplementedMsgServer) MakeTrade(context.Context, *MsgMakeTrade) (*MsgMakeTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeTrade not implemented")
}
func (UnimplementedMsgServer) MakeOffer(context.Context, *MsgMakeOffer) (*MsgMakeOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeOffer not implemented")
}
func (UnimplementedMsgServer) TakeOffer(context.Context, *MsgTakeOffer) (*MsgTakeOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeOffer not implemented")
}
func (UnimplementedMsgServer) CancelOffer(context.Context, *MsgCancelOffer) (*MsgCancelOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOffer not implemented")
}
func (UnimplementedMsgServer) OpenAuction(context.Context, *MsgOpenAuction) (*MsgOpenAuctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenAuction not implemented")
}
func (UnimplementedMsgServer) RedeemAuction(context.Context, *MsgRedeemAuction) (*MsgRedeemAuctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedeemAuction not implemented")
}
func (UnimplementedMsgServer) OpenPosition(context.Context, *MsgOpenPosition) (*MsgOpenPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenPosition not implemented")
}
func (UnimplementedMsgServer) ClosePosition(context.Context, *MsgClosePosition) (*MsgClosePositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClosePosition not implemented")
}
func (UnimplementedMsgServer) AddCollateral(context.Context, *MsgAddCollateral) (*MsgAddCollateralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCollateral not implemented")
}
func (UnimplementedMsgServer) CoverPosition(context.Context, *MsgCoverPosition) (*MsgCoverPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoverPosition not implemented")
}
func (UnimplementedMsgServer) InitializeLiquidation(context.Context, *MsgInitializeLiquidation) (*MsgInitializeLiquidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitializeLiquidation not implemented")
}
func (UnimplementedMsgServer) FinalizeLiquidation(context.Context, *MsgFinalizeLiquidation) (*MsgFinalizeLiquidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeLiquidation not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_CreatePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePool)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreatePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreatePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreatePool(ctx, req.(*MsgCreatePool))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdatePoolConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdatePoolConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdatePoolConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdatePoolConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdatePoolConfig(ctx, req.(*MsgUpdatePoolConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddLiquidity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddLiquidity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddLiquidity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AddLiquidity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddLiquidity(ctx, req.(*MsgAddLiquidity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveLiquidity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveLiquidity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveLiquidity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RemoveLiquidity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveLiquidity(ctx, req.(*MsgRemoveLiquidity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PoolSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPoolSwap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PoolSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_PoolSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PoolSwap(ctx, req.(*MsgPoolSwap))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MakeTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMakeTrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MakeTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_MakeTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MakeTrade(ctx, req.(*MsgMakeTrade))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MakeOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMakeOffer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MakeOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_MakeOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MakeOffer(ctx, req.(*MsgMakeOffer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TakeOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTakeOffer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TakeOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_TakeOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TakeOffer(ctx, req.(*MsgTakeOffer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelOffer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CancelOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelOffer(ctx, req.(*MsgCancelOffer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_OpenAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgOpenAuction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).OpenAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_OpenAuction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).OpenAuction(ctx, req.(*MsgOpenAuction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RedeemAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRedeemAuction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RedeemAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RedeemAuction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RedeemAuction(ctx, req.(*MsgRedeemAuction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_OpenPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgOpenPosition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).OpenPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_OpenPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).OpenPosition(ctx, req.(*MsgOpenPosition))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClosePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClosePosition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClosePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ClosePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClosePosition(ctx, req.(*MsgClosePosition))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddCollateral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddCollateral)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddCollateral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AddCollateral_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddCollateral(ctx, req.(*MsgAddCollateral))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CoverPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCoverPosition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CoverPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CoverPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CoverPosition(ctx, req.(*MsgCoverPosition))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InitializeLiquidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitializeLiquidation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InitializeLiquidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_InitializeLiquidation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InitializeLiquidation(ctx, req.(*MsgInitializeLiquidation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FinalizeLiquidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFinalizeLiquidation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FinalizeLiquidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_FinalizeLiquidation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FinalizeLiquidation(ctx, req.(*MsgFinalizeLiquidation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dysonprotocol.whaleswap.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePool",
			Handler:    _Msg_CreatePool_Handler,
		},
		{
			MethodName: "UpdatePoolConfig",
			Handler:    _Msg_UpdatePoolConfig_Handler,
		},
		{
			MethodName: "AddLiquidity",
			Handler:    _Msg_AddLiquidity_Handler,
		},
		{
			MethodName: "RemoveLiquidity",
			Handler:    _Msg_RemoveLiquidity_Handler,
		},
		{
			MethodName: "PoolSwap",
			Handler:    _Msg_PoolSwap_Handler,
		},
		{
			MethodName: "MakeTrade",
			Handler:    _Msg_MakeTrade_Handler,
		},
		{
			MethodName: "MakeOffer",
			Handler:    _Msg_MakeOffer_Handler,
		},
		{
			MethodName: "TakeOffer",
			Handler:    _Msg_TakeOffer_Handler,
		},
		{
			MethodName: "CancelOffer",
			Handler:    _Msg_CancelOffer_Handler,
		},
		{
			MethodName: "OpenAuction",
			Handler:    _Msg_OpenAuction_Handler,
		},
		{
			MethodName: "RedeemAuction",
			Handler:    _Msg_RedeemAuction_Handler,
		},
		{
			MethodName: "OpenPosition",
			Handler:    _Msg_OpenPosition_Handler,
		},
		{
			MethodName: "ClosePosition",
			Handler:    _Msg_ClosePosition_Handler,
		},
		{
			MethodName: "AddCollateral",
			Handler:    _Msg_AddCollateral_Handler,
		},
		{
			MethodName: "CoverPosition",
			Handler:    _Msg_CoverPosition_Handler,
		},
		{
			MethodName: "InitializeLiquidation",
			Handler:    _Msg_InitializeLiquidation_Handler,
		},
		{
			MethodName: "FinalizeLiquidation",
			Handler:    _Msg_FinalizeLiquidation_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dysonprotocol/whaleswap/v1/tx.proto",
}
